import { DocsContent } from './types';

export const docsAf: DocsContent = {
  sidebarTitle: 'Dokumentasie',
  sections: [
    { id: 'overview', title: 'Oorsig', description: 'Wat is Orion Safe?' },
    { id: 'quickstart', title: 'Snelaanvang', description: '5-minuut opstelgids' },
    { id: 'features', title: 'Kernkenmerke', description: 'Wat jy kan doen' },
    { id: 'roles', title: 'Rolle en Toestemmings', description: 'Wie kan wat doen' },
    { id: 'locks', title: 'Tydslotte en Vestiging', description: 'Skeduleer tokenvrystellings' },
    { id: 'tokens', title: 'Ondersteunde Tokens', description: 'USDC, XLM en meer' },
    { id: 'architecture', title: 'Hoe Dit Werk', description: 'Onder die enjinkap' },
    { id: 'security', title: 'Sekuriteit', description: 'Hoe ons jou veilig hou' },
    { id: 'faq', title: 'Algemene Vrae', description: 'Algemene vrae' },
    { id: 'roadmap', title: 'Padkaart', description: 'Wat kom volgende' },
  ],

  overview: {
    heading: 'Welkom by Orion Safe',
    intro:
      'Orion Safe is \'n **multi-handtekening tesourie-platform** wat op Stellar gebou is. ' +
      'Dink daaraan as \'n gedeelde bankrekening vir jou span, DAO of organisasie — maar met superkragte.',
    whyTitle: 'Hoekom Orion Safe Gebruik?',
    whyItems: [
      { emoji: '🔐', title: 'Geen Enkele Punt van Mislukking', desc: 'Veelvuldige goedkeurings word vereis — selfs al word een sleutel gekompromitteer, bly fondse veilig' },
      { emoji: '⚡', title: 'Blitsvinnig en Goedkoop', desc: 'Transaksies van ~5 sekondes, minder as $0.0001 per transaksie' },
      { emoji: '⏰', title: 'Tydgebaseerde Beheer', desc: 'Sluit tokens tot \'n datum, of stel hulle geleidelik oor tyd vry' },
      { emoji: '🌍', title: 'Volle Deursigtigheid', desc: 'Elke aksie word op die ketting aangeteken — deel leesalleen-skakels met enigeen' },
    ],
    perfectForTitle: 'Perfek Vir',
    perfectFor: [
      { icon: '🏛️', title: 'DAO\'s en Tesourieë', desc: 'Bestuur gemeenskapsfondse met deursigtige multi-handtekening-bestuur' },
      { icon: '👥', title: 'Spanne en Beginondernemings', desc: 'Beveilig maatskappytesourie met rolgebaseerde toegang' },
      { icon: '💼', title: 'Werknemervestiging', desc: '4-jaar tokenvestiging met 1-jaar klip, ten volle outomaties' },
      { icon: '🤝', title: 'Trustdienste', desc: '2-van-2 wedersydse ooreenkoms vir veilige transaksies' },
      { icon: '🎁', title: 'Toekennings en Salarisse', desc: 'Grootmaat tokenverspreidings met geskeduleerde vrystellings' },
      { icon: '📊', title: 'Beleggingsfondse', desc: 'Komiteegoedkeuring vir fondsbestuur' },
    ],
    liveTitle: 'Lewendig op Stellar Toetsnet',
    liveDesc:
      'Orion Safe is tans lewendig op die Stellar-toetsnet. Probeer dit nou met toetstokens! ' +
      'Hoofnet-bekendstelling beplan vir K4 2026 ná sekuriteitsoudit.',
  },

  quickstart: {
    heading: 'Snelaanvanggids',
    subtitle: 'Kry jou eerste kluis aan die gang in minder as 5 minute.',
    step1Title: 'Verbind Jou Beursie',
    step1Intro: 'Klik **"Verbind Beursie"** in die regter boonste hoek en kies jou voorkeurbeursie:',
    wallets: [
      { name: 'Freighter', note: 'Aanbeveel' },
      { name: 'Lobstr', note: 'Selfoonvriendelik' },
      { name: 'xBull', note: 'Kraggebruikers' },
      { name: 'Albedo', note: 'Webgebaseer' },
    ],
    noWalletTitle: 'Het jy nie \'n beursie nie?',
    noWalletDesc: 'Installeer {{freighter}} — dit is \'n gratis blaaieruitbreiding wat 2 minute neem om op te stel.',
    step2Title: 'Skep Jou Kluis',
    step2Items: [
      'Klik **"Skep Kluis"**',
      'Gee jou kluis \'n naam (bv. "Spantesourie")',
      'Voeg ondertekenaarbeursie-adresse by (mense wat transaksies kan goedkeur)',
      'Stel jou **drempel** — hoeveel goedkeurings benodig word',
    ],
    exampleLabel: 'Voorbeeld: 2-van-3 Multi-Handtekening',
    approvedLabel: '2/3 = Goedgekeur!',
    step3Title: 'Befonds Jou Kluis',
    step3Intro: 'Jou kluis het sy eie adres. Stuur tokens daarna soos enige Stellar-beursie:',
    step3Items: [
      'Kopieer jou kluisadres vanaf die kontroleskerm',
      'Stuur XLM, USDC of enige Stellar-token na daardie adres',
      'Fondse verskyn binne ~5 sekondes',
    ],
    proTipTitle: 'Pro-wenk',
    proTipDesc: 'Vir die toetsnet, kry gratis toets-XLM by die {{friendbot}}.',
    step4Title: 'Maak Jou Eerste Transaksie',
    step4Steps: [
      { title: 'Skep Voorstel', desc: 'Gaan na Transaksies → Nuut → Voer besonderhede in → Dien in' },
      { title: 'Versamel Goedkeurings', desc: 'Ander ondertekenaars hersien en klik "Keur goed"' },
      { title: 'Voer Uit', desc: 'Sodra die drempel bereik is, kan enigeen "Voer uit" klik' },
    ],
    doneTitle: '🎉 Dis al!',
    doneDesc:
      'Jy het nou \'n veilige multi-handtekening-kluis. Verken die kantbalk om tydslotte, ' +
      'vestigingskedules en meer gevorderde kenmerke te ontdek.',
  },

  features: {
    heading: 'Kernkenmerke',
    multiSig: {
      title: 'Multi-Handtekening Sekuriteit',
      desc: 'Vereis dat veelvuldige mense transaksies goedkeur. Jy kies die drempel — of dit 2-van-3 vir \'n klein span of 5-van-9 vir \'n groot DAO is.',
      configs: ['2-van-3', '3-van-5', '4-van-7', '5-van-9'],
    },
    proposal: {
      title: 'Voorstelgebaseerde Werkvloei',
      desc: 'Alle transaksies gaan deur \'n deursigtige voorstelproses. Geen verrassings, volle aanspreeklikheid.',
      steps: [
        { title: 'Stel voor', sub: 'Enige ondertekenaar' },
        { title: 'Keur goed', sub: 'Bereik drempel' },
        { title: 'Voer uit', sub: 'Enigeen' },
      ],
    },
    txTypes: {
      title: 'Transaksietipes',
      items: [
        { icon: '💸', title: 'Oordrag', desc: 'Stuur tokens onmiddellik ná goedkeuring. Eenvoudige, direkte betalings.' },
        { icon: '🔒', title: 'Tydslot', desc: 'Sluit tokens tot \'n spesifieke datum. Perfek vir trust of geskeduleerde vrystellings.' },
        { icon: '📈', title: 'Vestiging', desc: 'Geleidelike vrystelling oor tyd met opsionele klip. Ideaal vir werknemertokens.' },
      ],
    },
    dashboard: {
      title: 'Kontroleskerm-navigasie',
      views: [
        { name: 'Kontroleskerm', desc: 'Oorsig en statistieke' },
        { name: 'Bates', desc: 'Tokensaldo\'s' },
        { name: 'Transaksies', desc: 'Voorstelle en geskiedenis' },
        { name: 'Lede', desc: 'Ondertekenaars en rolle' },
        { name: 'Tydslotte', desc: 'Geskeduleerde vrystellings' },
        { name: 'Vestiging', desc: 'Tokenvestiging' },
        { name: 'Kontakte', desc: 'Adresboek' },
        { name: 'Instellings', desc: 'Konfigurasie' },
      ],
    },
    publicAccess: {
      title: 'Openbare Toegang en Deel',
      cards: [
        { title: '🔗 Openbare Kykskakel', desc: 'Deel \'n leesalleen-aansig met beleggers, ouditeure of die publiek. Hulle kan saldo\'s en aktiwiteit sien, maar kan geen aksies neem nie.' },
        { title: '🎁 Eisskakel', desc: 'Begunstigdes kan hul gesluite of gevestigde tokens direk eis met hul eie beursie — geen kluistoegang nodig nie.' },
      ],
    },
  },

  roles: {
    heading: 'Rolle en Toestemmings',
    intro: 'Orion Safe gebruik \'n rolgebaseerde stelsel om te beheer wie wat kan doen. Dit bied buigsaamheid terwyl sekuriteit gehandhaaf word.',
    cards: [
      { name: 'SuperAdmin', badge: 'Volle Beheer', desc: 'Volledige kluisbeheer. SuperAdmins kan alles doen, insluitend aksies wat die kluis se struktuur en sekuriteit raak.', canLabel: 'Kan:', can: 'Ondertekenaars byvoeg/verwyder, goedkeuringsdrempel verander, enige herroepbare slot kanselleer, kluisinstellings opdateer, plus alles wat Admins en Executors kan doen.' },
      { name: 'Admin', badge: 'Bedrywighede', desc: 'Daaglikse bedryfsbestuurder. Admins hanteer die meeste tesourie-aktiwiteite, maar kan nie die kluis se sekuriteitsinstellings verander nie.', canLabel: 'Kan:', can: 'Voorstelle skep, transaksies goedkeur, goedgekeurde transaksies uitvoer, tydslotte en vestigingskedules skep, kontakte bestuur.' },
      { name: 'Executor', badge: 'Keur goed en Voer uit', desc: 'Goedkeuringsgesag. Executors kan op voorstelle stem en goedgekeurde transaksies uitvoer, maar kan nie nuwes inisieer nie.', canLabel: 'Kan:', can: 'Voorstelle goedkeur of verwerp, transaksies wat die drempel bereik het, uitvoer.' },
      { name: 'Viewer', badge: 'Leesalleen', desc: 'Waarnemertoegang. Viewers kan alles sien, maar kan geen aksies neem nie. Perfek vir ouditeure of belanghebbendes.', canLabel: 'Kan:', can: 'Kluissaldo\'s, transaksiegeskiedenis, voorstelle, slotte en alle aktiwiteit bekyk.' },
    ],
    matrixTitle: 'Toestemmingsopsomming',
    matrixHeaders: { action: 'Aksie', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Bekyk kluis en saldo\'s', super: true, admin: true, exec: true, view: true },
      { action: 'Skep voorstelle', super: true, admin: true, exec: false, view: false },
      { action: 'Keur voorstelle goed', super: true, admin: true, exec: true, view: false },
      { action: 'Voer transaksies uit', super: true, admin: true, exec: true, view: false },
      { action: 'Skep tydslotte / vestiging', super: true, admin: true, exec: false, view: false },
      { action: 'Kanselleer herroepbare slotte', super: true, admin: false, exec: false, view: false },
      { action: 'Voeg ondertekenaars by/verwyder', super: true, admin: false, exec: false, view: false },
      { action: 'Verander drempel', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Beste Praktyk: Roltoewysing',
    bestPractice: [
      'Hou SuperAdmin tot 1-2 vertroude mense (stigters, uitvoerende beamptes)',
      'Gebruik Admin vir finansiële spanlede wat daaglikse bedrywighede bestuur',
      'Gebruik Executor vir direksielede wat net goedkeur, nie inisieer nie',
      'Gebruik Viewer vir belanghebbendes, ouditeure of openbare deursigtigheid',
    ],
  },

  locks: {
    heading: 'Tydslotte en Vestiging',
    intro: 'Beheer wanneer tokens beskikbaar word. Of jy nou trust, geskeduleerde betalings of werknemertokenvestiging nodig het — ons het jou gedek.',
    timeLockTitle: 'Tydslotte',
    timeLockDesc: 'Sluit tokens tot \'n spesifieke datum. Die begunstigde kan die **volle bedrag** slegs eis nadat die ontsluittyd verby is. Voor daardie datum is die tokens heeltemal ontoeganklik.',
    timeLockExampleLabel: 'Voorbeeld: Trustdeposito',
    timeLockExampleAmount: '10,000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Trust', desc: 'Hou fondse totdat voorwaardes nagekom is' },
      { icon: '🎯', title: 'Mylpaalbetalings', desc: 'Stel vry wanneer lewerbare voltooi is' },
      { icon: '🏦', title: 'Spaardoelwitte', desc: 'Voorkom impulsiewe onttrekkings' },
    ],
    vestingTitle: 'Vestigingskedules',
    vestingDesc: 'Stel tokens **geleidelik oor tyd** vry met \'n opsionele klipperiode. Dit is die industriestandaard vir werknemervergoeding en beleggerstoekennings.',
    vestingExampleLabel: 'Voorbeeld: 4-Jaar Werknemervestiging met 1-Jaar Klip',
    vestingExampleAmount: '100,000 tokens',
    vestingBarCliff: 'Klip (1 jr)',
    vestingBarLinear: 'Lineêre Vestiging → 100%',
    vestingTimeline: { start: 'Begin', cliff: 'Klip: 25% ontsluit', y2: 'Jaar 2: 50%', y3: 'Jaar 3: 75%', y4: 'Jaar 4: 100%' },
    howVestingTitle: 'Hoe Vestiging Werk',
    howVestingSteps: [
      { title: 'Klipperiode:', desc: 'Niks vestig totdat die klipdatum bereik is nie. As iemand voor die klip vertrek, kry hulle niks.' },
      { title: 'Klipontsluiting:', desc: 'Op die klipdatum ontsluit \'n gedeelte onmiddellik (tipies 25% vir \'n 4-jaar skedule).' },
      { title: 'Lineêre Vestiging:', desc: 'Ná die klip vestig tokens deurlopend tot die einddatum.' },
      { title: 'Eis Enige Tyd:', desc: 'Begunstigdes kan hul gevestigde tokens eis wanneer hulle wil — geen sperdatums nie.' },
    ],
    revTitle: 'Herroepbaar teenoor Onherroepbaar',
    revocable: { title: '✓ Herroepbaar', desc: 'SuperAdmin kan die slot kanselleer en ongevestigde tokens na die kluis terugstuur.', bestFor: 'Beste vir: Werknemervestiging (met beëindigingsklousule), voorwaardelike toekennings, interne toewysings' },
    nonRevocable: { title: '✗ Onherroepbaar', desc: 'Kan nie gekanselleer word sodra dit geskep is nie. Tokens word aan die begunstigde gewaarborg, maak nie saak wat nie.', bestFor: 'Beste vir: Beleggerstoewysings, onherroepbare toekennings, vertrouenslose trust, adviseurtokens' },
    bulkTitle: 'Grootmaatskepping',
    bulkDesc: 'Moet jy baie slotte op een slag skep? Gebruik die grootmaat-oplaaifunksie met \'n CSV-lêer. Perfek vir spantokenverspreidings, salarisse of toekenningsprogramme.',
    bulkPrepLabel: 'Berei eenvoudig \'n sigblad voor met:',
    bulkFields: [
      'Begunstigde se beursie-adres',
      'Tokenbedrag',
      'Ontsluitdatum (vir tydslotte) of vestigingsparameters',
      'Of dit herroepbaar is',
      'Opsionele beskrywing',
    ],
    bulkNote: 'Laai die CSV op, hersien die inskrywings en skep tot 10 slotte per groep.',
  },

  tokens: {
    heading: 'Ondersteunde Tokens',
    usdcTitle: 'Inheemse USDC op Stellar',
    usdcSubtitle: 'Circle se amptelike stabiele munt — nie toegedraai nie, nie oorbrug nie',
    usdcDesc: 'Orion Safe het eersteklas-ondersteuning vir USDC. Skep kluise in dollars, stel salarisvestiging in stabiele geldeenheid op, of sluit trustfondse sonder wisselvalligheidsrisiko.',
    allTitle: 'Alle Ondersteunde Bates',
    allIntro: 'Orion Safe ondersteun **enige token op die Stellar-netwerk**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Stellar se inheemse token' },
      { emoji: '💵', name: 'USDC', desc: 'VS-Dollar stabiele munt' },
      { emoji: '💶', name: 'EURC', desc: 'Euro stabiele munt' },
      { emoji: '🪙', name: 'Enige Token', desc: 'Pasgemaakte Stellar-bates' },
    ],
    whatTitle: 'Wat Jy Met Tokens Kan Doen',
    whatItems: [
      { icon: '💸', title: 'Multi-Handtekening Oordragte', desc: 'Stuur enige token met multi-handtekening-goedkeuring' },
      { icon: '🔒', title: 'Tydsluit Enige Bate', desc: 'Sluit USDC, XLM of pasgemaakte tokens tot \'n spesifieke datum' },
      { icon: '📈', title: 'Tokenvestiging', desc: 'Skep vestigingskedules vir enige Stellar-bate' },
      { icon: '📊', title: 'Grootmaatverspreidings', desc: 'Versprei tokens na veelvuldige ontvangers via CSV' },
    ],
    testTitle: 'Kry Toetsnet-tokens',
    xlmTitle: '⭐ XLM (Toetsnet)',
    xlmSteps: [
      'Gaan na {{laboratory}}',
      'Voer jou toetsnet-beursie-adres in',
      'Klik "Fund account with Friendbot"',
      'Ontvang 10,000 toets-XLM onmiddellik!',
    ],
    usdcTestTitle: '💵 USDC (Toetsnet)',
    usdcTestSteps: [
      'Voeg USDC-trustlyn in jou beursie by (Freighter → Manage Assets → Add USDC)',
      'Gebruik \'n toetsnet-USDC-kraan of ruil XLM op die toetsnet-DEX',
    ],
  },

  architecture: {
    heading: 'Hoe Dit Werk',
    intro: '\'n Eenvoudige verduideliking van wat agter die skerms gebeur wanneer jy Orion Safe gebruik.',
    basicsTitle: 'Die Grondbeginsels',
    basicsParas: [
      'Wanneer jy \'n kluis skep, ontplooi Orion Safe \'n **slimkontrak** op die Stellar-blokketting. Hierdie slimkontrak is soos \'n programmeerbare kluiskissie wat jou bates hou.',
      'Die slimkontrak handhaaf al die reëls: wie transaksies kan voorstel, hoeveel goedkeurings benodig word, wanneer gesluite tokens vrygestel kan word, en meer. **Niemand kan hierdie reëls omseil nie** — selfs nie die Orion Safe-span nie.',
    ],
    flowTitle: 'Wat Gebeur Wanneer Jy Tokens Stuur',
    flowSteps: [
      { title: 'Jy Skep \'n Voorstel', desc: 'Spesifiseer ontvanger, bedrag en opsionele memo. Die voorstel word op die blokketting aangeteken.' },
      { title: 'Ander Ondertekenaars Keur Goed', desc: 'Elke goedkeuring word op die ketting aangeteken. Almal kan sien wie goedgekeur het.' },
      { title: 'Drempel Bereik', desc: 'Sodra genoeg ondertekenaars goedkeur (bv. 2 van 3), is die transaksie gereed om uit te voer.' },
      { title: 'Voer Uit en Bevestig', desc: 'Enigeen kan uitvoering snel. Tokens beweeg onmiddellik (~5 sekondes). Klaar!' },
    ],
    whyTitle: 'Hoekom Ons op Stellar Gebou Het',
    whyItems: [
      { icon: '⚡', title: 'Vinnig', desc: 'Transaksies bevestig in ~5 sekondes' },
      { icon: '💰', title: 'Goedkoop', desc: 'Minder as $0.0001 per transaksie' },
      { icon: '🏦', title: 'Vertrou', desc: 'Gebruik deur Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Veilig', desc: 'Beproefde netwerk sedert 2015' },
      { icon: '💵', title: 'Inheemse USDC', desc: 'Werklike stabiele munte, nie toegedraaide tokens nie' },
      { icon: '🌍', title: 'Globaal', desc: 'Werk oral met internettoegang' },
    ],
    truthTitle: 'Belangrik: Blokketting is die Bron van Waarheid',
    truthDesc: 'Jou kluis bestaan op die Stellar-blokketting, nie op ons bedieners nie. Selfs as ons webwerf vanlyn sou gaan, sou jou kluis en fondse veilig en toeganklik bly deur ander Stellar-gereedskap. Ons verskaf bloot \'n gebruikersvriendelike koppelvlak om met jou op-ketting-kluis te kommunikeer.',
  },

  security: {
    heading: 'Sekuriteit',
    intro: 'Hoe Orion Safe jou bates veilig hou.',
    principlesTitle: 'Kern-Sekuriteitsbeginsels',
    principles: [
      { title: 'Op-Ketting Afdwinging', desc: 'Alle reëls word deur die slimkontrak op die blokketting afgedwing. Die webwerf is net \'n gebruikerskoppelvlak — die blokketting is die gesag.' },
      { title: 'Geen Agterdeure', desc: 'Niemand — selfs nie die Orion Safe-span nie — kan toegang tot jou kluis kry of jou fondse beweeg sonder behoorlike handtekeninge nie.' },
      { title: 'Multi-Handtekening as Verstek', desc: 'Selfs al word een sleutel gekompromitteer, kan aanvallers nie fondse beweeg sonder om jou goedkeuringsdrempel te bereik nie.' },
    ],
    threatsTitle: 'Hoe Ons Teen Bedreigings Beskerm',
    threats: [
      { threat: 'Gekompromitteerde ondertekenaarsleutel', mitigation: 'Multi-handtekening-drempel voorkom enkelsleutel-aanvalle. Ander ondertekenaars kan gekompromitteerde sleutel verwyder.' },
      { threat: 'Kwaadwillige voorstel', mitigation: 'Vereis veelvuldige goedkeurings. Ander ondertekenaars kan slegte voorstelle verwerp.' },
      { threat: 'Verlore sleutels', mitigation: 'Solank oorblywende ondertekenaars die drempel bereik, bly die kluis toeganklik.' },
      { threat: 'Webwerf gaan af', mitigation: 'Jou kluis bestaan op die blokketting. Kry toegang daartoe deur ander Stellar-gereedskap.' },
      { threat: 'Databasis-skending', mitigation: 'Ons databasis is net \'n kas vir vinniger laai. Blokketting is die bron van waarheid.' },
    ],
    bestTitle: 'Beste Sekuriteitspraktyke',
    doTitle: '✓ Doen',
    dos: [
      'Gebruik hardewarebeursies (soos Ledger) vir ondertekenaarsleutels',
      'Hou drempel op 2 of hoër (nooit enkele ondertekenaar nie)',
      'Hersien gereeld jou ondertekenaarslys',
      'Gebruik aparte kluise vir verskillende doeleindes',
      'Toets eers met klein bedrae',
      'Rugsteun jou herstelfrases veilig',
    ],
    dontTitle: '✗ Moenie',
    donts: [
      'Deel private sleutels oor e-pos of klets',
      'Gebruik dieselfde sleutel vir veelvuldige kritieke kluise',
      'Ignoreer hangende voorstelle vir te lank',
      'Stel drempel gelyk aan totale ondertekenaars (geen oortolligheid)',
      'Stoor herstelfrases digitaal onversleuteld',
      'Gee SuperAdmin-toegang aan mense wat jy nie ten volle vertrou nie',
    ],
    statusTitle: 'Sekuriteitstatus',
    statuses: [
      { color: 'green', text: 'Gebou op beproefde Stellar-netwerk (sedert 2015)' },
      { color: 'green', text: 'OpenZeppelin Smart Account-raamwerk-integrasie' },
      { color: 'yellow', text: 'Professionele sekuriteitsoudit beplan voor hoofnet (K4 2026)' },
      { color: 'gray', text: 'Foutbeloningsprogram kom ná hoofnet-bekendstelling' },
    ],
  },

  roadmap: {
    heading: 'Padkaart',
    liveTitle: 'Tans Lewendig op Toetsnet',
    liveFeatures: ['Multi-handtekening-kluise', 'Rolgebaseerde toegang', 'Tydslotte', 'Vestigingskedules', 'Grootmaat-CSV-invoer', 'Openbare kykskakels', 'Eisportaal', 'Multi-beursie-ondersteuning'],
    phases: [
      { color: 'purple', title: 'Fase 1: Produksiegereedheid', target: 'Teiken: Julie 2026', items: ['Hoofnet-ontplooiingsvoorbereiding', 'Sekuriteitsverharding en -toetsing', 'Werkverrigtingoptimering', 'Verbeterde fouthantering'] },
      { color: 'blue', title: 'Fase 2: Gevorderde Kenmerke', target: 'Teiken: September 2026', items: ['Besteperke (daaglikse/weeklikse/maandelikse beperkings)', 'Verbeterde vestigingsjablone', 'Gevorderde voorstelopsies', 'Verbeterde selfoonervaring'] },
      { color: 'cyan', title: 'Fase 3: Hoofnet-bekendstelling', target: 'Teiken: November 2026', items: ['Professionele sekuriteitsoudit', 'Stellar DEX-integrasie (in-kluis handel)', 'Ontwikkelaar-SDK', 'Omvattende gebruikersgidse en tutoriale', '🚀 **Hoofnet-ontplooiing**'] },
    ],
    futureTitle: 'Toekomsvisie (2027+)',
    future: [
      { title: 'DeFi-integrasie', desc: 'Opbrengsstrategieë, leenprotokolle, likiditeitsvoorsiening' },
      { title: 'Ondernemingsuite', desc: 'Wit-etiket-opsies, SSO, nakomingsverslagdoening' },
      { title: 'Outomatisering', desc: 'Geskeduleerde herhalende betalings, slim voorwaardes' },
      { title: 'Integrasies', desc: 'API, webhake, rekeningkundige sagteware-verbindings' },
    ],
    followTitle: 'Volg Ons Vordering',
    followDesc: 'Ons bou in die openbaar. Hou ons GitHub-bewaarplek dop vir opdaterings, of kom terug hierheen vir die jongste nuus.',
  },

  faq: {
    heading: 'Algemene Vrae',
    items: [
      { q: 'Is Orion Safe gratis om te gebruik?', a: 'Ja! Die platform is gratis. Jy betaal slegs standaard Stellar-netwerkfooie (minder as $0.0001 per transaksie) plus \'n klein eenmalige deposito wanneer jy \'n kluis skep.' },
      { q: 'Wat gebeur as ek my private sleutel verloor?', a: 'Solank die oorblywende ondertekenaars die goedkeuringsdrempel bereik, bly die kluis ten volle toeganklik. Byvoorbeeld, in \'n 2-van-3-kluis, as een sleutel verlore is, kan die ander 2 ondertekenaars steeds die kluis bedryf en selfs \'n vervangingsondertekenaar byvoeg.' },
      { q: 'Kan die Orion Safe-span toegang tot my fondse kry?', a: 'Nee. Jou kluis is \'n slimkontrak op die Stellar-blokketting. Slegs ondertekenaars wat jy byvoeg, kan transaksies magtig. Ons het geen spesiale toegang, agterdeure of admin-sleutels tot jou kluis nie.' },
      { q: 'Watter tokens kan ek stoor?', a: 'Enige Stellar-bate: XLM (inheems), USDC, EURC en duisende ander tokens wat op die Stellar-netwerk uitgereik is.' },
      { q: 'Hoe vinnig is transaksies?', a: 'Ongeveer 5 sekondes ná uitvoering. Die goedkeuringsproses hang af van hoe vinnig jou ondertekenaars reageer.' },
      { q: 'Kan ek \'n tydslot of vestigingskedule kanselleer?', a: 'Slegs as dit as "herroepbaar" geskep is. Onherroepbare slotte kan nie gekanselleer word sodra dit geskep is nie — die tokens word aan die begunstigde gewaarborg.' },
      { q: 'Is daar \'n selfoontoepassing?', a: 'Die kontroleskerm is ten volle reageerbaar en werk uitstekend op selfoonblaaiers. Gebruik dit met selfoonbeursies soos Lobstr of verbind via WalletConnect.' },
      { q: 'Wat as die webwerf afgaan?', a: 'Jou kluis bestaan op die Stellar-blokketting, nie op ons bedieners nie. Jy kan daarmee kommunikeer deur die Stellar Laboratory of enige versoenbare gereedskap te gebruik, selfs al is ons webwerf onbeskikbaar.' },
      { q: 'Hoe eis begunstigdes hul tokens?', a: 'Deel \'n eisskakel met hulle (gevind in Instellings → Deel). Hulle verbind hul eie beursie en eis direk — geen kluistoegang nodig nie.' },
      { q: 'Is daar \'n perk op die aantal ondertekenaars?', a: 'Ondersteun tans tot 10 ondertekenaars per kluis. Benodig jy meer? Kontak ons vir ondernemingsoplossings.' },
      { q: 'Wat is die verskil tussen toetsnet en hoofnet?', a: 'Toetsnet gebruik vals tokens vir toetsing — geen werklike waarde nie. Hoofnet gebruik werklike tokens en werklike geld. Ons is tans op die toetsnet, met hoofnet-bekendstelling beplan vir K4 2026.' },
      { q: 'Hoe kry ek hulp as iets verkeerd loop?', a: 'Gaan eers hierdie dokumentasie na. As jy steeds hulp nodig het, maak \'n kwessie op ons GitHub-bewaarplek oop of kontak ons deur ons kontakkanale.' },
    ],
  },

  common: {
    locked: '🔒 Gesluit',
    claimable: '✓ Eisbaar',
    today: 'Vandag',
    unlockDate: '⏰ Ontsluitdatum',
    claimed: 'Geëis',
    viewOnGithub: 'Bekyk op GitHub',
  },
};
