import { DocsContent } from './types';

export const docsCs: DocsContent = {
  sidebarTitle: 'Dokumentace',
  sections: [
    { id: 'overview', title: 'Přehled', description: 'Co je Orion Safe?' },
    { id: 'quickstart', title: 'Rychlý Start', description: 'Průvodce nastavením za 5 minut' },
    { id: 'features', title: 'Hlavní Funkce', description: 'Co můžete dělat' },
    { id: 'roles', title: 'Role a Oprávnění', description: 'Kdo co může dělat' },
    { id: 'locks', title: 'Časové Zámky a Vesting', description: 'Naplánujte uvolňování tokenů' },
    { id: 'tokens', title: 'Podporované Tokeny', description: 'USDC, XLM a další' },
    { id: 'architecture', title: 'Jak To Funguje', description: 'Pod kapotou' },
    { id: 'security', title: 'Bezpečnost', description: 'Jak vás chráníme' },
    { id: 'faq', title: 'FAQ', description: 'Časté otázky' },
    { id: 'roadmap', title: 'Plán Vývoje', description: 'Co bude dál' },
  ],

  overview: {
    heading: 'Vítejte v Orion Safe',
    intro:
      'Orion Safe je **vícepodpisová pokladniční platforma** postavená na Stellaru. ' +
      'Představte si ji jako sdílený bankovní účet pro váš tým, DAO nebo organizaci — ale se superschopnostmi.',
    whyTitle: 'Proč používat Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Žádný Jediný Bod Selhání', desc: 'Vyžaduje se více schválení — i když je jeden klíč kompromitován, prostředky zůstávají v bezpečí' },
      { emoji: '⚡', title: 'Bleskově Rychlé a Levné', desc: 'Transakce za ~5 sekund, méně než 0,0001 $ za transakci' },
      { emoji: '⏰', title: 'Časově Založené Kontroly', desc: 'Zamkněte tokeny do určitého data nebo je uvolňujte postupně v čase' },
      { emoji: '🌍', title: 'Plná Transparentnost', desc: 'Každá akce zaznamenána on-chain — sdílejte odkazy pouze ke čtení s kýmkoli' },
    ],
    perfectForTitle: 'Ideální Pro',
    perfectFor: [
      { icon: '🏛️', title: 'DAO a Pokladny', desc: 'Spravujte komunitní fondy s transparentním vícepodpisovým řízením' },
      { icon: '👥', title: 'Týmy a Startupy', desc: 'Zabezpečte firemní pokladnu přístupem založeným na rolích' },
      { icon: '💼', title: 'Vesting Zaměstnanců', desc: '4letý vesting tokenů s ročním cliffem, plně automatizovaný' },
      { icon: '🤝', title: 'Escrow Služby', desc: 'Vzájemná dohoda 2-z-2 pro bezpečné transakce' },
      { icon: '🎁', title: 'Granty a Výplaty', desc: 'Hromadné distribuce tokenů s naplánovaným uvolňováním' },
      { icon: '📊', title: 'Investiční Fondy', desc: 'Schválení výborem pro správu fondu' },
    ],
    liveTitle: 'V Provozu na Testnetu Stellar',
    liveDesc:
      'Orion Safe je v současnosti v provozu na testnetu Stellar. Vyzkoušejte ho hned s testovacími tokeny! ' +
      'Spuštění na mainnetu plánováno na Q4 2026 po bezpečnostním auditu.',
  },

  quickstart: {
    heading: 'Průvodce Rychlým Startem',
    subtitle: 'Zprovozněte svůj první trezor za méně než 5 minut.',
    step1Title: 'Připojte Svou Peněženku',
    step1Intro: 'Klikněte na **„Připojit Peněženku"** v pravém horním rohu a vyberte svou preferovanou peněženku:',
    wallets: [
      { name: 'Freighter', note: 'Doporučeno' },
      { name: 'Lobstr', note: 'Vhodné pro mobil' },
      { name: 'xBull', note: 'Pokročilí uživatelé' },
      { name: 'Albedo', note: 'Webová' },
    ],
    noWalletTitle: 'Nemáte peněženku?',
    noWalletDesc: 'Nainstalujte {{freighter}} — je to bezplatné rozšíření prohlížeče, jehož nastavení zabere 2 minuty.',
    step2Title: 'Vytvořte Svůj Trezor',
    step2Items: [
      'Klikněte na **„Vytvořit Trezor"**',
      'Pojmenujte svůj trezor (např. „Týmová Pokladna")',
      'Přidejte adresy peněženek podepisujících (lidé, kteří mohou schvalovat transakce)',
      'Nastavte svůj **práh** — kolik schválení je potřeba',
    ],
    exampleLabel: 'Příklad: Vícepodpisový 2-z-3',
    approvedLabel: '2/3 = Schváleno!',
    step3Title: 'Naplňte Svůj Trezor',
    step3Intro: 'Váš trezor má vlastní adresu. Posílejte na ni tokeny jako na jakoukoli peněženku Stellar:',
    step3Items: [
      'Zkopírujte adresu svého trezoru z panelu',
      'Pošlete XLM, USDC nebo jakýkoli token Stellar na tuto adresu',
      'Prostředky se objeví do ~5 sekund',
    ],
    proTipTitle: 'Profi Tip',
    proTipDesc: 'Pro testnet získejte bezplatné testovací XLM z {{friendbot}}.',
    step4Title: 'Proveďte Svou První Transakci',
    step4Steps: [
      { title: 'Vytvořit Návrh', desc: 'Přejděte na Transakce → Nový → Zadejte podrobnosti → Odeslat' },
      { title: 'Shromáždit Schválení', desc: 'Ostatní podepisující zkontrolují a kliknou na „Schválit"' },
      { title: 'Provést', desc: 'Jakmile je dosaženo prahu, kdokoli může kliknout na „Provést"' },
    ],
    doneTitle: '🎉 A je to!',
    doneDesc:
      'Nyní máte bezpečný vícepodpisový trezor. Prozkoumejte boční panel a objevte časové zámky, ' +
      'plány vestingu a pokročilejší funkce.',
  },

  features: {
    heading: 'Hlavní Funkce',
    multiSig: {
      title: 'Vícepodpisová Bezpečnost',
      desc: 'Vyžadujte, aby transakce schvalovalo více lidí. Práh si vybíráte vy — ať už je to 2-z-3 pro malý tým nebo 5-z-9 pro velkou DAO.',
      configs: ['2-z-3', '3-z-5', '4-z-7', '5-z-9'],
    },
    proposal: {
      title: 'Pracovní Postup Založený na Návrzích',
      desc: 'Všechny transakce procházejí transparentním procesem návrhu. Žádná překvapení, plná odpovědnost.',
      steps: [
        { title: 'Navrhnout', sub: 'Kterýkoli podepisující' },
        { title: 'Schválit', sub: 'Dosáhnout prahu' },
        { title: 'Provést', sub: 'Kdokoli' },
      ],
    },
    txTypes: {
      title: 'Typy Transakcí',
      items: [
        { icon: '💸', title: 'Převod', desc: 'Pošlete tokeny ihned po schválení. Jednoduché, přímé platby.' },
        { icon: '🔒', title: 'Časový Zámek', desc: 'Zamkněte tokeny do určitého data. Ideální pro escrow nebo naplánovaná uvolnění.' },
        { icon: '📈', title: 'Vesting', desc: 'Postupné uvolňování v čase s volitelným cliffem. Ideální pro zaměstnanecké tokeny.' },
      ],
    },
    dashboard: {
      title: 'Navigace Panelu',
      views: [
        { name: 'Panel', desc: 'Přehled a statistiky' },
        { name: 'Aktiva', desc: 'Zůstatky tokenů' },
        { name: 'Transakce', desc: 'Návrhy a historie' },
        { name: 'Členové', desc: 'Podepisující a role' },
        { name: 'Časové Zámky', desc: 'Naplánovaná uvolnění' },
        { name: 'Vesting', desc: 'Vesting tokenů' },
        { name: 'Kontakty', desc: 'Adresář' },
        { name: 'Nastavení', desc: 'Konfigurace' },
      ],
    },
    publicAccess: {
      title: 'Veřejný Přístup a Sdílení',
      cards: [
        { title: '🔗 Odkaz na Veřejné Zobrazení', desc: 'Sdílejte zobrazení pouze ke čtení s investory, auditory nebo veřejností. Vidí zůstatky a aktivitu, ale nemohou provádět žádné akce.' },
        { title: '🎁 Odkaz pro Vyzvednutí', desc: 'Příjemci si mohou vyzvednout své zamčené nebo přidělené tokeny přímo pomocí vlastní peněženky — bez nutnosti přístupu k trezoru.' },
      ],
    },
  },

  roles: {
    heading: 'Role a Oprávnění',
    intro: 'Orion Safe používá systém založený na rolích k řízení toho, kdo co může dělat. To poskytuje flexibilitu při zachování bezpečnosti.',
    cards: [
      { name: 'SuperAdmin', badge: 'Plná Kontrola', desc: 'Úplná kontrola nad trezorem. SuperAdmini mohou dělat vše, včetně akcí ovlivňujících strukturu a bezpečnost trezoru.', canLabel: 'Může:', can: 'Přidávat/odebírat podepisující, měnit práh schválení, zrušit jakýkoli odvolatelný zámek, aktualizovat nastavení trezoru, plus vše, co mohou Admini a Executoři.' },
      { name: 'Admin', badge: 'Provoz', desc: 'Správce každodenního provozu. Admini zajišťují většinu pokladničních činností, ale nemohou měnit bezpečnostní nastavení trezoru.', canLabel: 'Může:', can: 'Vytvářet návrhy, schvalovat transakce, provádět schválené transakce, vytvářet časové zámky a plány vestingu, spravovat kontakty.' },
      { name: 'Executor', badge: 'Schválit a Provést', desc: 'Schvalovací pravomoc. Executoři mohou hlasovat o návrzích a provádět schválené transakce, ale nemohou iniciovat nové.', canLabel: 'Může:', can: 'Schvalovat nebo zamítat návrhy, provádět transakce, které dosáhly prahu.' },
      { name: 'Viewer', badge: 'Pouze ke Čtení', desc: 'Přístup pozorovatele. Viewerové vidí vše, ale nemohou provádět žádné akce. Ideální pro auditory nebo zainteresované strany.', canLabel: 'Může:', can: 'Zobrazit zůstatky trezoru, historii transakcí, návrhy, zámky a veškerou aktivitu.' },
    ],
    matrixTitle: 'Přehled Oprávnění',
    matrixHeaders: { action: 'Akce', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Zobrazit trezor a zůstatky', super: true, admin: true, exec: true, view: true },
      { action: 'Vytvářet návrhy', super: true, admin: true, exec: false, view: false },
      { action: 'Schvalovat návrhy', super: true, admin: true, exec: true, view: false },
      { action: 'Provádět transakce', super: true, admin: true, exec: true, view: false },
      { action: 'Vytvářet časové zámky / vesting', super: true, admin: true, exec: false, view: false },
      { action: 'Rušit odvolatelné zámky', super: true, admin: false, exec: false, view: false },
      { action: 'Přidávat/odebírat podepisující', super: true, admin: false, exec: false, view: false },
      { action: 'Měnit práh', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Osvědčený Postup: Přidělování Rolí',
    bestPractice: [
      'Omezte SuperAdmina na 1-2 důvěryhodné osoby (zakladatelé, vedení)',
      'Používejte Admina pro členy finančního týmu, kteří řídí každodenní provoz',
      'Používejte Executora pro členy správní rady, kteří pouze schvalují, neiniciují',
      'Používejte Viewera pro zainteresované strany, auditory nebo veřejnou transparentnost',
    ],
  },

  locks: {
    heading: 'Časové Zámky a Vesting',
    intro: 'Řiďte, kdy se tokeny stanou dostupnými. Ať už potřebujete escrow, naplánované platby nebo vesting zaměstnaneckých tokenů — máme vás pokryté.',
    timeLockTitle: 'Časové Zámky',
    timeLockDesc: 'Zamkněte tokeny do určitého data. Příjemce si může vyzvednout **celou částku** až poté, co uplyne čas odemčení. Před tímto datem jsou tokeny zcela nepřístupné.',
    timeLockExampleLabel: 'Příklad: Escrow Vklad',
    timeLockExampleAmount: '10 000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Escrow', desc: 'Zadržte prostředky, dokud nejsou splněny podmínky' },
      { icon: '🎯', title: 'Platby za Milníky', desc: 'Uvolněte po dokončení výstupu' },
      { icon: '🏦', title: 'Spořicí Cíle', desc: 'Zabraňte impulzivním výběrům' },
    ],
    vestingTitle: 'Plány Vestingu',
    vestingDesc: 'Uvolňujte tokeny **postupně v čase** s volitelným cliff obdobím. Je to oborový standard pro odměňování zaměstnanců a alokace investorům.',
    vestingExampleLabel: 'Příklad: 4letý Zaměstnanecký Vesting s Ročním Cliffem',
    vestingExampleAmount: '100 000 tokenů',
    vestingBarCliff: 'Cliff (1 r.)',
    vestingBarLinear: 'Lineární Vesting → 100 %',
    vestingTimeline: { start: 'Začátek', cliff: 'Cliff: odemkne se 25 %', y2: 'Rok 2: 50 %', y3: 'Rok 3: 75 %', y4: 'Rok 4: 100 %' },
    howVestingTitle: 'Jak Vesting Funguje',
    howVestingSteps: [
      { title: 'Cliff Období:', desc: 'Nic se nepřiděluje až do data cliffu. Pokud někdo odejde před cliffem, nedostane nic.' },
      { title: 'Odemčení Cliffu:', desc: 'V den cliffu se část okamžitě odemkne (obvykle 25 % pro 4letý plán).' },
      { title: 'Lineární Vesting:', desc: 'Po cliffu se tokeny přidělují průběžně až do koncového data.' },
      { title: 'Vyzvednutí Kdykoli:', desc: 'Příjemci si mohou vyzvednout přidělené tokeny, kdykoli chtějí — bez termínů.' },
    ],
    revTitle: 'Odvolatelný vs. Neodvolatelný',
    revocable: { title: '✓ Odvolatelný', desc: 'SuperAdmin může zámek zrušit a vrátit nepřidělené tokeny do trezoru.', bestFor: 'Nejlepší pro: Vesting zaměstnanců (s doložkou o ukončení), podmíněné granty, interní alokace' },
    nonRevocable: { title: '✗ Neodvolatelný', desc: 'Po vytvoření nelze zrušit. Tokeny jsou příjemci zaručeny za všech okolností.', bestFor: 'Nejlepší pro: Alokace investorům, neodvolatelné granty, bezdůvěrový escrow, tokeny pro poradce' },
    bulkTitle: 'Hromadné Vytváření',
    bulkDesc: 'Potřebujete vytvořit mnoho zámků najednou? Použijte funkci hromadného nahrávání se souborem CSV. Ideální pro týmové distribuce tokenů, výplaty nebo grantové programy.',
    bulkPrepLabel: 'Jednoduše připravte tabulku s:',
    bulkFields: [
      'Adresou peněženky příjemce',
      'Množstvím tokenů',
      'Datem odemčení (pro časové zámky) nebo parametry vestingu',
      'Zda je odvolatelný',
      'Volitelným popisem',
    ],
    bulkNote: 'Nahrajte CSV, zkontrolujte záznamy a vytvořte až 10 zámků na dávku.',
  },

  tokens: {
    heading: 'Podporované Tokeny',
    usdcTitle: 'Nativní USDC na Stellaru',
    usdcSubtitle: 'Oficiální stablecoin od Circle — nezabalený, nepřemostěný',
    usdcDesc: 'Orion Safe nabízí prvotřídní podporu pro USDC. Vytvářejte trezory denominované v dolarech, nastavte vesting mezd ve stabilní měně nebo zamkněte escrow prostředky bez rizika volatility.',
    allTitle: 'Všechna Podporovaná Aktiva',
    allIntro: 'Orion Safe podporuje **jakýkoli token v síti Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Nativní token Stellaru' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin amerického dolaru' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin eura' },
      { emoji: '🪙', name: 'Jakýkoli Token', desc: 'Vlastní aktiva Stellaru' },
    ],
    whatTitle: 'Co Můžete s Tokeny Dělat',
    whatItems: [
      { icon: '💸', title: 'Vícepodpisové Převody', desc: 'Posílejte jakýkoli token s vícepodpisovým schválením' },
      { icon: '🔒', title: 'Zamknout Jakékoli Aktivum', desc: 'Zamkněte USDC, XLM nebo vlastní tokeny do určitého data' },
      { icon: '📈', title: 'Vesting Tokenů', desc: 'Vytvářejte plány vestingu pro jakékoli aktivum Stellaru' },
      { icon: '📊', title: 'Hromadné Distribuce', desc: 'Distribuujte tokeny více příjemcům pomocí CSV' },
    ],
    testTitle: 'Získání Tokenů Testnet',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Přejděte na {{laboratory}}',
      'Zadejte adresu své peněženky testnet',
      'Klikněte na „Fund account with Friendbot"',
      'Okamžitě obdržíte 10 000 testovacích XLM!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Přidejte trustline USDC ve své peněžence (Freighter → Manage Assets → Add USDC)',
      'Použijte testnet USDC faucet nebo vyměňte XLM na testnet DEXu',
    ],
  },

  architecture: {
    heading: 'Jak To Funguje',
    intro: 'Jednoduché vysvětlení toho, co se děje v zákulisí, když používáte Orion Safe.',
    basicsTitle: 'Základy',
    basicsParas: [
      'Když vytvoříte trezor, Orion Safe nasadí **chytrý kontrakt** na blockchainu Stellar. Tento chytrý kontrakt je jako programovatelná bezpečnostní schránka, která uchovává vaše aktiva.',
      'Chytrý kontrakt vynucuje všechna pravidla: kdo může navrhovat transakce, kolik schválení je potřeba, kdy lze uvolnit zamčené tokeny a další. **Nikdo tato pravidla nemůže obejít** — ani tým Orion Safe.',
    ],
    flowTitle: 'Co Se Stane, Když Pošlete Tokeny',
    flowSteps: [
      { title: 'Vytvoříte Návrh', desc: 'Zadejte příjemce, částku a volitelné memo. Návrh se zaznamená na blockchain.' },
      { title: 'Ostatní Podepisující Schválí', desc: 'Každé schválení se zaznamená on-chain. Každý vidí, kdo schválil.' },
      { title: 'Dosažen Práh', desc: 'Jakmile dostatek podepisujících schválí (např. 2 ze 3), transakce je připravena k provedení.' },
      { title: 'Provést a Potvrdit', desc: 'Kdokoli může spustit provedení. Tokeny se přesunou okamžitě (~5 sekund). Hotovo!' },
    ],
    whyTitle: 'Proč Jsme Postavili na Stellaru',
    whyItems: [
      { icon: '⚡', title: 'Rychlé', desc: 'Transakce se potvrdí za ~5 sekund' },
      { icon: '💰', title: 'Levné', desc: 'Méně než 0,0001 $ za transakci' },
      { icon: '🏦', title: 'Důvěryhodné', desc: 'Používáno společnostmi Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Bezpečné', desc: 'Praxí ověřená síť od roku 2015' },
      { icon: '💵', title: 'Nativní USDC', desc: 'Skutečné stablecoiny, ne zabalené tokeny' },
      { icon: '🌍', title: 'Globální', desc: 'Funguje kdekoli s přístupem k internetu' },
    ],
    truthTitle: 'Důležité: Blockchain Je Zdrojem Pravdy',
    truthDesc: 'Váš trezor existuje na blockchainu Stellar, ne na našich serverech. I kdyby naše webové stránky přestaly fungovat, váš trezor a prostředky by zůstaly v bezpečí a přístupné prostřednictvím jiných nástrojů Stellar. My jednoduše poskytujeme uživatelsky přívětivé rozhraní pro interakci s vaším on-chain trezorem.',
  },

  security: {
    heading: 'Bezpečnost',
    intro: 'Jak Orion Safe udržuje vaše aktiva v bezpečí.',
    principlesTitle: 'Základní Bezpečnostní Principy',
    principles: [
      { title: 'Vynucování On-Chain', desc: 'Všechna pravidla vynucuje chytrý kontrakt na blockchainu. Webové stránky jsou jen uživatelské rozhraní — blockchain je autorita.' },
      { title: 'Žádná Zadní Vrátka', desc: 'Nikdo — ani tým Orion Safe — nemůže získat přístup k vašemu trezoru ani přesunout vaše prostředky bez správných podpisů.' },
      { title: 'Vícepodpisové ve Výchozím Nastavení', desc: 'I když je jeden klíč kompromitován, útočníci nemohou přesunout prostředky bez dosažení vašeho prahu schválení.' },
    ],
    threatsTitle: 'Jak Chráníme Před Hrozbami',
    threats: [
      { threat: 'Kompromitovaný klíč podepisujícího', mitigation: 'Vícepodpisový práh zabraňuje útokům na jediný klíč. Ostatní podepisující mohou kompromitovaný klíč odebrat.' },
      { threat: 'Škodlivý návrh', mitigation: 'Vyžaduje více schválení. Ostatní podepisující mohou špatné návrhy zamítnout.' },
      { threat: 'Ztracené klíče', mitigation: 'Dokud zbývající podepisující dosahují prahu, trezor zůstává přístupný.' },
      { threat: 'Web přestane fungovat', mitigation: 'Váš trezor existuje na blockchainu. Přistupte k němu pomocí jiných nástrojů Stellar.' },
      { threat: 'Únik databáze', mitigation: 'Naše databáze je jen mezipaměť pro rychlejší načítání. Blockchain je zdrojem pravdy.' },
    ],
    bestTitle: 'Osvědčené Bezpečnostní Postupy',
    doTitle: '✓ Dělejte',
    dos: [
      'Používejte hardwarové peněženky (jako Ledger) pro klíče podepisujících',
      'Udržujte práh na 2 nebo vyšším (nikdy jediný podepisující)',
      'Pravidelně kontrolujte svůj seznam podepisujících',
      'Používejte samostatné trezory pro různé účely',
      'Nejprve testujte s malými částkami',
      'Bezpečně zálohujte své obnovovací fráze',
    ],
    dontTitle: '✗ Nedělejte',
    donts: [
      'Sdílet soukromé klíče přes e-mail nebo chat',
      'Používat stejný klíč pro více kritických trezorů',
      'Ignorovat čekající návrhy příliš dlouho',
      'Nastavovat práh rovný celkovému počtu podepisujících (žádná redundance)',
      'Ukládat obnovovací fráze digitálně nešifrovaně',
      'Udělovat přístup SuperAdmina lidem, kterým plně nedůvěřujete',
    ],
    statusTitle: 'Stav Bezpečnosti',
    statuses: [
      { color: 'green', text: 'Postaveno na praxí ověřené síti Stellar (od roku 2015)' },
      { color: 'green', text: 'Integrace frameworku Smart Account od OpenZeppelin' },
      { color: 'yellow', text: 'Profesionální bezpečnostní audit plánován před mainnetem (Q4 2026)' },
      { color: 'gray', text: 'Program odměn za chyby přichází po spuštění mainnetu' },
    ],
  },

  roadmap: {
    heading: 'Plán Vývoje',
    liveTitle: 'V Současnosti v Provozu na Testnetu',
    liveFeatures: ['Vícepodpisové trezory', 'Přístup založený na rolích', 'Časové zámky', 'Plány vestingu', 'Hromadný import CSV', 'Odkazy na veřejné zobrazení', 'Portál pro vyzvednutí', 'Podpora více peněženek'],
    phases: [
      { color: 'purple', title: 'Fáze 1: Připravenost pro Produkci', target: 'Cíl: Červenec 2026', items: ['Příprava nasazení na mainnet', 'Posílení bezpečnosti a testování', 'Optimalizace výkonu', 'Vylepšené zpracování chyb'] },
      { color: 'blue', title: 'Fáze 2: Pokročilé Funkce', target: 'Cíl: Září 2026', items: ['Limity útrat (denní/týdenní/měsíční stropy)', 'Vylepšené šablony vestingu', 'Pokročilé možnosti návrhů', 'Vylepšený mobilní zážitek'] },
      { color: 'cyan', title: 'Fáze 3: Spuštění Mainnetu', target: 'Cíl: Listopad 2026', items: ['Profesionální bezpečnostní audit', 'Integrace s DEXem Stellar (obchodování v trezoru)', 'SDK pro vývojáře', 'Komplexní uživatelské příručky a návody', '🚀 **Nasazení na mainnet**'] },
    ],
    futureTitle: 'Vize Budoucnosti (2027+)',
    future: [
      { title: 'Integrace DeFi', desc: 'Výnosové strategie, půjčovací protokoly, poskytování likvidity' },
      { title: 'Podniková Sada', desc: 'Možnosti white-label, SSO, reportování souladu' },
      { title: 'Automatizace', desc: 'Naplánované opakující se platby, chytré podmínky' },
      { title: 'Integrace', desc: 'API, webhooky, propojení s účetním softwarem' },
    ],
    followTitle: 'Sledujte Náš Pokrok',
    followDesc: 'Stavíme veřejně. Sledujte naše úložiště GitHub pro aktualizace nebo se sem vraťte pro nejnovější zprávy.',
  },

  faq: {
    heading: 'Často Kladené Otázky',
    items: [
      { q: 'Je Orion Safe zdarma?', a: 'Ano! Platforma je zdarma. Platíte pouze standardní poplatky sítě Stellar (méně než 0,0001 $ za transakci) plus malý jednorázový vklad při vytváření trezoru.' },
      { q: 'Co se stane, když ztratím svůj soukromý klíč?', a: 'Dokud zbývající podepisující dosahují prahu schválení, trezor zůstává plně přístupný. Například v trezoru 2-z-3, pokud je jeden klíč ztracen, zbylí 2 podepisující mohou trezor stále ovládat a dokonce přidat náhradního podepisujícího.' },
      { q: 'Může tým Orion Safe přistupovat k mým prostředkům?', a: 'Ne. Váš trezor je chytrý kontrakt na blockchainu Stellar. Transakce mohou autorizovat pouze podepisující, které přidáte. Nemáme žádný zvláštní přístup, zadní vrátka ani administrátorské klíče k vašemu trezoru.' },
      { q: 'Jaké tokeny mohu uchovávat?', a: 'Jakékoli aktivum Stellar: XLM (nativní), USDC, EURC a tisíce dalších tokenů vydaných v síti Stellar.' },
      { q: 'Jak rychlé jsou transakce?', a: 'Přibližně 5 sekund po provedení. Proces schvalování závisí na tom, jak rychle reagují vaši podepisující.' },
      { q: 'Mohu zrušit časový zámek nebo plán vestingu?', a: 'Pouze pokud byl vytvořen jako „odvolatelný". Neodvolatelné zámky nelze po vytvoření zrušit — tokeny jsou příjemci zaručeny.' },
      { q: 'Existuje mobilní aplikace?', a: 'Panel je plně responzivní a skvěle funguje v mobilních prohlížečích. Používejte ho s mobilními peněženkami jako Lobstr nebo se připojte přes WalletConnect.' },
      { q: 'Co když web přestane fungovat?', a: 'Váš trezor existuje na blockchainu Stellar, ne na našich serverech. Můžete s ním interagovat pomocí Stellar Laboratory nebo jakéhokoli kompatibilního nástroje, i když naše stránky nejsou dostupné.' },
      { q: 'Jak si příjemci vyzvednou své tokeny?', a: 'Sdílejte s nimi odkaz pro vyzvednutí (najdete v Nastavení → Sdílet). Připojí svou vlastní peněženku a vyzvednou přímo — bez nutnosti přístupu k trezoru.' },
      { q: 'Existuje limit na počet podepisujících?', a: 'V současnosti podporuje až 10 podepisujících na trezor. Potřebujete více? Kontaktujte nás ohledně podnikových řešení.' },
      { q: 'Jaký je rozdíl mezi testnetem a mainnetem?', a: 'Testnet používá falešné tokeny k testování — bez skutečné hodnoty. Mainnet používá skutečné tokeny a skutečné peníze. V současnosti jsme na testnetu, spuštění mainnetu plánováno na Q4 2026.' },
      { q: 'Jak získám pomoc, když se něco pokazí?', a: 'Nejprve si projděte tuto dokumentaci. Pokud stále potřebujete pomoc, otevřete issue v našem úložišti GitHub nebo nás kontaktujte přes naše kanály.' },
    ],
  },

  common: {
    locked: '🔒 Zamčeno',
    claimable: '✓ K Vyzvednutí',
    today: 'Dnes',
    unlockDate: '⏰ Datum Odemčení',
    claimed: 'Vyzvednuto',
    viewOnGithub: 'Zobrazit na GitHubu',
  },
};
