import { DocsContent } from './types';

export const docsDe: DocsContent = {
  sidebarTitle: 'Dokumentation',
  sections: [
    { id: 'overview', title: 'Überblick', description: 'Was ist Orion Safe?' },
    { id: 'quickstart', title: 'Schnellstart', description: '5-Minuten-Einrichtungsanleitung' },
    { id: 'features', title: 'Kernfunktionen', description: 'Was du tun kannst' },
    { id: 'roles', title: 'Rollen & Berechtigungen', description: 'Wer was darf' },
    { id: 'locks', title: 'Zeitsperren & Vesting', description: 'Token-Freigaben planen' },
    { id: 'tokens', title: 'Unterstützte Token', description: 'USDC, XLM & mehr' },
    { id: 'architecture', title: 'So funktioniert es', description: 'Hinter den Kulissen' },
    { id: 'security', title: 'Sicherheit', description: 'Wie wir dich schützen' },
    { id: 'faq', title: 'FAQ', description: 'Häufige Fragen' },
    { id: 'roadmap', title: 'Roadmap', description: 'Was als Nächstes kommt' },
  ],

  overview: {
    heading: 'Willkommen bei Orion Safe',
    intro:
      'Orion Safe ist eine **Multi-Signatur-Treasury-Plattform** auf Stellar. ' +
      'Stell es dir wie ein gemeinsames Bankkonto für dein Team, deine DAO oder Organisation vor – nur mit Superkräften.',
    whyTitle: 'Warum Orion Safe nutzen?',
    whyItems: [
      { emoji: '🔐', title: 'Kein einzelner Fehlerpunkt', desc: 'Mehrere Freigaben erforderlich – selbst wenn ein Schlüssel kompromittiert wird, bleiben die Mittel sicher' },
      { emoji: '⚡', title: 'Blitzschnell & Günstig', desc: 'Transaktionen in ~5 Sekunden, weniger als 0,0001 $ pro Transaktion' },
      { emoji: '⏰', title: 'Zeitbasierte Kontrollen', desc: 'Token bis zu einem Datum sperren oder sie schrittweise freigeben' },
      { emoji: '🌍', title: 'Volle Transparenz', desc: 'Jede Aktion wird On-Chain erfasst – teile schreibgeschützte Links mit jedem' },
    ],
    perfectForTitle: 'Perfekt Für',
    perfectFor: [
      { icon: '🏛️', title: 'DAOs & Treasuries', desc: 'Verwalte Community-Mittel mit transparenter Multi-Sig-Governance' },
      { icon: '👥', title: 'Teams & Startups', desc: 'Sichere die Unternehmens-Treasury mit rollenbasiertem Zugriff' },
      { icon: '💼', title: 'Mitarbeiter-Vesting', desc: '4-Jahres-Token-Vesting mit 1-Jahres-Cliff, vollständig automatisiert' },
      { icon: '🤝', title: 'Treuhanddienste', desc: '2-von-2-Einvernehmen für sichere Transaktionen' },
      { icon: '🎁', title: 'Förderungen & Gehälter', desc: 'Massen-Token-Verteilungen mit geplanten Freigaben' },
      { icon: '📊', title: 'Investmentfonds', desc: 'Komitee-Freigabe für die Fondsverwaltung' },
    ],
    liveTitle: 'Live im Stellar-Testnet',
    liveDesc:
      'Orion Safe ist derzeit im Stellar-Testnet live. Teste es jetzt mit Test-Token! ' +
      'Mainnet-Start für Q4 2026 nach dem Sicherheitsaudit geplant.',
  },

  quickstart: {
    heading: 'Schnellstart-Anleitung',
    subtitle: 'Bring deinen ersten Vault in unter 5 Minuten zum Laufen.',
    step1Title: 'Verbinde deine Wallet',
    step1Intro: 'Klicke oben rechts auf **„Wallet verbinden"** und wähle deine bevorzugte Wallet:',
    wallets: [
      { name: 'Freighter', note: 'Empfohlen' },
      { name: 'Lobstr', note: 'Mobil-freundlich' },
      { name: 'xBull', note: 'Power-User' },
      { name: 'Albedo', note: 'Webbasiert' },
    ],
    noWalletTitle: 'Keine Wallet?',
    noWalletDesc: 'Installiere {{freighter}} – eine kostenlose Browser-Erweiterung, die in 2 Minuten eingerichtet ist.',
    step2Title: 'Erstelle deinen Vault',
    step2Items: [
      'Klicke auf **„Vault erstellen"**',
      'Gib deinem Vault einen Namen (z. B. „Team-Treasury")',
      'Füge die Wallet-Adressen der Unterzeichner hinzu (Personen, die Transaktionen freigeben können)',
      'Lege deinen **Schwellenwert** fest – wie viele Freigaben nötig sind',
    ],
    exampleLabel: 'Beispiel: 2-von-3-Multi-Sig',
    approvedLabel: '2/3 = Freigegeben!',
    step3Title: 'Finanziere deinen Vault',
    step3Intro: 'Dein Vault hat eine eigene Adresse. Sende ihm Token wie an jede Stellar-Wallet:',
    step3Items: [
      'Kopiere deine Vault-Adresse aus dem Dashboard',
      'Sende XLM, USDC oder einen beliebigen Stellar-Token an diese Adresse',
      'Die Mittel erscheinen innerhalb von ~5 Sekunden',
    ],
    proTipTitle: 'Profi-Tipp',
    proTipDesc: 'Für das Testnet bekommst du kostenlose Test-XLM vom {{friendbot}}.',
    step4Title: 'Führe deine erste Transaktion durch',
    step4Steps: [
      { title: 'Vorschlag erstellen', desc: 'Gehe zu Transaktionen → Neu → Details eingeben → Absenden' },
      { title: 'Freigaben sammeln', desc: 'Andere Unterzeichner prüfen und klicken auf „Freigeben"' },
      { title: 'Ausführen', desc: 'Sobald der Schwellenwert erreicht ist, kann jeder auf „Ausführen" klicken' },
    ],
    doneTitle: '🎉 Das war\'s!',
    doneDesc:
      'Du hast jetzt einen sicheren Multi-Sig-Vault. Erkunde die Seitenleiste, um Zeitsperren, ' +
      'Vesting-Pläne und weitere fortgeschrittene Funktionen zu entdecken.',
  },

  features: {
    heading: 'Kernfunktionen',
    multiSig: {
      title: 'Multi-Signatur-Sicherheit',
      desc: 'Verlange, dass mehrere Personen Transaktionen freigeben. Du wählst den Schwellenwert – ob 2-von-3 für ein kleines Team oder 5-von-9 für eine große DAO.',
      configs: ['2-von-3', '3-von-5', '4-von-7', '5-von-9'],
    },
    proposal: {
      title: 'Vorschlagsbasierter Ablauf',
      desc: 'Alle Transaktionen durchlaufen einen transparenten Vorschlagsprozess. Keine Überraschungen, volle Rechenschaft.',
      steps: [
        { title: 'Vorschlagen', sub: 'Jeder Unterzeichner' },
        { title: 'Freigeben', sub: 'Schwellenwert erreichen' },
        { title: 'Ausführen', sub: 'Jeder' },
      ],
    },
    txTypes: {
      title: 'Transaktionstypen',
      items: [
        { icon: '💸', title: 'Überweisung', desc: 'Sende Token sofort nach der Freigabe. Einfache, direkte Zahlungen.' },
        { icon: '🔒', title: 'Zeitsperre', desc: 'Sperre Token bis zu einem bestimmten Datum. Perfekt für Treuhand oder geplante Freigaben.' },
        { icon: '📈', title: 'Vesting', desc: 'Schrittweise Freigabe über die Zeit mit optionalem Cliff. Ideal für Mitarbeiter-Token.' },
      ],
    },
    dashboard: {
      title: 'Dashboard-Navigation',
      views: [
        { name: 'Dashboard', desc: 'Überblick & Statistiken' },
        { name: 'Vermögenswerte', desc: 'Token-Guthaben' },
        { name: 'Transaktionen', desc: 'Vorschläge & Verlauf' },
        { name: 'Mitglieder', desc: 'Unterzeichner & Rollen' },
        { name: 'Zeitsperren', desc: 'Geplante Freigaben' },
        { name: 'Vesting', desc: 'Token-Vesting' },
        { name: 'Kontakte', desc: 'Adressbuch' },
        { name: 'Einstellungen', desc: 'Konfiguration' },
      ],
    },
    publicAccess: {
      title: 'Öffentlicher Zugriff & Teilen',
      cards: [
        { title: '🔗 Öffentlicher Ansichts-Link', desc: 'Teile eine schreibgeschützte Ansicht mit Investoren, Prüfern oder der Öffentlichkeit. Sie können Guthaben und Aktivität sehen, aber keine Aktionen ausführen.' },
        { title: '🎁 Einlöse-Link', desc: 'Begünstigte können ihre gesperrten oder gevesteten Token direkt mit ihrer eigenen Wallet einlösen – kein Vault-Zugriff nötig.' },
      ],
    },
  },

  roles: {
    heading: 'Rollen & Berechtigungen',
    intro: 'Orion Safe nutzt ein rollenbasiertes System, um zu steuern, wer was darf. Das bietet Flexibilität bei gleichzeitiger Sicherheit.',
    cards: [
      { name: 'SuperAdmin', badge: 'Volle Kontrolle', desc: 'Vollständige Vault-Kontrolle. SuperAdmins können alles tun, einschließlich Aktionen, die Struktur und Sicherheit des Vaults betreffen.', canLabel: 'Kann:', can: 'Unterzeichner hinzufügen/entfernen, den Freigabe-Schwellenwert ändern, jede widerrufbare Sperre aufheben, Vault-Einstellungen aktualisieren – plus alles, was Admins und Executors können.' },
      { name: 'Admin', badge: 'Betrieb', desc: 'Verantwortlich für den laufenden Betrieb. Admins übernehmen die meisten Treasury-Aktivitäten, können aber die Sicherheitseinstellungen des Vaults nicht ändern.', canLabel: 'Kann:', can: 'Vorschläge erstellen, Transaktionen freigeben, freigegebene Transaktionen ausführen, Zeitsperren und Vesting-Pläne erstellen, Kontakte verwalten.' },
      { name: 'Executor', badge: 'Freigeben & Ausführen', desc: 'Freigabe-Befugnis. Executors können über Vorschläge abstimmen und freigegebene Transaktionen ausführen, aber keine neuen anstoßen.', canLabel: 'Kann:', can: 'Vorschläge freigeben oder ablehnen, Transaktionen ausführen, die den Schwellenwert erreicht haben.' },
      { name: 'Viewer', badge: 'Nur Lesen', desc: 'Beobachter-Zugriff. Viewer können alles sehen, aber keine Aktionen ausführen. Perfekt für Prüfer oder Stakeholder.', canLabel: 'Kann:', can: 'Vault-Guthaben, Transaktionsverlauf, Vorschläge, Sperren und alle Aktivitäten ansehen.' },
    ],
    matrixTitle: 'Berechtigungsübersicht',
    matrixHeaders: { action: 'Aktion', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Vault & Guthaben ansehen', super: true, admin: true, exec: true, view: true },
      { action: 'Vorschläge erstellen', super: true, admin: true, exec: false, view: false },
      { action: 'Vorschläge freigeben', super: true, admin: true, exec: true, view: false },
      { action: 'Transaktionen ausführen', super: true, admin: true, exec: true, view: false },
      { action: 'Zeitsperren / Vesting erstellen', super: true, admin: true, exec: false, view: false },
      { action: 'Widerrufbare Sperren aufheben', super: true, admin: false, exec: false, view: false },
      { action: 'Unterzeichner hinzufügen/entfernen', super: true, admin: false, exec: false, view: false },
      { action: 'Schwellenwert ändern', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Best Practice: Rollenzuweisung',
    bestPractice: [
      'Beschränke SuperAdmin auf 1-2 vertrauenswürdige Personen (Gründer, Führungskräfte)',
      'Nutze Admin für Mitglieder des Finanzteams, die den Tagesbetrieb verwalten',
      'Nutze Executor für Vorstandsmitglieder, die nur freigeben, nicht anstoßen',
      'Nutze Viewer für Stakeholder, Prüfer oder öffentliche Transparenz',
    ],
  },

  locks: {
    heading: 'Zeitsperren & Vesting',
    intro: 'Steuere, wann Token verfügbar werden. Ob du Treuhand, geplante Zahlungen oder Mitarbeiter-Token-Vesting brauchst – wir haben das für dich abgedeckt.',
    timeLockTitle: 'Zeitsperren',
    timeLockDesc: 'Sperre Token bis zu einem bestimmten Datum. Der Begünstigte kann den **gesamten Betrag** erst einlösen, nachdem der Entsperrzeitpunkt verstrichen ist. Vor diesem Datum sind die Token vollständig unzugänglich.',
    timeLockExampleLabel: 'Beispiel: Treuhand-Einzahlung',
    timeLockExampleAmount: '10.000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Treuhand', desc: 'Halte Mittel zurück, bis Bedingungen erfüllt sind' },
      { icon: '🎯', title: 'Meilenstein-Zahlungen', desc: 'Freigabe, wenn das Ergebnis fertig ist' },
      { icon: '🏦', title: 'Sparziele', desc: 'Verhindere impulsive Abhebungen' },
    ],
    vestingTitle: 'Vesting-Pläne',
    vestingDesc: 'Gib Token **schrittweise über die Zeit** frei, mit optionaler Cliff-Periode. Dies ist der Branchenstandard für Mitarbeitervergütung und Investorenzuteilungen.',
    vestingExampleLabel: 'Beispiel: 4-Jahres-Mitarbeiter-Vesting mit 1-Jahres-Cliff',
    vestingExampleAmount: '100.000 Token',
    vestingBarCliff: 'Cliff (1 J.)',
    vestingBarLinear: 'Lineares Vesting → 100%',
    vestingTimeline: { start: 'Start', cliff: 'Cliff: 25% entsperrt', y2: 'Jahr 2: 50%', y3: 'Jahr 3: 75%', y4: 'Jahr 4: 100%' },
    howVestingTitle: 'So funktioniert Vesting',
    howVestingSteps: [
      { title: 'Cliff-Periode:', desc: 'Bis zum Cliff-Datum wird nichts gevestet. Verlässt jemand das Unternehmen vor dem Cliff, erhält er nichts.' },
      { title: 'Cliff-Entsperrung:', desc: 'Am Cliff-Datum wird ein Teil sofort entsperrt (typischerweise 25% bei einem 4-Jahres-Plan).' },
      { title: 'Lineares Vesting:', desc: 'Nach dem Cliff vesten die Token kontinuierlich bis zum Enddatum.' },
      { title: 'Jederzeit einlösen:', desc: 'Begünstigte können ihre gevesteten Token einlösen, wann immer sie möchten – ohne Fristen.' },
    ],
    revTitle: 'Widerrufbar vs. Nicht Widerrufbar',
    revocable: { title: '✓ Widerrufbar', desc: 'Der SuperAdmin kann die Sperre aufheben und nicht gevestete Token an den Vault zurückgeben.', bestFor: 'Am besten für: Mitarbeiter-Vesting (mit Kündigungsklausel), bedingte Förderungen, interne Zuteilungen' },
    nonRevocable: { title: '✗ Nicht Widerrufbar', desc: 'Kann nach der Erstellung nicht aufgehoben werden. Die Token sind dem Begünstigten in jedem Fall garantiert.', bestFor: 'Am besten für: Investorenzuteilungen, unwiderrufliche Förderungen, vertrauensfreie Treuhand, Berater-Token' },
    bulkTitle: 'Massenerstellung',
    bulkDesc: 'Musst du viele Sperren auf einmal erstellen? Nutze die Massen-Upload-Funktion mit einer CSV-Datei. Perfekt für Team-Token-Verteilungen, Gehaltsabrechnungen oder Förderprogramme.',
    bulkPrepLabel: 'Bereite einfach eine Tabelle vor mit:',
    bulkFields: [
      'Wallet-Adresse des Begünstigten',
      'Token-Menge',
      'Entsperrdatum (für Zeitsperren) oder Vesting-Parameter',
      'Ob widerrufbar',
      'Optionale Beschreibung',
    ],
    bulkNote: 'Lade die CSV hoch, prüfe die Einträge und erstelle bis zu 10 Sperren pro Stapel.',
  },

  tokens: {
    heading: 'Unterstützte Token',
    usdcTitle: 'Natives USDC auf Stellar',
    usdcSubtitle: 'Circles offizieller Stablecoin – nicht gewrappt, nicht gebridget',
    usdcDesc: 'Orion Safe bietet erstklassige Unterstützung für USDC. Erstelle in Dollar denominierte Vaults, richte Gehalts-Vesting in stabiler Währung ein oder sperre Treuhandmittel ohne Volatilitätsrisiko.',
    allTitle: 'Alle Unterstützten Vermögenswerte',
    allIntro: 'Orion Safe unterstützt **jeden Token im Stellar-Netzwerk**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Der native Token von Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'US-Dollar-Stablecoin' },
      { emoji: '💶', name: 'EURC', desc: 'Euro-Stablecoin' },
      { emoji: '🪙', name: 'Jeder Token', desc: 'Benutzerdefinierte Stellar-Assets' },
    ],
    whatTitle: 'Was du mit Token tun kannst',
    whatItems: [
      { icon: '💸', title: 'Multi-Sig-Überweisungen', desc: 'Sende jeden Token mit Multi-Signatur-Freigabe' },
      { icon: '🔒', title: 'Jedes Asset zeitsperren', desc: 'Sperre USDC, XLM oder benutzerdefinierte Token bis zu einem bestimmten Datum' },
      { icon: '📈', title: 'Token-Vesting', desc: 'Erstelle Vesting-Pläne für jedes Stellar-Asset' },
      { icon: '📊', title: 'Massen-Verteilungen', desc: 'Verteile Token per CSV an mehrere Empfänger' },
    ],
    testTitle: 'Testnet-Token Erhalten',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Gehe zu {{laboratory}}',
      'Gib deine Testnet-Wallet-Adresse ein',
      'Klicke auf „Fund account with Friendbot"',
      'Erhalte sofort 10.000 Test-XLM!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Füge eine USDC-Trustline in deiner Wallet hinzu (Freighter → Manage Assets → Add USDC)',
      'Nutze einen Testnet-USDC-Faucet oder tausche XLM am Testnet-DEX',
    ],
  },

  architecture: {
    heading: 'So funktioniert es',
    intro: 'Eine einfache Erklärung, was hinter den Kulissen passiert, wenn du Orion Safe nutzt.',
    basicsTitle: 'Die Grundlagen',
    basicsParas: [
      'Wenn du einen Vault erstellst, stellt Orion Safe einen **Smart Contract** auf der Stellar-Blockchain bereit. Dieser Smart Contract ist wie ein programmierbares Schließfach, das deine Vermögenswerte verwahrt.',
      'Der Smart Contract setzt alle Regeln durch: wer Transaktionen vorschlagen darf, wie viele Freigaben nötig sind, wann gesperrte Token freigegeben werden können und mehr. **Niemand kann diese Regeln umgehen** – nicht einmal das Orion-Safe-Team.',
    ],
    flowTitle: 'Was passiert, wenn du Token sendest',
    flowSteps: [
      { title: 'Du erstellst einen Vorschlag', desc: 'Gib Empfänger, Betrag und ein optionales Memo an. Der Vorschlag wird auf der Blockchain erfasst.' },
      { title: 'Andere Unterzeichner geben frei', desc: 'Jede Freigabe wird On-Chain erfasst. Jeder kann sehen, wer freigegeben hat.' },
      { title: 'Schwellenwert erreicht', desc: 'Sobald genügend Unterzeichner freigeben (z. B. 2 von 3), ist die Transaktion zur Ausführung bereit.' },
      { title: 'Ausführen & Bestätigen', desc: 'Jeder kann die Ausführung auslösen. Token bewegen sich sofort (~5 Sekunden). Fertig!' },
    ],
    whyTitle: 'Warum wir auf Stellar gebaut haben',
    whyItems: [
      { icon: '⚡', title: 'Schnell', desc: 'Transaktionen bestätigen in ~5 Sekunden' },
      { icon: '💰', title: 'Günstig', desc: 'Weniger als 0,0001 $ pro Transaktion' },
      { icon: '🏦', title: 'Vertrauenswürdig', desc: 'Genutzt von Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Sicher', desc: 'Praxiserprobtes Netzwerk seit 2015' },
      { icon: '💵', title: 'Natives USDC', desc: 'Echte Stablecoins, keine gewrappten Token' },
      { icon: '🌍', title: 'Global', desc: 'Funktioniert überall mit Internetzugang' },
    ],
    truthTitle: 'Wichtig: Die Blockchain ist die Quelle der Wahrheit',
    truthDesc: 'Dein Vault existiert auf der Stellar-Blockchain, nicht auf unseren Servern. Selbst wenn unsere Website offline ginge, blieben dein Vault und deine Mittel über andere Stellar-Tools sicher und zugänglich. Wir stellen lediglich eine benutzerfreundliche Oberfläche bereit, um mit deinem On-Chain-Vault zu interagieren.',
  },

  security: {
    heading: 'Sicherheit',
    intro: 'Wie Orion Safe deine Vermögenswerte sicher hält.',
    principlesTitle: 'Grundlegende Sicherheitsprinzipien',
    principles: [
      { title: 'On-Chain-Durchsetzung', desc: 'Alle Regeln werden vom Smart Contract auf der Blockchain durchgesetzt. Die Website ist nur eine Benutzeroberfläche – die Blockchain ist die Autorität.' },
      { title: 'Keine Hintertüren', desc: 'Niemand – nicht einmal das Orion-Safe-Team – kann ohne die richtigen Signaturen auf deinen Vault zugreifen oder deine Mittel bewegen.' },
      { title: 'Multi-Sig standardmäßig', desc: 'Selbst wenn ein Schlüssel kompromittiert wird, können Angreifer keine Mittel bewegen, ohne deinen Freigabe-Schwellenwert zu erreichen.' },
    ],
    threatsTitle: 'Wie wir vor Bedrohungen schützen',
    threats: [
      { threat: 'Kompromittierter Unterzeichner-Schlüssel', mitigation: 'Der Multi-Sig-Schwellenwert verhindert Angriffe mit einem einzigen Schlüssel. Andere Unterzeichner können den kompromittierten Schlüssel entfernen.' },
      { threat: 'Böswilliger Vorschlag', mitigation: 'Erfordert mehrere Freigaben. Andere Unterzeichner können schädliche Vorschläge ablehnen.' },
      { threat: 'Verlorene Schlüssel', mitigation: 'Solange die verbleibenden Unterzeichner den Schwellenwert erreichen, bleibt der Vault zugänglich.' },
      { threat: 'Website fällt aus', mitigation: 'Dein Vault existiert auf der Blockchain. Greife über andere Stellar-Tools darauf zu.' },
      { threat: 'Datenbank-Verletzung', mitigation: 'Unsere Datenbank ist nur ein Cache für schnelleres Laden. Die Blockchain ist die Quelle der Wahrheit.' },
    ],
    bestTitle: 'Sicherheits-Best-Practices',
    doTitle: '✓ Tun',
    dos: [
      'Nutze Hardware-Wallets (wie Ledger) für Unterzeichner-Schlüssel',
      'Halte den Schwellenwert bei 2 oder höher (niemals einzelner Unterzeichner)',
      'Überprüfe regelmäßig deine Unterzeichner-Liste',
      'Nutze separate Vaults für unterschiedliche Zwecke',
      'Teste zuerst mit kleinen Beträgen',
      'Sichere deine Wiederherstellungsphrasen sicher',
    ],
    dontTitle: '✗ Nicht Tun',
    donts: [
      'Private Schlüssel per E-Mail oder Chat teilen',
      'Denselben Schlüssel für mehrere kritische Vaults nutzen',
      'Ausstehende Vorschläge zu lange ignorieren',
      'Den Schwellenwert gleich der Gesamtzahl der Unterzeichner setzen (keine Redundanz)',
      'Wiederherstellungsphrasen digital unverschlüsselt speichern',
      'SuperAdmin-Zugriff an Personen geben, denen du nicht voll vertraust',
    ],
    statusTitle: 'Sicherheitsstatus',
    statuses: [
      { color: 'green', text: 'Auf dem praxiserprobten Stellar-Netzwerk aufgebaut (seit 2015)' },
      { color: 'green', text: 'Integration des OpenZeppelin Smart Account Frameworks' },
      { color: 'yellow', text: 'Professionelles Sicherheitsaudit vor der Mainnet geplant (Q4 2026)' },
      { color: 'gray', text: 'Bug-Bounty-Programm kommt nach dem Mainnet-Start' },
    ],
  },

  roadmap: {
    heading: 'Roadmap',
    liveTitle: 'Derzeit Live im Testnet',
    liveFeatures: ['Multi-Sig-Vaults', 'Rollenbasierter Zugriff', 'Zeitsperren', 'Vesting-Pläne', 'Massen-CSV-Import', 'Öffentliche Ansichts-Links', 'Einlöse-Portal', 'Multi-Wallet-Unterstützung'],
    phases: [
      { color: 'purple', title: 'Phase 1: Produktionsreife', target: 'Ziel: Juli 2026', items: ['Vorbereitung des Mainnet-Deployments', 'Sicherheitshärtung und Tests', 'Performance-Optimierung', 'Verbesserte Fehlerbehandlung'] },
      { color: 'blue', title: 'Phase 2: Erweiterte Funktionen', target: 'Ziel: September 2026', items: ['Ausgabenlimits (tägliche/wöchentliche/monatliche Obergrenzen)', 'Verbesserte Vesting-Vorlagen', 'Erweiterte Vorschlagsoptionen', 'Verbessertes mobiles Erlebnis'] },
      { color: 'cyan', title: 'Phase 3: Mainnet-Start', target: 'Ziel: November 2026', items: ['Professionelles Sicherheitsaudit', 'Stellar-DEX-Integration (Handel im Vault)', 'Entwickler-SDK', 'Umfassende Benutzerhandbücher und Tutorials', '🚀 **Mainnet-Deployment**'] },
    ],
    futureTitle: 'Zukunftsvision (2027+)',
    future: [
      { title: 'DeFi-Integration', desc: 'Renditestrategien, Kreditprotokolle, Liquiditätsbereitstellung' },
      { title: 'Enterprise-Suite', desc: 'White-Label-Optionen, SSO, Compliance-Berichte' },
      { title: 'Automatisierung', desc: 'Geplante wiederkehrende Zahlungen, intelligente Bedingungen' },
      { title: 'Integrationen', desc: 'API, Webhooks, Verbindungen zu Buchhaltungssoftware' },
    ],
    followTitle: 'Verfolge unseren Fortschritt',
    followDesc: 'Wir entwickeln öffentlich. Beobachte unser GitHub-Repository für Updates oder schau hier wieder vorbei für die neuesten Nachrichten.',
  },

  faq: {
    heading: 'Häufig Gestellte Fragen',
    items: [
      { q: 'Ist Orion Safe kostenlos nutzbar?', a: 'Ja! Die Plattform ist kostenlos. Du zahlst nur die üblichen Stellar-Netzwerkgebühren (weniger als 0,0001 $ pro Transaktion) sowie eine kleine einmalige Einzahlung beim Erstellen eines Vaults.' },
      { q: 'Was passiert, wenn ich meinen privaten Schlüssel verliere?', a: 'Solange die verbleibenden Unterzeichner den Freigabe-Schwellenwert erreichen, bleibt der Vault voll zugänglich. In einem 2-von-3-Vault können z. B. bei Verlust eines Schlüssels die anderen 2 Unterzeichner den Vault weiter betreiben und sogar einen Ersatz-Unterzeichner hinzufügen.' },
      { q: 'Kann das Orion-Safe-Team auf meine Mittel zugreifen?', a: 'Nein. Dein Vault ist ein Smart Contract auf der Stellar-Blockchain. Nur von dir hinzugefügte Unterzeichner können Transaktionen autorisieren. Wir haben keinen Sonderzugriff, keine Hintertüren und keine Admin-Schlüssel zu deinem Vault.' },
      { q: 'Welche Token kann ich speichern?', a: 'Jedes Stellar-Asset: XLM (nativ), USDC, EURC und tausende weitere im Stellar-Netzwerk ausgegebene Token.' },
      { q: 'Wie schnell sind Transaktionen?', a: 'Etwa 5 Sekunden nach der Ausführung. Der Freigabeprozess hängt davon ab, wie schnell deine Unterzeichner reagieren.' },
      { q: 'Kann ich eine Zeitsperre oder einen Vesting-Plan aufheben?', a: 'Nur wenn sie als „widerrufbar" erstellt wurde. Nicht widerrufbare Sperren können nach der Erstellung nicht aufgehoben werden – die Token sind dem Begünstigten garantiert.' },
      { q: 'Gibt es eine mobile App?', a: 'Das Dashboard ist vollständig responsiv und funktioniert hervorragend in mobilen Browsern. Nutze es mit mobilen Wallets wie Lobstr oder verbinde dich über WalletConnect.' },
      { q: 'Was, wenn die Website ausfällt?', a: 'Dein Vault existiert auf der Stellar-Blockchain, nicht auf unseren Servern. Du kannst über das Stellar Laboratory oder jedes kompatible Tool damit interagieren, selbst wenn unsere Website nicht verfügbar ist.' },
      { q: 'Wie lösen Begünstigte ihre Token ein?', a: 'Teile einen Einlöse-Link mit ihnen (zu finden unter Einstellungen → Teilen). Sie verbinden ihre eigene Wallet und lösen direkt ein – kein Vault-Zugriff nötig.' },
      { q: 'Gibt es ein Limit für die Anzahl der Unterzeichner?', a: 'Derzeit werden bis zu 10 Unterzeichner pro Vault unterstützt. Brauchst du mehr? Kontaktiere uns für Enterprise-Lösungen.' },
      { q: 'Was ist der Unterschied zwischen Testnet und Mainnet?', a: 'Das Testnet nutzt gefälschte Token zum Testen – ohne echten Wert. Das Mainnet nutzt echte Token und echtes Geld. Wir sind derzeit im Testnet, der Mainnet-Start ist für Q4 2026 geplant.' },
      { q: 'Wie bekomme ich Hilfe, wenn etwas schiefgeht?', a: 'Sieh zuerst in diese Dokumentation. Wenn du weiterhin Hilfe brauchst, öffne ein Issue in unserem GitHub-Repository oder kontaktiere uns über unsere Kanäle.' },
    ],
  },

  common: {
    locked: '🔒 Gesperrt',
    claimable: '✓ Einlösbar',
    today: 'Heute',
    unlockDate: '⏰ Entsperrdatum',
    claimed: 'Eingelöst',
    viewOnGithub: 'Auf GitHub ansehen',
  },
};
