import { DocsContent } from './types';

export const docsEn: DocsContent = {
  sidebarTitle: 'Documentation',
  sections: [
    { id: 'overview', title: 'Overview', description: 'What is Orion Safe?' },
    { id: 'quickstart', title: 'Quick Start', description: '5-minute setup guide' },
    { id: 'features', title: 'Core Features', description: 'What you can do' },
    { id: 'roles', title: 'Roles & Permissions', description: 'Who can do what' },
    { id: 'locks', title: 'Time Locks & Vesting', description: 'Schedule token releases' },
    { id: 'tokens', title: 'Supported Tokens', description: 'USDC, XLM & more' },
    { id: 'architecture', title: 'How It Works', description: 'Under the hood' },
    { id: 'security', title: 'Security', description: 'How we keep you safe' },
    { id: 'faq', title: 'FAQ', description: 'Common questions' },
    { id: 'roadmap', title: 'Roadmap', description: "What's coming next" },
  ],

  overview: {
    heading: 'Welcome to Orion Safe',
    intro:
      'Orion Safe is a **multi-signature treasury platform** built on Stellar. ' +
      'Think of it as a shared bank account for your team, DAO, or organization — but with superpowers.',
    whyTitle: 'Why Use Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'No Single Point of Failure', desc: 'Multiple approvals required — even if one key is compromised, funds stay safe' },
      { emoji: '⚡', title: 'Lightning Fast & Cheap', desc: '~5 second transactions, less than $0.0001 per transaction' },
      { emoji: '⏰', title: 'Time-Based Controls', desc: 'Lock tokens until a date, or release them gradually over time' },
      { emoji: '🌍', title: 'Full Transparency', desc: 'Every action recorded on-chain — share read-only links with anyone' },
    ],
    perfectForTitle: 'Perfect For',
    perfectFor: [
      { icon: '🏛️', title: 'DAOs & Treasuries', desc: 'Manage community funds with transparent multi-sig governance' },
      { icon: '👥', title: 'Teams & Startups', desc: 'Secure company treasury with role-based access' },
      { icon: '💼', title: 'Employee Vesting', desc: '4-year token vesting with 1-year cliff, fully automated' },
      { icon: '🤝', title: 'Escrow Services', desc: '2-of-2 mutual agreement for secure transactions' },
      { icon: '🎁', title: 'Grants & Payroll', desc: 'Bulk token distributions with scheduled releases' },
      { icon: '📊', title: 'Investment Funds', desc: 'Committee approval for fund management' },
    ],
    liveTitle: 'Live on Stellar Testnet',
    liveDesc:
      'Orion Safe is currently live on Stellar testnet. Try it now with test tokens! ' +
      'Mainnet launch planned for Q4 2026 following security audit.',
  },

  quickstart: {
    heading: 'Quick Start Guide',
    subtitle: 'Get your first vault running in under 5 minutes.',
    step1Title: 'Connect Your Wallet',
    step1Intro: 'Click **"Connect Wallet"** in the top right corner and select your preferred wallet:',
    wallets: [
      { name: 'Freighter', note: 'Recommended' },
      { name: 'Lobstr', note: 'Mobile-friendly' },
      { name: 'xBull', note: 'Power users' },
      { name: 'Albedo', note: 'Web-based' },
    ],
    noWalletTitle: "Don't have a wallet?",
    noWalletDesc: "Install {{freighter}} — it's a free browser extension that takes 2 minutes to set up.",
    step2Title: 'Create Your Vault',
    step2Items: [
      'Click **"Create Vault"**',
      'Give your vault a name (e.g., "Team Treasury")',
      'Add signer wallet addresses (people who can approve transactions)',
      'Set your **threshold** — how many approvals are needed',
    ],
    exampleLabel: 'Example: 2-of-3 Multi-Sig',
    approvedLabel: '2/3 = Approved!',
    step3Title: 'Fund Your Vault',
    step3Intro: 'Your vault has its own address. Send tokens to it like any Stellar wallet:',
    step3Items: [
      'Copy your vault address from the dashboard',
      'Send XLM, USDC, or any Stellar token to that address',
      'Funds appear within ~5 seconds',
    ],
    proTipTitle: 'Pro Tip',
    proTipDesc: 'For testnet, get free test XLM from the {{friendbot}}.',
    step4Title: 'Make Your First Transaction',
    step4Steps: [
      { title: 'Create Proposal', desc: 'Go to Transactions → New → Enter details → Submit' },
      { title: 'Collect Approvals', desc: 'Other signers review and click "Approve"' },
      { title: 'Execute', desc: 'Once threshold is met, anyone can click "Execute"' },
    ],
    doneTitle: "🎉 That's it!",
    doneDesc:
      'You now have a secure multi-sig vault. Explore the sidebar to discover time-locks, ' +
      'vesting schedules, and more advanced features.',
  },

  features: {
    heading: 'Core Features',
    multiSig: {
      title: 'Multi-Signature Security',
      desc: "Require multiple people to approve transactions. You choose the threshold — whether it's 2-of-3 for a small team or 5-of-9 for a large DAO.",
      configs: ['2-of-3', '3-of-5', '4-of-7', '5-of-9'],
    },
    proposal: {
      title: 'Proposal-Based Workflow',
      desc: 'All transactions go through a transparent proposal process. No surprises, full accountability.',
      steps: [
        { title: 'Propose', sub: 'Any signer' },
        { title: 'Approve', sub: 'Meet threshold' },
        { title: 'Execute', sub: 'Anyone' },
      ],
    },
    txTypes: {
      title: 'Transaction Types',
      items: [
        { icon: '💸', title: 'Transfer', desc: 'Send tokens immediately after approval. Simple, direct payments.' },
        { icon: '🔒', title: 'Time Lock', desc: 'Lock tokens until a specific date. Perfect for escrow or scheduled releases.' },
        { icon: '📈', title: 'Vesting', desc: 'Gradual release over time with optional cliff. Ideal for employee tokens.' },
      ],
    },
    dashboard: {
      title: 'Dashboard Navigation',
      views: [
        { name: 'Dashboard', desc: 'Overview & stats' },
        { name: 'Assets', desc: 'Token balances' },
        { name: 'Transactions', desc: 'Proposals & history' },
        { name: 'Members', desc: 'Signers & roles' },
        { name: 'Time Locks', desc: 'Scheduled releases' },
        { name: 'Vesting', desc: 'Token vesting' },
        { name: 'Contacts', desc: 'Address book' },
        { name: 'Settings', desc: 'Configuration' },
      ],
    },
    publicAccess: {
      title: 'Public Access & Sharing',
      cards: [
        { title: '🔗 Public View Link', desc: 'Share a read-only view with investors, auditors, or the public. They can see balances and activity but cannot take any actions.' },
        { title: '🎁 Claim Link', desc: 'Beneficiaries can claim their locked or vested tokens directly using their own wallet — no vault access needed.' },
      ],
    },
  },

  roles: {
    heading: 'Roles & Permissions',
    intro: 'Orion Safe uses a role-based system to control who can do what. This provides flexibility while maintaining security.',
    cards: [
      { name: 'SuperAdmin', badge: 'Full Control', desc: "Complete vault control. SuperAdmins can do everything, including actions that affect the vault's structure and security.", canLabel: 'Can:', can: 'Add/remove signers, change approval threshold, cancel any revocable lock, update vault settings, plus everything Admins and Executors can do.' },
      { name: 'Admin', badge: 'Operations', desc: "Day-to-day operations manager. Admins handle most treasury activities but cannot change the vault's security settings.", canLabel: 'Can:', can: 'Create proposals, approve transactions, execute approved transactions, create time locks and vesting schedules, manage contacts.' },
      { name: 'Executor', badge: 'Approve & Execute', desc: 'Approval authority. Executors can vote on proposals and execute approved transactions, but cannot initiate new ones.', canLabel: 'Can:', can: 'Approve or reject proposals, execute transactions that have met the threshold.' },
      { name: 'Viewer', badge: 'Read Only', desc: 'Observer access. Viewers can see everything but cannot take any actions. Perfect for auditors or stakeholders.', canLabel: 'Can:', can: 'View vault balances, transaction history, proposals, locks, and all activity.' },
    ],
    matrixTitle: 'Permission Summary',
    matrixHeaders: { action: 'Action', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'View vault & balances', super: true, admin: true, exec: true, view: true },
      { action: 'Create proposals', super: true, admin: true, exec: false, view: false },
      { action: 'Approve proposals', super: true, admin: true, exec: true, view: false },
      { action: 'Execute transactions', super: true, admin: true, exec: true, view: false },
      { action: 'Create time locks / vesting', super: true, admin: true, exec: false, view: false },
      { action: 'Cancel revocable locks', super: true, admin: false, exec: false, view: false },
      { action: 'Add/remove signers', super: true, admin: false, exec: false, view: false },
      { action: 'Change threshold', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Best Practice: Role Assignment',
    bestPractice: [
      'Keep SuperAdmin to 1-2 trusted people (founders, executives)',
      'Use Admin for finance team members who manage day-to-day operations',
      'Use Executor for board members who only approve, not initiate',
      'Use Viewer for stakeholders, auditors, or public transparency',
    ],
  },

  locks: {
    heading: 'Time Locks & Vesting',
    intro: "Control when tokens become available. Whether you need escrow, scheduled payments, or employee token vesting — we've got you covered.",
    timeLockTitle: 'Time Locks',
    timeLockDesc: 'Lock tokens until a specific date. The beneficiary can claim the **full amount** only after the unlock time passes. Before that date, the tokens are completely inaccessible.',
    timeLockExampleLabel: 'Example: Escrow Deposit',
    timeLockExampleAmount: '10,000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Escrow', desc: 'Hold funds until conditions are met' },
      { icon: '🎯', title: 'Milestone Payments', desc: 'Release when deliverable is complete' },
      { icon: '🏦', title: 'Savings Goals', desc: 'Prevent impulsive withdrawals' },
    ],
    vestingTitle: 'Vesting Schedules',
    vestingDesc: 'Release tokens **gradually over time** with an optional cliff period. This is the industry standard for employee compensation and investor allocations.',
    vestingExampleLabel: 'Example: 4-Year Employee Vesting with 1-Year Cliff',
    vestingExampleAmount: '100,000 tokens',
    vestingBarCliff: 'Cliff (1yr)',
    vestingBarLinear: 'Linear Vesting → 100%',
    vestingTimeline: { start: 'Start', cliff: 'Cliff: 25% unlocks', y2: 'Year 2: 50%', y3: 'Year 3: 75%', y4: 'Year 4: 100%' },
    howVestingTitle: 'How Vesting Works',
    howVestingSteps: [
      { title: 'Cliff Period:', desc: 'Nothing vests until the cliff date. If someone leaves before the cliff, they get nothing.' },
      { title: 'Cliff Unlock:', desc: 'On the cliff date, a portion unlocks immediately (typically 25% for a 4-year schedule).' },
      { title: 'Linear Vesting:', desc: 'After the cliff, tokens vest continuously until the end date.' },
      { title: 'Claim Anytime:', desc: 'Beneficiaries can claim their vested tokens whenever they want — no deadlines.' },
    ],
    revTitle: 'Revocable vs. Non-Revocable',
    revocable: { title: '✓ Revocable', desc: 'SuperAdmin can cancel the lock and return unvested tokens to the vault.', bestFor: 'Best for: Employee vesting (with termination clause), conditional grants, internal allocations' },
    nonRevocable: { title: '✗ Non-Revocable', desc: 'Cannot be cancelled once created. Tokens are guaranteed to the beneficiary no matter what.', bestFor: 'Best for: Investor allocations, irrevocable grants, trustless escrow, advisor tokens' },
    bulkTitle: 'Bulk Creation',
    bulkDesc: 'Need to create many locks at once? Use the bulk upload feature with a CSV file. Perfect for team token distributions, payroll, or grant programs.',
    bulkPrepLabel: 'Simply prepare a spreadsheet with:',
    bulkFields: [
      'Beneficiary wallet address',
      'Token amount',
      'Unlock date (for time locks) or vesting parameters',
      "Whether it's revocable",
      'Optional description',
    ],
    bulkNote: 'Upload the CSV, review the entries, and create up to 10 locks per batch.',
  },

  tokens: {
    heading: 'Supported Tokens',
    usdcTitle: 'Native USDC on Stellar',
    usdcSubtitle: "Circle's official stablecoin — not wrapped, not bridged",
    usdcDesc: 'Orion Safe has first-class support for USDC. Create vaults denominated in dollars, set up salary vesting in stable currency, or lock escrow funds without volatility risk.',
    allTitle: 'All Supported Assets',
    allIntro: 'Orion Safe supports **any token on the Stellar network**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: "Stellar's native token" },
      { emoji: '💵', name: 'USDC', desc: 'US Dollar stablecoin' },
      { emoji: '💶', name: 'EURC', desc: 'Euro stablecoin' },
      { emoji: '🪙', name: 'Any Token', desc: 'Custom Stellar assets' },
    ],
    whatTitle: 'What You Can Do With Tokens',
    whatItems: [
      { icon: '💸', title: 'Multi-Sig Transfers', desc: 'Send any token with multi-signature approval' },
      { icon: '🔒', title: 'Time-Lock Any Asset', desc: 'Lock USDC, XLM, or custom tokens until a specific date' },
      { icon: '📈', title: 'Token Vesting', desc: 'Create vesting schedules for any Stellar asset' },
      { icon: '📊', title: 'Bulk Distributions', desc: 'Distribute tokens to multiple recipients via CSV' },
    ],
    testTitle: 'Getting Testnet Tokens',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Go to {{laboratory}}',
      'Enter your testnet wallet address',
      'Click "Fund account with Friendbot"',
      'Receive 10,000 test XLM instantly!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Add USDC trustline in your wallet (Freighter → Manage Assets → Add USDC)',
      'Use a testnet USDC faucet or swap XLM on the testnet DEX',
    ],
  },

  architecture: {
    heading: 'How It Works',
    intro: 'A simple explanation of what happens behind the scenes when you use Orion Safe.',
    basicsTitle: 'The Basics',
    basicsParas: [
      'When you create a vault, Orion Safe deploys a **smart contract** on the Stellar blockchain. This smart contract is like a programmable safe deposit box that holds your assets.',
      'The smart contract enforces all the rules: who can propose transactions, how many approvals are needed, when locked tokens can be released, and more. **Nobody can bypass these rules** — not even the Orion Safe team.',
    ],
    flowTitle: 'What Happens When You Send Tokens',
    flowSteps: [
      { title: 'You Create a Proposal', desc: 'Specify recipient, amount, and optional memo. The proposal is recorded on the blockchain.' },
      { title: 'Other Signers Approve', desc: 'Each approval is recorded on-chain. Everyone can see who has approved.' },
      { title: 'Threshold Met', desc: 'Once enough signers approve (e.g., 2 of 3), the transaction is ready to execute.' },
      { title: 'Execute & Confirm', desc: 'Anyone can trigger execution. Tokens move instantly (~5 seconds). Done!' },
    ],
    whyTitle: 'Why We Built on Stellar',
    whyItems: [
      { icon: '⚡', title: 'Fast', desc: 'Transactions confirm in ~5 seconds' },
      { icon: '💰', title: 'Cheap', desc: 'Less than $0.0001 per transaction' },
      { icon: '🏦', title: 'Trusted', desc: 'Used by Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Secure', desc: 'Battle-tested network since 2015' },
      { icon: '💵', title: 'Native USDC', desc: 'Real stablecoins, not wrapped tokens' },
      { icon: '🌍', title: 'Global', desc: 'Works anywhere with internet access' },
    ],
    truthTitle: 'Important: Blockchain is the Source of Truth',
    truthDesc: 'Your vault exists on the Stellar blockchain, not on our servers. Even if our website went offline, your vault and funds would remain safe and accessible through other Stellar tools. We simply provide a user-friendly interface to interact with your on-chain vault.',
  },

  security: {
    heading: 'Security',
    intro: 'How Orion Safe keeps your assets secure.',
    principlesTitle: 'Core Security Principles',
    principles: [
      { title: 'On-Chain Enforcement', desc: 'All rules are enforced by the smart contract on the blockchain. The website is just a user interface — the blockchain is the authority.' },
      { title: 'No Backdoors', desc: 'Nobody — not even the Orion Safe team — can access your vault or move your funds without proper signatures.' },
      { title: 'Multi-Sig by Default', desc: 'Even if one key is compromised, attackers cannot move funds without meeting your approval threshold.' },
    ],
    threatsTitle: 'How We Protect Against Threats',
    threats: [
      { threat: 'Compromised signer key', mitigation: 'Multi-sig threshold prevents single-key attacks. Other signers can remove compromised key.' },
      { threat: 'Malicious proposal', mitigation: 'Requires multiple approvals. Other signers can reject bad proposals.' },
      { threat: 'Lost keys', mitigation: 'As long as remaining signers meet threshold, vault remains accessible.' },
      { threat: 'Website goes down', mitigation: 'Your vault exists on the blockchain. Access it through other Stellar tools.' },
      { threat: 'Database breach', mitigation: 'Our database is only a cache for faster loading. Blockchain is the source of truth.' },
    ],
    bestTitle: 'Security Best Practices',
    doTitle: '✓ Do',
    dos: [
      'Use hardware wallets (like Ledger) for signer keys',
      'Keep threshold at 2 or higher (never single-signer)',
      'Regularly review your signer list',
      'Use separate vaults for different purposes',
      'Test with small amounts first',
      'Back up your recovery phrases securely',
    ],
    dontTitle: "✗ Don't",
    donts: [
      'Share private keys over email or chat',
      'Use the same key for multiple critical vaults',
      'Ignore pending proposals for too long',
      'Set threshold equal to total signers (no redundancy)',
      'Store recovery phrases digitally unencrypted',
      "Give SuperAdmin access to people you don't fully trust",
    ],
    statusTitle: 'Security Status',
    statuses: [
      { color: 'green', text: 'Built on battle-tested Stellar network (since 2015)' },
      { color: 'green', text: 'OpenZeppelin Smart Account framework integration' },
      { color: 'yellow', text: 'Professional security audit planned before mainnet (Q4 2026)' },
      { color: 'gray', text: 'Bug bounty program coming after mainnet launch' },
    ],
  },

  roadmap: {
    heading: 'Roadmap',
    liveTitle: 'Currently Live on Testnet',
    liveFeatures: ['Multi-sig vaults', 'Role-based access', 'Time locks', 'Vesting schedules', 'Bulk CSV import', 'Public view links', 'Claim portal', 'Multi-wallet support'],
    phases: [
      { color: 'purple', title: 'Phase 1: Production Readiness', target: 'Target: July 2026', items: ['Mainnet deployment preparation', 'Security hardening and testing', 'Performance optimization', 'Improved error handling'] },
      { color: 'blue', title: 'Phase 2: Advanced Features', target: 'Target: September 2026', items: ['Spending limits (daily/weekly/monthly caps)', 'Enhanced vesting templates', 'Advanced proposal options', 'Improved mobile experience'] },
      { color: 'cyan', title: 'Phase 3: Mainnet Launch', target: 'Target: November 2026', items: ['Professional security audit', 'Stellar DEX integration (in-vault trading)', 'Developer SDK', 'Comprehensive user guides and tutorials', '🚀 **Mainnet deployment**'] },
    ],
    futureTitle: 'Future Vision (2027+)',
    future: [
      { title: 'DeFi Integration', desc: 'Yield strategies, lending protocols, liquidity provision' },
      { title: 'Enterprise Suite', desc: 'White-label options, SSO, compliance reporting' },
      { title: 'Automation', desc: 'Scheduled recurring payments, smart conditions' },
      { title: 'Integrations', desc: 'API, webhooks, accounting software connections' },
    ],
    followTitle: 'Follow Our Progress',
    followDesc: "We're building in public. Watch our GitHub repository for updates, or check back here for the latest news.",
  },

  faq: {
    heading: 'Frequently Asked Questions',
    items: [
      { q: 'Is Orion Safe free to use?', a: 'Yes! The platform is free. You only pay standard Stellar network fees (less than $0.0001 per transaction) plus a small one-time deposit when creating a vault.' },
      { q: 'What happens if I lose my private key?', a: 'As long as the remaining signers meet the approval threshold, the vault remains fully accessible. For example, in a 2-of-3 vault, if one key is lost, the other 2 signers can still operate the vault and even add a replacement signer.' },
      { q: 'Can the Orion Safe team access my funds?', a: 'No. Your vault is a smart contract on the Stellar blockchain. Only signers you add can authorize transactions. We have no special access, backdoors, or admin keys to your vault.' },
      { q: 'What tokens can I store?', a: 'Any Stellar asset: XLM (native), USDC, EURC, and thousands of other tokens issued on the Stellar network.' },
      { q: 'How fast are transactions?', a: 'About 5 seconds after execution. The approval process depends on how quickly your signers respond.' },
      { q: 'Can I cancel a time-lock or vesting schedule?', a: "Only if it was created as 'revocable'. Non-revocable locks cannot be cancelled once created — the tokens are guaranteed to the beneficiary." },
      { q: 'Is there a mobile app?', a: 'The dashboard is fully responsive and works great on mobile browsers. Use it with mobile wallets like Lobstr or connect via WalletConnect.' },
      { q: 'What if the website goes down?', a: 'Your vault exists on the Stellar blockchain, not on our servers. You can interact with it using the Stellar Laboratory or any compatible tool even if our website is unavailable.' },
      { q: 'How do beneficiaries claim their tokens?', a: 'Share a claim link with them (found in Settings → Share). They connect their own wallet and claim directly — no vault access needed.' },
      { q: 'Is there a limit on the number of signers?', a: 'Currently supports up to 10 signers per vault. Need more? Contact us for enterprise solutions.' },
      { q: "What's the difference between testnet and mainnet?", a: "Testnet uses fake tokens for testing — no real value. Mainnet uses real tokens and real money. We're currently on testnet, with mainnet launch planned for Q4 2026." },
      { q: 'How do I get help if something goes wrong?', a: 'Check this documentation first. If you still need help, open an issue on our GitHub repository or reach out through our contact channels.' },
    ],
  },

  common: {
    locked: '🔒 Locked',
    claimable: '✓ Claimable',
    today: 'Today',
    unlockDate: '⏰ Unlock Date',
    claimed: 'Claimed',
    viewOnGithub: 'View on GitHub',
  },
};
