import { DocsContent } from './types';

export const docsEs: DocsContent = {
  sidebarTitle: 'Documentación',
  sections: [
    { id: 'overview', title: 'Resumen', description: '¿Qué es Orion Safe?' },
    { id: 'quickstart', title: 'Inicio Rápido', description: 'Guía de configuración en 5 minutos' },
    { id: 'features', title: 'Funciones Principales', description: 'Lo que puedes hacer' },
    { id: 'roles', title: 'Roles y Permisos', description: 'Quién puede hacer qué' },
    { id: 'locks', title: 'Bloqueos Temporales y Vesting', description: 'Programa liberaciones de tokens' },
    { id: 'tokens', title: 'Tokens Compatibles', description: 'USDC, XLM y más' },
    { id: 'architecture', title: 'Cómo Funciona', description: 'Por dentro' },
    { id: 'security', title: 'Seguridad', description: 'Cómo te mantenemos a salvo' },
    { id: 'faq', title: 'Preguntas Frecuentes', description: 'Preguntas comunes' },
    { id: 'roadmap', title: 'Hoja de Ruta', description: 'Lo que viene' },
  ],

  overview: {
    heading: 'Bienvenido a Orion Safe',
    intro:
      'Orion Safe es una **plataforma de tesorería multifirma** construida sobre Stellar. ' +
      'Piénsalo como una cuenta bancaria compartida para tu equipo, DAO u organización, pero con superpoderes.',
    whyTitle: '¿Por qué usar Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Sin Punto Único de Fallo', desc: 'Se requieren múltiples aprobaciones — aunque una clave se vea comprometida, los fondos siguen seguros' },
      { emoji: '⚡', title: 'Rápido y Económico', desc: 'Transacciones en ~5 segundos, menos de $0.0001 por transacción' },
      { emoji: '⏰', title: 'Controles Basados en Tiempo', desc: 'Bloquea tokens hasta una fecha, o libéralos gradualmente con el tiempo' },
      { emoji: '🌍', title: 'Transparencia Total', desc: 'Cada acción queda registrada en la cadena — comparte enlaces de solo lectura con cualquiera' },
    ],
    perfectForTitle: 'Perfecto Para',
    perfectFor: [
      { icon: '🏛️', title: 'DAOs y Tesorerías', desc: 'Gestiona fondos comunitarios con gobernanza multifirma transparente' },
      { icon: '👥', title: 'Equipos y Startups', desc: 'Protege la tesorería de la empresa con acceso basado en roles' },
      { icon: '💼', title: 'Vesting de Empleados', desc: 'Vesting de tokens a 4 años con cliff de 1 año, totalmente automatizado' },
      { icon: '🤝', title: 'Servicios de Custodia', desc: 'Acuerdo mutuo 2-de-2 para transacciones seguras' },
      { icon: '🎁', title: 'Subvenciones y Nóminas', desc: 'Distribuciones masivas de tokens con liberaciones programadas' },
      { icon: '📊', title: 'Fondos de Inversión', desc: 'Aprobación por comité para la gestión de fondos' },
    ],
    liveTitle: 'En Vivo en la Testnet de Stellar',
    liveDesc:
      'Orion Safe está actualmente activo en la testnet de Stellar. ¡Pruébalo ahora con tokens de prueba! ' +
      'Lanzamiento en mainnet previsto para el Q4 2026 tras la auditoría de seguridad.',
  },

  quickstart: {
    heading: 'Guía de Inicio Rápido',
    subtitle: 'Pon en marcha tu primer vault en menos de 5 minutos.',
    step1Title: 'Conecta Tu Billetera',
    step1Intro: 'Haz clic en **"Conectar Billetera"** en la esquina superior derecha y selecciona tu billetera preferida:',
    wallets: [
      { name: 'Freighter', note: 'Recomendada' },
      { name: 'Lobstr', note: 'Ideal para móvil' },
      { name: 'xBull', note: 'Usuarios avanzados' },
      { name: 'Albedo', note: 'Basada en web' },
    ],
    noWalletTitle: '¿No tienes billetera?',
    noWalletDesc: 'Instala {{freighter}} — es una extensión de navegador gratuita que se configura en 2 minutos.',
    step2Title: 'Crea Tu Vault',
    step2Items: [
      'Haz clic en **"Crear Vault"**',
      'Dale un nombre a tu vault (p. ej., "Tesorería del Equipo")',
      'Añade las direcciones de billetera de los firmantes (quienes pueden aprobar transacciones)',
      'Establece tu **umbral** — cuántas aprobaciones se necesitan',
    ],
    exampleLabel: 'Ejemplo: Multifirma 2-de-3',
    approvedLabel: '2/3 = ¡Aprobado!',
    step3Title: 'Financia Tu Vault',
    step3Intro: 'Tu vault tiene su propia dirección. Envíale tokens como a cualquier billetera de Stellar:',
    step3Items: [
      'Copia la dirección de tu vault desde el panel',
      'Envía XLM, USDC o cualquier token de Stellar a esa dirección',
      'Los fondos aparecen en ~5 segundos',
    ],
    proTipTitle: 'Consejo Profesional',
    proTipDesc: 'Para la testnet, obtén XLM de prueba gratis desde el {{friendbot}}.',
    step4Title: 'Realiza Tu Primera Transacción',
    step4Steps: [
      { title: 'Crear Propuesta', desc: 'Ve a Transacciones → Nueva → Introduce los datos → Enviar' },
      { title: 'Recopilar Aprobaciones', desc: 'Otros firmantes revisan y hacen clic en "Aprobar"' },
      { title: 'Ejecutar', desc: 'Una vez alcanzado el umbral, cualquiera puede hacer clic en "Ejecutar"' },
    ],
    doneTitle: '🎉 ¡Eso es todo!',
    doneDesc:
      'Ahora tienes un vault multifirma seguro. Explora la barra lateral para descubrir bloqueos temporales, ' +
      'calendarios de vesting y funciones más avanzadas.',
  },

  features: {
    heading: 'Funciones Principales',
    multiSig: {
      title: 'Seguridad Multifirma',
      desc: 'Requiere que varias personas aprueben las transacciones. Tú eliges el umbral, ya sea 2-de-3 para un equipo pequeño o 5-de-9 para una DAO grande.',
      configs: ['2-de-3', '3-de-5', '4-de-7', '5-de-9'],
    },
    proposal: {
      title: 'Flujo Basado en Propuestas',
      desc: 'Todas las transacciones pasan por un proceso de propuesta transparente. Sin sorpresas, con total responsabilidad.',
      steps: [
        { title: 'Proponer', sub: 'Cualquier firmante' },
        { title: 'Aprobar', sub: 'Alcanzar umbral' },
        { title: 'Ejecutar', sub: 'Cualquiera' },
      ],
    },
    txTypes: {
      title: 'Tipos de Transacción',
      items: [
        { icon: '💸', title: 'Transferencia', desc: 'Envía tokens inmediatamente tras la aprobación. Pagos simples y directos.' },
        { icon: '🔒', title: 'Bloqueo Temporal', desc: 'Bloquea tokens hasta una fecha concreta. Perfecto para custodia o liberaciones programadas.' },
        { icon: '📈', title: 'Vesting', desc: 'Liberación gradual en el tiempo con cliff opcional. Ideal para tokens de empleados.' },
      ],
    },
    dashboard: {
      title: 'Navegación del Panel',
      views: [
        { name: 'Panel', desc: 'Resumen y estadísticas' },
        { name: 'Activos', desc: 'Saldos de tokens' },
        { name: 'Transacciones', desc: 'Propuestas e historial' },
        { name: 'Miembros', desc: 'Firmantes y roles' },
        { name: 'Bloqueos Temporales', desc: 'Liberaciones programadas' },
        { name: 'Vesting', desc: 'Vesting de tokens' },
        { name: 'Contactos', desc: 'Libreta de direcciones' },
        { name: 'Ajustes', desc: 'Configuración' },
      ],
    },
    publicAccess: {
      title: 'Acceso Público y Compartir',
      cards: [
        { title: '🔗 Enlace de Vista Pública', desc: 'Comparte una vista de solo lectura con inversores, auditores o el público. Pueden ver saldos y actividad pero no realizar ninguna acción.' },
        { title: '🎁 Enlace de Reclamo', desc: 'Los beneficiarios pueden reclamar sus tokens bloqueados o adquiridos directamente con su propia billetera, sin necesidad de acceso al vault.' },
      ],
    },
  },

  roles: {
    heading: 'Roles y Permisos',
    intro: 'Orion Safe utiliza un sistema basado en roles para controlar quién puede hacer qué. Esto ofrece flexibilidad manteniendo la seguridad.',
    cards: [
      { name: 'SuperAdmin', badge: 'Control Total', desc: 'Control completo del vault. Los SuperAdmins pueden hacer todo, incluidas las acciones que afectan a la estructura y la seguridad del vault.', canLabel: 'Puede:', can: 'Añadir/eliminar firmantes, cambiar el umbral de aprobación, cancelar cualquier bloqueo revocable, actualizar la configuración del vault, además de todo lo que pueden hacer los Admins y Executors.' },
      { name: 'Admin', badge: 'Operaciones', desc: 'Responsable de las operaciones del día a día. Los Admins gestionan la mayoría de las actividades de tesorería pero no pueden cambiar la configuración de seguridad del vault.', canLabel: 'Puede:', can: 'Crear propuestas, aprobar transacciones, ejecutar transacciones aprobadas, crear bloqueos temporales y calendarios de vesting, gestionar contactos.' },
      { name: 'Executor', badge: 'Aprobar y Ejecutar', desc: 'Autoridad de aprobación. Los Executors pueden votar propuestas y ejecutar transacciones aprobadas, pero no pueden iniciar nuevas.', canLabel: 'Puede:', can: 'Aprobar o rechazar propuestas, ejecutar transacciones que hayan alcanzado el umbral.' },
      { name: 'Viewer', badge: 'Solo Lectura', desc: 'Acceso de observador. Los Viewers pueden ver todo pero no pueden realizar ninguna acción. Perfecto para auditores o partes interesadas.', canLabel: 'Puede:', can: 'Ver saldos del vault, historial de transacciones, propuestas, bloqueos y toda la actividad.' },
    ],
    matrixTitle: 'Resumen de Permisos',
    matrixHeaders: { action: 'Acción', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Ver vault y saldos', super: true, admin: true, exec: true, view: true },
      { action: 'Crear propuestas', super: true, admin: true, exec: false, view: false },
      { action: 'Aprobar propuestas', super: true, admin: true, exec: true, view: false },
      { action: 'Ejecutar transacciones', super: true, admin: true, exec: true, view: false },
      { action: 'Crear bloqueos temporales / vesting', super: true, admin: true, exec: false, view: false },
      { action: 'Cancelar bloqueos revocables', super: true, admin: false, exec: false, view: false },
      { action: 'Añadir/eliminar firmantes', super: true, admin: false, exec: false, view: false },
      { action: 'Cambiar el umbral', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Buena Práctica: Asignación de Roles',
    bestPractice: [
      'Limita SuperAdmin a 1-2 personas de confianza (fundadores, directivos)',
      'Usa Admin para los miembros del equipo financiero que gestionan las operaciones diarias',
      'Usa Executor para miembros del consejo que solo aprueban, no inician',
      'Usa Viewer para partes interesadas, auditores o transparencia pública',
    ],
  },

  locks: {
    heading: 'Bloqueos Temporales y Vesting',
    intro: 'Controla cuándo los tokens quedan disponibles. Ya sea que necesites custodia, pagos programados o vesting de tokens para empleados, lo tenemos cubierto.',
    timeLockTitle: 'Bloqueos Temporales',
    timeLockDesc: 'Bloquea tokens hasta una fecha concreta. El beneficiario puede reclamar el **importe completo** solo después de que pase la hora de desbloqueo. Antes de esa fecha, los tokens son completamente inaccesibles.',
    timeLockExampleLabel: 'Ejemplo: Depósito en Custodia',
    timeLockExampleAmount: '10.000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Custodia', desc: 'Retén fondos hasta que se cumplan las condiciones' },
      { icon: '🎯', title: 'Pagos por Hitos', desc: 'Libera cuando el entregable esté completo' },
      { icon: '🏦', title: 'Metas de Ahorro', desc: 'Evita retiros impulsivos' },
    ],
    vestingTitle: 'Calendarios de Vesting',
    vestingDesc: 'Libera tokens **gradualmente con el tiempo** con un periodo de cliff opcional. Es el estándar del sector para la compensación de empleados y las asignaciones a inversores.',
    vestingExampleLabel: 'Ejemplo: Vesting de Empleado a 4 Años con Cliff de 1 Año',
    vestingExampleAmount: '100.000 tokens',
    vestingBarCliff: 'Cliff (1 año)',
    vestingBarLinear: 'Vesting Lineal → 100%',
    vestingTimeline: { start: 'Inicio', cliff: 'Cliff: se desbloquea el 25%', y2: 'Año 2: 50%', y3: 'Año 3: 75%', y4: 'Año 4: 100%' },
    howVestingTitle: 'Cómo Funciona el Vesting',
    howVestingSteps: [
      { title: 'Periodo de Cliff:', desc: 'No se libera nada hasta la fecha del cliff. Si alguien se va antes del cliff, no recibe nada.' },
      { title: 'Desbloqueo del Cliff:', desc: 'En la fecha del cliff, una parte se desbloquea de inmediato (normalmente el 25% para un calendario de 4 años).' },
      { title: 'Vesting Lineal:', desc: 'Tras el cliff, los tokens se liberan de forma continua hasta la fecha de finalización.' },
      { title: 'Reclama Cuando Quieras:', desc: 'Los beneficiarios pueden reclamar sus tokens adquiridos cuando deseen, sin plazos.' },
    ],
    revTitle: 'Revocable vs. No Revocable',
    revocable: { title: '✓ Revocable', desc: 'El SuperAdmin puede cancelar el bloqueo y devolver los tokens no adquiridos al vault.', bestFor: 'Ideal para: Vesting de empleados (con cláusula de finalización), subvenciones condicionales, asignaciones internas' },
    nonRevocable: { title: '✗ No Revocable', desc: 'No se puede cancelar una vez creado. Los tokens están garantizados al beneficiario pase lo que pase.', bestFor: 'Ideal para: Asignaciones a inversores, subvenciones irrevocables, custodia sin confianza, tokens de asesores' },
    bulkTitle: 'Creación Masiva',
    bulkDesc: '¿Necesitas crear muchos bloqueos a la vez? Usa la función de carga masiva con un archivo CSV. Perfecto para distribuciones de tokens de equipo, nóminas o programas de subvenciones.',
    bulkPrepLabel: 'Simplemente prepara una hoja de cálculo con:',
    bulkFields: [
      'Dirección de billetera del beneficiario',
      'Cantidad de tokens',
      'Fecha de desbloqueo (para bloqueos temporales) o parámetros de vesting',
      'Si es revocable',
      'Descripción opcional',
    ],
    bulkNote: 'Sube el CSV, revisa las entradas y crea hasta 10 bloqueos por lote.',
  },

  tokens: {
    heading: 'Tokens Compatibles',
    usdcTitle: 'USDC Nativo en Stellar',
    usdcSubtitle: 'La stablecoin oficial de Circle — no envuelta, no puenteada',
    usdcDesc: 'Orion Safe ofrece soporte de primera clase para USDC. Crea vaults denominados en dólares, configura vesting de salarios en moneda estable o bloquea fondos en custodia sin riesgo de volatilidad.',
    allTitle: 'Todos los Activos Compatibles',
    allIntro: 'Orion Safe admite **cualquier token de la red Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'El token nativo de Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin del dólar estadounidense' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin del euro' },
      { emoji: '🪙', name: 'Cualquier Token', desc: 'Activos personalizados de Stellar' },
    ],
    whatTitle: 'Qué Puedes Hacer Con los Tokens',
    whatItems: [
      { icon: '💸', title: 'Transferencias Multifirma', desc: 'Envía cualquier token con aprobación multifirma' },
      { icon: '🔒', title: 'Bloquea Cualquier Activo', desc: 'Bloquea USDC, XLM o tokens personalizados hasta una fecha concreta' },
      { icon: '📈', title: 'Vesting de Tokens', desc: 'Crea calendarios de vesting para cualquier activo de Stellar' },
      { icon: '📊', title: 'Distribuciones Masivas', desc: 'Distribuye tokens a múltiples destinatarios mediante CSV' },
    ],
    testTitle: 'Cómo Obtener Tokens de Testnet',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Ve a {{laboratory}}',
      'Introduce la dirección de tu billetera de testnet',
      'Haz clic en "Fund account with Friendbot"',
      '¡Recibe 10.000 XLM de prueba al instante!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Añade la línea de confianza de USDC en tu billetera (Freighter → Manage Assets → Add USDC)',
      'Usa un faucet de USDC de testnet o intercambia XLM en el DEX de testnet',
    ],
  },

  architecture: {
    heading: 'Cómo Funciona',
    intro: 'Una explicación sencilla de lo que ocurre entre bastidores cuando usas Orion Safe.',
    basicsTitle: 'Lo Básico',
    basicsParas: [
      'Cuando creas un vault, Orion Safe despliega un **contrato inteligente** en la blockchain de Stellar. Este contrato inteligente es como una caja de seguridad programable que custodia tus activos.',
      'El contrato inteligente impone todas las reglas: quién puede proponer transacciones, cuántas aprobaciones se necesitan, cuándo se pueden liberar los tokens bloqueados y más. **Nadie puede saltarse estas reglas** — ni siquiera el equipo de Orion Safe.',
    ],
    flowTitle: 'Qué Ocurre Cuando Envías Tokens',
    flowSteps: [
      { title: 'Creas una Propuesta', desc: 'Especifica el destinatario, el importe y un memo opcional. La propuesta se registra en la blockchain.' },
      { title: 'Otros Firmantes Aprueban', desc: 'Cada aprobación se registra en la cadena. Todos pueden ver quién ha aprobado.' },
      { title: 'Umbral Alcanzado', desc: 'Una vez que suficientes firmantes aprueban (p. ej., 2 de 3), la transacción está lista para ejecutarse.' },
      { title: 'Ejecutar y Confirmar', desc: 'Cualquiera puede activar la ejecución. Los tokens se mueven al instante (~5 segundos). ¡Listo!' },
    ],
    whyTitle: 'Por Qué Construimos sobre Stellar',
    whyItems: [
      { icon: '⚡', title: 'Rápido', desc: 'Las transacciones se confirman en ~5 segundos' },
      { icon: '💰', title: 'Económico', desc: 'Menos de $0.0001 por transacción' },
      { icon: '🏦', title: 'Confiable', desc: 'Usado por Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Seguro', desc: 'Red probada en batalla desde 2015' },
      { icon: '💵', title: 'USDC Nativo', desc: 'Stablecoins reales, no tokens envueltos' },
      { icon: '🌍', title: 'Global', desc: 'Funciona en cualquier lugar con acceso a internet' },
    ],
    truthTitle: 'Importante: La Blockchain es la Fuente de Verdad',
    truthDesc: 'Tu vault existe en la blockchain de Stellar, no en nuestros servidores. Aunque nuestro sitio web se cayera, tu vault y tus fondos seguirían seguros y accesibles a través de otras herramientas de Stellar. Simplemente proporcionamos una interfaz fácil de usar para interactuar con tu vault en la cadena.',
  },

  security: {
    heading: 'Seguridad',
    intro: 'Cómo Orion Safe mantiene tus activos seguros.',
    principlesTitle: 'Principios Fundamentales de Seguridad',
    principles: [
      { title: 'Cumplimiento en la Cadena', desc: 'Todas las reglas las impone el contrato inteligente en la blockchain. El sitio web es solo una interfaz de usuario — la blockchain es la autoridad.' },
      { title: 'Sin Puertas Traseras', desc: 'Nadie — ni siquiera el equipo de Orion Safe — puede acceder a tu vault ni mover tus fondos sin las firmas adecuadas.' },
      { title: 'Multifirma por Defecto', desc: 'Aunque una clave se vea comprometida, los atacantes no pueden mover fondos sin alcanzar tu umbral de aprobación.' },
    ],
    threatsTitle: 'Cómo Protegemos Contra las Amenazas',
    threats: [
      { threat: 'Clave de firmante comprometida', mitigation: 'El umbral multifirma evita ataques con una sola clave. Otros firmantes pueden eliminar la clave comprometida.' },
      { threat: 'Propuesta maliciosa', mitigation: 'Requiere múltiples aprobaciones. Otros firmantes pueden rechazar propuestas dañinas.' },
      { threat: 'Claves perdidas', mitigation: 'Mientras los firmantes restantes alcancen el umbral, el vault sigue accesible.' },
      { threat: 'El sitio web deja de funcionar', mitigation: 'Tu vault existe en la blockchain. Accede a él mediante otras herramientas de Stellar.' },
      { threat: 'Brecha en la base de datos', mitigation: 'Nuestra base de datos es solo una caché para cargar más rápido. La blockchain es la fuente de verdad.' },
    ],
    bestTitle: 'Buenas Prácticas de Seguridad',
    doTitle: '✓ Haz',
    dos: [
      'Usa billeteras de hardware (como Ledger) para las claves de los firmantes',
      'Mantén el umbral en 2 o más (nunca un solo firmante)',
      'Revisa periódicamente tu lista de firmantes',
      'Usa vaults separados para distintos propósitos',
      'Prueba primero con cantidades pequeñas',
      'Respalda tus frases de recuperación de forma segura',
    ],
    dontTitle: '✗ No Hagas',
    donts: [
      'Compartir claves privadas por correo o chat',
      'Usar la misma clave para varios vaults críticos',
      'Ignorar propuestas pendientes durante demasiado tiempo',
      'Establecer el umbral igual al total de firmantes (sin redundancia)',
      'Almacenar frases de recuperación digitalmente sin cifrar',
      'Dar acceso de SuperAdmin a personas en las que no confías plenamente',
    ],
    statusTitle: 'Estado de Seguridad',
    statuses: [
      { color: 'green', text: 'Construido sobre la red Stellar probada en batalla (desde 2015)' },
      { color: 'green', text: 'Integración del framework Smart Account de OpenZeppelin' },
      { color: 'yellow', text: 'Auditoría de seguridad profesional prevista antes de la mainnet (Q4 2026)' },
      { color: 'gray', text: 'Programa de recompensas por errores tras el lanzamiento en mainnet' },
    ],
  },

  roadmap: {
    heading: 'Hoja de Ruta',
    liveTitle: 'Actualmente en Vivo en la Testnet',
    liveFeatures: ['Vaults multifirma', 'Acceso basado en roles', 'Bloqueos temporales', 'Calendarios de vesting', 'Importación masiva por CSV', 'Enlaces de vista pública', 'Portal de reclamos', 'Soporte multibilletera'],
    phases: [
      { color: 'purple', title: 'Fase 1: Preparación para Producción', target: 'Objetivo: Julio 2026', items: ['Preparación del despliegue en mainnet', 'Refuerzo y pruebas de seguridad', 'Optimización del rendimiento', 'Mejor manejo de errores'] },
      { color: 'blue', title: 'Fase 2: Funciones Avanzadas', target: 'Objetivo: Septiembre 2026', items: ['Límites de gasto (topes diarios/semanales/mensuales)', 'Plantillas de vesting mejoradas', 'Opciones avanzadas de propuestas', 'Experiencia móvil mejorada'] },
      { color: 'cyan', title: 'Fase 3: Lanzamiento en Mainnet', target: 'Objetivo: Noviembre 2026', items: ['Auditoría de seguridad profesional', 'Integración con el DEX de Stellar (trading dentro del vault)', 'SDK para desarrolladores', 'Guías y tutoriales completos para usuarios', '🚀 **Despliegue en mainnet**'] },
    ],
    futureTitle: 'Visión de Futuro (2027+)',
    future: [
      { title: 'Integración DeFi', desc: 'Estrategias de rendimiento, protocolos de préstamo, provisión de liquidez' },
      { title: 'Suite Empresarial', desc: 'Opciones de marca blanca, SSO, informes de cumplimiento' },
      { title: 'Automatización', desc: 'Pagos recurrentes programados, condiciones inteligentes' },
      { title: 'Integraciones', desc: 'API, webhooks, conexiones con software de contabilidad' },
    ],
    followTitle: 'Sigue Nuestro Progreso',
    followDesc: 'Estamos construyendo en público. Sigue nuestro repositorio de GitHub para ver actualizaciones, o vuelve aquí para conocer las últimas novedades.',
  },

  faq: {
    heading: 'Preguntas Frecuentes',
    items: [
      { q: '¿Orion Safe es gratis?', a: '¡Sí! La plataforma es gratuita. Solo pagas las tarifas estándar de la red Stellar (menos de $0.0001 por transacción) más un pequeño depósito único al crear un vault.' },
      { q: '¿Qué pasa si pierdo mi clave privada?', a: 'Mientras los firmantes restantes alcancen el umbral de aprobación, el vault sigue siendo totalmente accesible. Por ejemplo, en un vault 2-de-3, si se pierde una clave, los otros 2 firmantes aún pueden operar el vault e incluso añadir un firmante de reemplazo.' },
      { q: '¿El equipo de Orion Safe puede acceder a mis fondos?', a: 'No. Tu vault es un contrato inteligente en la blockchain de Stellar. Solo los firmantes que añadas pueden autorizar transacciones. No tenemos acceso especial, puertas traseras ni claves de administrador a tu vault.' },
      { q: '¿Qué tokens puedo almacenar?', a: 'Cualquier activo de Stellar: XLM (nativo), USDC, EURC y miles de otros tokens emitidos en la red Stellar.' },
      { q: '¿Qué tan rápidas son las transacciones?', a: 'Alrededor de 5 segundos tras la ejecución. El proceso de aprobación depende de la rapidez con la que respondan tus firmantes.' },
      { q: '¿Puedo cancelar un bloqueo temporal o un calendario de vesting?', a: 'Solo si se creó como "revocable". Los bloqueos no revocables no se pueden cancelar una vez creados — los tokens están garantizados al beneficiario.' },
      { q: '¿Hay una aplicación móvil?', a: 'El panel es totalmente responsive y funciona muy bien en navegadores móviles. Úsalo con billeteras móviles como Lobstr o conéctate mediante WalletConnect.' },
      { q: '¿Qué pasa si el sitio web deja de funcionar?', a: 'Tu vault existe en la blockchain de Stellar, no en nuestros servidores. Puedes interactuar con él usando el Stellar Laboratory o cualquier herramienta compatible, incluso si nuestro sitio web no está disponible.' },
      { q: '¿Cómo reclaman sus tokens los beneficiarios?', a: 'Comparte un enlace de reclamo con ellos (en Ajustes → Compartir). Conectan su propia billetera y reclaman directamente, sin necesidad de acceso al vault.' },
      { q: '¿Hay un límite en el número de firmantes?', a: 'Actualmente admite hasta 10 firmantes por vault. ¿Necesitas más? Contáctanos para soluciones empresariales.' },
      { q: '¿Cuál es la diferencia entre testnet y mainnet?', a: 'La testnet usa tokens falsos para pruebas — sin valor real. La mainnet usa tokens reales y dinero real. Actualmente estamos en testnet, con el lanzamiento en mainnet previsto para el Q4 2026.' },
      { q: '¿Cómo obtengo ayuda si algo sale mal?', a: 'Consulta primero esta documentación. Si aún necesitas ayuda, abre un issue en nuestro repositorio de GitHub o contáctanos por nuestros canales.' },
    ],
  },

  common: {
    locked: '🔒 Bloqueado',
    claimable: '✓ Reclamable',
    today: 'Hoy',
    unlockDate: '⏰ Fecha de Desbloqueo',
    claimed: 'Reclamado',
    viewOnGithub: 'Ver en GitHub',
  },
};
