import { DocsContent } from './types';

export const docsFr: DocsContent = {
  sidebarTitle: 'Documentation',
  sections: [
    { id: 'overview', title: 'Présentation', description: "Qu'est-ce qu'Orion Safe ?" },
    { id: 'quickstart', title: 'Démarrage rapide', description: 'Guide en 5 minutes' },
    { id: 'features', title: 'Fonctionnalités', description: 'Ce que vous pouvez faire' },
    { id: 'roles', title: 'Rôles et permissions', description: 'Qui peut faire quoi' },
    { id: 'locks', title: 'Verrous & acquisition', description: 'Programmer les libérations' },
    { id: 'tokens', title: 'Jetons pris en charge', description: 'USDC, XLM et plus' },
    { id: 'architecture', title: 'Fonctionnement', description: 'Sous le capot' },
    { id: 'security', title: 'Sécurité', description: 'Comment on vous protège' },
    { id: 'faq', title: 'FAQ', description: 'Questions courantes' },
    { id: 'roadmap', title: 'Feuille de route', description: 'À venir' },
  ],

  overview: {
    heading: 'Bienvenue sur Orion Safe',
    intro:
      'Orion Safe est une **plateforme de trésorerie multi-signatures** construite sur Stellar. ' +
      "Voyez-la comme un compte bancaire partagé pour votre équipe, DAO ou organisation — mais avec des super-pouvoirs.",
    whyTitle: 'Pourquoi utiliser Orion Safe ?',
    whyItems: [
      { emoji: '🔐', title: 'Aucun point de défaillance unique', desc: 'Plusieurs approbations requises — même si une clé est compromise, les fonds restent en sécurité' },
      { emoji: '⚡', title: 'Ultra rapide et économique', desc: 'Transactions en ~5 secondes, moins de 0,0001 $ par transaction' },
      { emoji: '⏰', title: 'Contrôles temporels', desc: "Verrouillez les jetons jusqu'à une date, ou libérez-les progressivement" },
      { emoji: '🌍', title: 'Transparence totale', desc: 'Chaque action enregistrée on-chain — partagez des liens en lecture seule' },
    ],
    perfectForTitle: 'Idéal pour',
    perfectFor: [
      { icon: '🏛️', title: 'DAO & trésoreries', desc: 'Gérez les fonds communautaires avec une gouvernance multi-sig transparente' },
      { icon: '👥', title: 'Équipes & startups', desc: "Sécurisez la trésorerie de l'entreprise avec un accès par rôle" },
      { icon: '💼', title: 'Acquisition employés', desc: "Acquisition sur 4 ans avec cliff d'1 an, entièrement automatisée" },
      { icon: '🤝', title: "Services d'entiercement", desc: 'Accord mutuel 2-sur-2 pour des transactions sécurisées' },
      { icon: '🎁', title: 'Subventions & paie', desc: 'Distributions en masse avec libérations programmées' },
      { icon: '📊', title: "Fonds d'investissement", desc: 'Approbation par comité pour la gestion de fonds' },
    ],
    liveTitle: 'En ligne sur le testnet Stellar',
    liveDesc:
      "Orion Safe est actuellement en ligne sur le testnet Stellar. Essayez-le dès maintenant avec des jetons de test ! " +
      'Lancement mainnet prévu au T4 2026 après audit de sécurité.',
  },

  quickstart: {
    heading: 'Guide de démarrage rapide',
    subtitle: 'Lancez votre premier coffre en moins de 5 minutes.',
    step1Title: 'Connectez votre portefeuille',
    step1Intro: 'Cliquez sur **« Connecter le portefeuille »** en haut à droite et choisissez votre portefeuille :',
    wallets: [
      { name: 'Freighter', note: 'Recommandé' },
      { name: 'Lobstr', note: 'Adapté mobile' },
      { name: 'xBull', note: 'Utilisateurs avancés' },
      { name: 'Albedo', note: 'Sur navigateur' },
    ],
    noWalletTitle: "Vous n'avez pas de portefeuille ?",
    noWalletDesc: 'Installez {{freighter}} — une extension de navigateur gratuite qui se configure en 2 minutes.',
    step2Title: 'Créez votre coffre',
    step2Items: [
      'Cliquez sur **« Créer un coffre »**',
      'Donnez un nom à votre coffre (ex. « Trésorerie équipe »)',
      'Ajoutez les adresses des signataires (les personnes qui peuvent approuver)',
      'Définissez votre **seuil** — le nombre d\'approbations nécessaires',
    ],
    exampleLabel: 'Exemple : multi-sig 2-sur-3',
    approvedLabel: '2/3 = Approuvé !',
    step3Title: 'Approvisionnez votre coffre',
    step3Intro: 'Votre coffre a sa propre adresse. Envoyez-y des jetons comme à tout portefeuille Stellar :',
    step3Items: [
      "Copiez l'adresse de votre coffre depuis le tableau de bord",
      "Envoyez du XLM, de l'USDC ou tout jeton Stellar à cette adresse",
      'Les fonds apparaissent en ~5 secondes',
    ],
    proTipTitle: 'Astuce',
    proTipDesc: 'Pour le testnet, obtenez du XLM de test gratuit via le {{friendbot}}.',
    step4Title: 'Effectuez votre première transaction',
    step4Steps: [
      { title: 'Créer une proposition', desc: 'Transactions → Nouvelle → Saisir les détails → Soumettre' },
      { title: 'Collecter les approbations', desc: 'Les autres signataires examinent et cliquent sur « Approuver »' },
      { title: 'Exécuter', desc: 'Une fois le seuil atteint, n\'importe qui peut cliquer sur « Exécuter »' },
    ],
    doneTitle: "🎉 C'est tout !",
    doneDesc:
      "Vous disposez maintenant d'un coffre multi-sig sécurisé. Explorez la barre latérale pour découvrir les verrous temporels, " +
      "les calendriers d'acquisition et d'autres fonctionnalités avancées.",
  },

  features: {
    heading: 'Fonctionnalités',
    multiSig: {
      title: 'Sécurité multi-signatures',
      desc: "Exigez l'approbation de plusieurs personnes pour les transactions. Vous choisissez le seuil — du 2-sur-3 pour une petite équipe au 5-sur-9 pour une grande DAO.",
      configs: ['2-sur-3', '3-sur-5', '4-sur-7', '5-sur-9'],
    },
    proposal: {
      title: 'Flux par propositions',
      desc: 'Toutes les transactions passent par un processus de proposition transparent. Aucune surprise, responsabilité totale.',
      steps: [
        { title: 'Proposer', sub: 'Tout signataire' },
        { title: 'Approuver', sub: 'Atteindre le seuil' },
        { title: 'Exécuter', sub: "N'importe qui" },
      ],
    },
    txTypes: {
      title: 'Types de transactions',
      items: [
        { icon: '💸', title: 'Transfert', desc: "Envoi de jetons immédiatement après approbation. Paiements simples et directs." },
        { icon: '🔒', title: 'Verrou temporel', desc: "Verrouillez les jetons jusqu'à une date précise. Idéal pour l'entiercement ou les libérations programmées." },
        { icon: '📈', title: 'Acquisition', desc: 'Libération progressive avec cliff optionnel. Idéal pour les jetons des employés.' },
      ],
    },
    dashboard: {
      title: 'Navigation du tableau de bord',
      views: [
        { name: 'Tableau de bord', desc: "Vue d'ensemble & stats" },
        { name: 'Actifs', desc: 'Soldes des jetons' },
        { name: 'Transactions', desc: 'Propositions & historique' },
        { name: 'Membres', desc: 'Signataires & rôles' },
        { name: 'Verrous temporels', desc: 'Libérations programmées' },
        { name: 'Acquisition', desc: 'Acquisition de jetons' },
        { name: 'Contacts', desc: 'Carnet d\'adresses' },
        { name: 'Paramètres', desc: 'Configuration' },
      ],
    },
    publicAccess: {
      title: 'Accès public & partage',
      cards: [
        { title: '🔗 Lien en lecture seule', desc: 'Partagez une vue en lecture seule avec des investisseurs, auditeurs ou le public. Ils voient les soldes et l\'activité mais ne peuvent rien faire.' },
        { title: '🎁 Lien de réclamation', desc: 'Les bénéficiaires réclament leurs jetons verrouillés ou acquis directement avec leur propre portefeuille — aucun accès au coffre requis.' },
      ],
    },
  },

  roles: {
    heading: 'Rôles et permissions',
    intro: "Orion Safe utilise un système basé sur les rôles pour contrôler qui peut faire quoi. Cela offre de la flexibilité tout en maintenant la sécurité.",
    cards: [
      { name: 'SuperAdmin', badge: 'Contrôle total', desc: "Contrôle complet du coffre. Les SuperAdmins peuvent tout faire, y compris les actions affectant la structure et la sécurité du coffre.", canLabel: 'Peut :', can: 'Ajouter/retirer des signataires, modifier le seuil d\'approbation, annuler tout verrou révocable, mettre à jour les paramètres du coffre, plus tout ce que peuvent faire les Admins et Exécuteurs.' },
      { name: 'Admin', badge: 'Opérations', desc: "Gestionnaire des opérations quotidiennes. Les Admins gèrent la plupart des activités de trésorerie mais ne peuvent pas modifier les paramètres de sécurité du coffre.", canLabel: 'Peut :', can: "Créer des propositions, approuver des transactions, exécuter les transactions approuvées, créer des verrous temporels et calendriers d'acquisition, gérer les contacts." },
      { name: 'Executor', badge: 'Approuver & exécuter', desc: "Autorité d'approbation. Les Exécuteurs peuvent voter sur les propositions et exécuter les transactions approuvées, mais ne peuvent pas en initier de nouvelles.", canLabel: 'Peut :', can: 'Approuver ou rejeter des propositions, exécuter les transactions ayant atteint le seuil.' },
      { name: 'Viewer', badge: 'Lecture seule', desc: "Accès observateur. Les Viewers voient tout mais ne peuvent rien faire. Parfait pour les auditeurs ou parties prenantes.", canLabel: 'Peut :', can: "Consulter les soldes du coffre, l'historique des transactions, les propositions, les verrous et toute l'activité." },
    ],
    matrixTitle: 'Résumé des permissions',
    matrixHeaders: { action: 'Action', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Voir le coffre & les soldes', super: true, admin: true, exec: true, view: true },
      { action: 'Créer des propositions', super: true, admin: true, exec: false, view: false },
      { action: 'Approuver des propositions', super: true, admin: true, exec: true, view: false },
      { action: 'Exécuter des transactions', super: true, admin: true, exec: true, view: false },
      { action: 'Créer verrous / acquisitions', super: true, admin: true, exec: false, view: false },
      { action: 'Annuler des verrous révocables', super: true, admin: false, exec: false, view: false },
      { action: 'Ajouter/retirer des signataires', super: true, admin: false, exec: false, view: false },
      { action: 'Modifier le seuil', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Bonne pratique : attribution des rôles',
    bestPractice: [
      'Limitez SuperAdmin à 1-2 personnes de confiance (fondateurs, dirigeants)',
      'Utilisez Admin pour les membres de l\'équipe finance gérant le quotidien',
      'Utilisez Executor pour les membres du conseil qui approuvent seulement',
      'Utilisez Viewer pour les parties prenantes, auditeurs ou la transparence publique',
    ],
  },

  locks: {
    heading: 'Verrous & acquisition',
    intro: "Contrôlez quand les jetons deviennent disponibles. Entiercement, paiements programmés ou acquisition de jetons employés — nous avons ce qu'il vous faut.",
    timeLockTitle: 'Verrous temporels',
    timeLockDesc: "Verrouillez des jetons jusqu'à une date précise. Le bénéficiaire ne peut réclamer le **montant total** qu'après le passage de la date de déverrouillage. Avant cette date, les jetons sont totalement inaccessibles.",
    timeLockExampleLabel: "Exemple : dépôt d'entiercement",
    timeLockExampleAmount: '10 000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Entiercement', desc: 'Conserver les fonds jusqu\'au respect des conditions' },
      { icon: '🎯', title: 'Paiements par jalon', desc: 'Libérer une fois le livrable terminé' },
      { icon: '🏦', title: "Objectifs d'épargne", desc: 'Empêcher les retraits impulsifs' },
    ],
    vestingTitle: "Calendriers d'acquisition",
    vestingDesc: "Libérez les jetons **progressivement dans le temps** avec une période de cliff optionnelle. C'est le standard de l'industrie pour la rémunération des employés et les allocations aux investisseurs.",
    vestingExampleLabel: "Exemple : acquisition employé sur 4 ans avec cliff d'1 an",
    vestingExampleAmount: '100 000 jetons',
    vestingBarCliff: 'Cliff (1 an)',
    vestingBarLinear: 'Acquisition linéaire → 100 %',
    vestingTimeline: { start: 'Début', cliff: 'Cliff : 25 % débloqués', y2: 'An 2 : 50 %', y3: 'An 3 : 75 %', y4: 'An 4 : 100 %' },
    howVestingTitle: "Comment fonctionne l'acquisition",
    howVestingSteps: [
      { title: 'Période de cliff :', desc: "Rien n'est acquis avant la date du cliff. Si quelqu'un part avant le cliff, il n'obtient rien." },
      { title: 'Déblocage au cliff :', desc: 'À la date du cliff, une portion se débloque immédiatement (typiquement 25 % pour un calendrier de 4 ans).' },
      { title: 'Acquisition linéaire :', desc: "Après le cliff, les jetons s'acquièrent en continu jusqu'à la date de fin." },
      { title: 'Réclamation à tout moment :', desc: "Les bénéficiaires réclament leurs jetons acquis quand ils le souhaitent — aucune échéance." },
    ],
    revTitle: 'Révocable vs non révocable',
    revocable: { title: '✓ Révocable', desc: 'Le SuperAdmin peut annuler le verrou et renvoyer les jetons non acquis au coffre.', bestFor: 'Idéal pour : acquisition employé (avec clause de résiliation), subventions conditionnelles, allocations internes' },
    nonRevocable: { title: '✗ Non révocable', desc: 'Impossible à annuler une fois créé. Les jetons sont garantis au bénéficiaire quoi qu\'il arrive.', bestFor: "Idéal pour : allocations investisseurs, subventions irrévocables, entiercement sans confiance, jetons conseillers" },
    bulkTitle: 'Création en masse',
    bulkDesc: 'Besoin de créer de nombreux verrous d\'un coup ? Utilisez l\'import en masse via un fichier CSV. Parfait pour les distributions de jetons d\'équipe, la paie ou les programmes de subventions.',
    bulkPrepLabel: 'Préparez simplement un tableur avec :',
    bulkFields: [
      'Adresse du portefeuille bénéficiaire',
      'Montant de jetons',
      'Date de déverrouillage (verrous) ou paramètres d\'acquisition',
      "S'il est révocable",
      'Description optionnelle',
    ],
    bulkNote: "Importez le CSV, vérifiez les entrées et créez jusqu'à 10 verrous par lot.",
  },

  tokens: {
    heading: 'Jetons pris en charge',
    usdcTitle: 'USDC natif sur Stellar',
    usdcSubtitle: 'Le stablecoin officiel de Circle — ni wrappé, ni bridgé',
    usdcDesc: "Orion Safe prend en charge l'USDC de manière native. Créez des coffres libellés en dollars, configurez une acquisition de salaire en monnaie stable, ou verrouillez des fonds d'entiercement sans risque de volatilité.",
    allTitle: 'Tous les actifs pris en charge',
    allIntro: 'Orion Safe prend en charge **tout jeton du réseau Stellar** :',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Le jeton natif de Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin dollar US' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin euro' },
      { emoji: '🪙', name: 'Tout jeton', desc: 'Actifs Stellar personnalisés' },
    ],
    whatTitle: 'Ce que vous pouvez faire avec les jetons',
    whatItems: [
      { icon: '💸', title: 'Transferts multi-sig', desc: 'Envoyer tout jeton avec approbation multi-signatures' },
      { icon: '🔒', title: 'Verrouiller tout actif', desc: "Verrouiller USDC, XLM ou jetons personnalisés jusqu'à une date" },
      { icon: '📈', title: 'Acquisition de jetons', desc: "Créer des calendriers d'acquisition pour tout actif Stellar" },
      { icon: '📊', title: 'Distributions en masse', desc: 'Distribuer des jetons à plusieurs destinataires via CSV' },
    ],
    testTitle: 'Obtenir des jetons de testnet',
    xlmTitle: '⭐ XLM (testnet)',
    xlmSteps: [
      'Rendez-vous sur {{laboratory}}',
      'Saisissez votre adresse de portefeuille testnet',
      'Cliquez sur « Fund account with Friendbot »',
      'Recevez 10 000 XLM de test instantanément !',
    ],
    usdcTestTitle: '💵 USDC (testnet)',
    usdcTestSteps: [
      'Ajoutez une trustline USDC dans votre portefeuille (Freighter → Gérer les actifs → Ajouter USDC)',
      'Utilisez un faucet USDC testnet ou échangez du XLM sur le DEX testnet',
    ],
  },

  architecture: {
    heading: 'Fonctionnement',
    intro: 'Une explication simple de ce qui se passe en coulisses lorsque vous utilisez Orion Safe.',
    basicsTitle: 'Les bases',
    basicsParas: [
      'Lorsque vous créez un coffre, Orion Safe déploie un **contrat intelligent** sur la blockchain Stellar. Ce contrat est comme un coffre-fort programmable qui détient vos actifs.',
      "Le contrat applique toutes les règles : qui peut proposer des transactions, combien d'approbations sont nécessaires, quand les jetons verrouillés peuvent être libérés, etc. **Personne ne peut contourner ces règles** — pas même l'équipe Orion Safe.",
    ],
    flowTitle: 'Ce qui se passe quand vous envoyez des jetons',
    flowSteps: [
      { title: 'Vous créez une proposition', desc: 'Indiquez le destinataire, le montant et un mémo optionnel. La proposition est enregistrée sur la blockchain.' },
      { title: 'Les autres signataires approuvent', desc: 'Chaque approbation est enregistrée on-chain. Tout le monde voit qui a approuvé.' },
      { title: 'Seuil atteint', desc: 'Une fois assez de signataires (ex. 2 sur 3), la transaction est prête à être exécutée.' },
      { title: 'Exécution & confirmation', desc: "N'importe qui peut déclencher l'exécution. Les jetons sont déplacés instantanément (~5 secondes). Terminé !" },
    ],
    whyTitle: 'Pourquoi nous avons choisi Stellar',
    whyItems: [
      { icon: '⚡', title: 'Rapide', desc: 'Transactions confirmées en ~5 secondes' },
      { icon: '💰', title: 'Économique', desc: 'Moins de 0,0001 $ par transaction' },
      { icon: '🏦', title: 'Fiable', desc: 'Utilisé par Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Sécurisé', desc: 'Réseau éprouvé depuis 2015' },
      { icon: '💵', title: 'USDC natif', desc: 'De vrais stablecoins, pas des jetons wrappés' },
      { icon: '🌍', title: 'Mondial', desc: 'Fonctionne partout avec une connexion internet' },
    ],
    truthTitle: 'Important : la blockchain fait foi',
    truthDesc: "Votre coffre existe sur la blockchain Stellar, pas sur nos serveurs. Même si notre site était hors ligne, votre coffre et vos fonds resteraient en sécurité et accessibles via d'autres outils Stellar. Nous fournissons simplement une interface conviviale pour interagir avec votre coffre on-chain.",
  },

  security: {
    heading: 'Sécurité',
    intro: 'Comment Orion Safe protège vos actifs.',
    principlesTitle: 'Principes de sécurité fondamentaux',
    principles: [
      { title: 'Application on-chain', desc: "Toutes les règles sont appliquées par le contrat intelligent sur la blockchain. Le site n'est qu'une interface — la blockchain fait autorité." },
      { title: 'Aucune porte dérobée', desc: "Personne — pas même l'équipe Orion Safe — ne peut accéder à votre coffre ou déplacer vos fonds sans les signatures appropriées." },
      { title: 'Multi-sig par défaut', desc: "Même si une clé est compromise, les attaquants ne peuvent pas déplacer les fonds sans atteindre votre seuil d'approbation." },
    ],
    threatsTitle: 'Comment nous protégeons contre les menaces',
    threats: [
      { threat: 'Clé de signataire compromise', mitigation: 'Le seuil multi-sig empêche les attaques par clé unique. Les autres signataires peuvent retirer la clé compromise.' },
      { threat: 'Proposition malveillante', mitigation: 'Nécessite plusieurs approbations. Les autres signataires peuvent rejeter les mauvaises propositions.' },
      { threat: 'Clés perdues', mitigation: 'Tant que les signataires restants atteignent le seuil, le coffre reste accessible.' },
      { threat: 'Site hors ligne', mitigation: "Votre coffre existe sur la blockchain. Accédez-y via d'autres outils Stellar." },
      { threat: 'Fuite de base de données', mitigation: 'Notre base de données n\'est qu\'un cache pour un chargement plus rapide. La blockchain fait foi.' },
    ],
    bestTitle: 'Bonnes pratiques de sécurité',
    doTitle: '✓ À faire',
    dos: [
      'Utiliser des portefeuilles matériels (comme Ledger) pour les clés de signataires',
      'Garder le seuil à 2 ou plus (jamais un seul signataire)',
      'Revoir régulièrement votre liste de signataires',
      'Utiliser des coffres séparés pour des usages différents',
      'Tester d\'abord avec de petits montants',
      'Sauvegarder vos phrases de récupération en sécurité',
    ],
    dontTitle: '✗ À éviter',
    donts: [
      'Partager des clés privées par e-mail ou chat',
      'Utiliser la même clé pour plusieurs coffres critiques',
      'Ignorer trop longtemps les propositions en attente',
      'Fixer le seuil égal au nombre total de signataires (aucune redondance)',
      'Stocker les phrases de récupération numériquement sans chiffrement',
      "Donner l'accès SuperAdmin à des personnes en qui vous n'avez pas pleine confiance",
    ],
    statusTitle: 'État de la sécurité',
    statuses: [
      { color: 'green', text: 'Bâti sur le réseau Stellar éprouvé (depuis 2015)' },
      { color: 'green', text: 'Intégration du framework Smart Account d\'OpenZeppelin' },
      { color: 'yellow', text: 'Audit de sécurité professionnel prévu avant le mainnet (T4 2026)' },
      { color: 'gray', text: 'Programme de bug bounty après le lancement mainnet' },
    ],
  },

  roadmap: {
    heading: 'Feuille de route',
    liveTitle: 'Actuellement en ligne sur le testnet',
    liveFeatures: ['Coffres multi-sig', 'Accès par rôle', 'Verrous temporels', "Calendriers d'acquisition", 'Import CSV en masse', 'Liens en lecture seule', 'Portail de réclamation', 'Support multi-portefeuilles'],
    phases: [
      { color: 'purple', title: 'Phase 1 : Préparation à la production', target: 'Objectif : juillet 2026', items: ['Préparation du déploiement mainnet', 'Renforcement et tests de sécurité', 'Optimisation des performances', 'Meilleure gestion des erreurs'] },
      { color: 'blue', title: 'Phase 2 : Fonctionnalités avancées', target: 'Objectif : septembre 2026', items: ['Limites de dépenses (plafonds quotidiens/hebdo/mensuels)', "Modèles d'acquisition améliorés", 'Options de proposition avancées', 'Expérience mobile améliorée'] },
      { color: 'cyan', title: 'Phase 3 : Lancement mainnet', target: 'Objectif : novembre 2026', items: ['Audit de sécurité professionnel', 'Intégration du DEX Stellar (trading intégré)', 'SDK développeur', "Guides utilisateurs et tutoriels complets", '🚀 **Déploiement mainnet**'] },
    ],
    futureTitle: 'Vision future (2027+)',
    future: [
      { title: 'Intégration DeFi', desc: 'Stratégies de rendement, protocoles de prêt, apport de liquidité' },
      { title: 'Suite entreprise', desc: 'Options marque blanche, SSO, reporting de conformité' },
      { title: 'Automatisation', desc: 'Paiements récurrents programmés, conditions intelligentes' },
      { title: 'Intégrations', desc: 'API, webhooks, connexions aux logiciels comptables' },
    ],
    followTitle: 'Suivez notre progression',
    followDesc: "Nous construisons en public. Surveillez notre dépôt GitHub pour les mises à jour, ou revenez ici pour les dernières nouvelles.",
  },

  faq: {
    heading: 'Questions fréquentes',
    items: [
      { q: "Orion Safe est-il gratuit ?", a: "Oui ! La plateforme est gratuite. Vous ne payez que les frais réseau Stellar standards (moins de 0,0001 $ par transaction) plus un petit dépôt unique à la création d'un coffre." },
      { q: 'Que se passe-t-il si je perds ma clé privée ?', a: "Tant que les signataires restants atteignent le seuil d'approbation, le coffre reste pleinement accessible. Par exemple, dans un coffre 2-sur-3, si une clé est perdue, les 2 autres signataires peuvent toujours opérer le coffre et même ajouter un signataire de remplacement." },
      { q: "L'équipe Orion Safe peut-elle accéder à mes fonds ?", a: "Non. Votre coffre est un contrat intelligent sur la blockchain Stellar. Seuls les signataires que vous ajoutez peuvent autoriser des transactions. Nous n'avons aucun accès spécial, porte dérobée ou clé d'administration." },
      { q: 'Quels jetons puis-je stocker ?', a: 'Tout actif Stellar : XLM (natif), USDC, EURC et des milliers d\'autres jetons émis sur le réseau Stellar.' },
      { q: 'Quelle est la vitesse des transactions ?', a: "Environ 5 secondes après exécution. Le processus d'approbation dépend de la rapidité de réponse de vos signataires." },
      { q: "Puis-je annuler un verrou temporel ou un calendrier d'acquisition ?", a: "Uniquement s'il a été créé comme « révocable ». Les verrous non révocables ne peuvent pas être annulés une fois créés — les jetons sont garantis au bénéficiaire." },
      { q: 'Existe-t-il une application mobile ?', a: 'Le tableau de bord est entièrement responsive et fonctionne très bien sur navigateurs mobiles. Utilisez-le avec des portefeuilles mobiles comme Lobstr ou via WalletConnect.' },
      { q: 'Que se passe-t-il si le site tombe en panne ?', a: "Votre coffre existe sur la blockchain Stellar, pas sur nos serveurs. Vous pouvez interagir avec lui via le Stellar Laboratory ou tout outil compatible, même si notre site est indisponible." },
      { q: 'Comment les bénéficiaires réclament-ils leurs jetons ?', a: 'Partagez-leur un lien de réclamation (dans Paramètres → Partager). Ils connectent leur propre portefeuille et réclament directement — aucun accès au coffre requis.' },
      { q: 'Y a-t-il une limite au nombre de signataires ?', a: "Actuellement jusqu'à 10 signataires par coffre. Besoin de plus ? Contactez-nous pour des solutions entreprise." },
      { q: 'Quelle est la différence entre testnet et mainnet ?', a: "Le testnet utilise des jetons fictifs pour les tests — sans valeur réelle. Le mainnet utilise de vrais jetons et de l'argent réel. Nous sommes actuellement sur testnet, lancement mainnet prévu au T4 2026." },
      { q: "Comment obtenir de l'aide en cas de problème ?", a: "Consultez d'abord cette documentation. Si vous avez encore besoin d'aide, ouvrez une issue sur notre dépôt GitHub ou contactez-nous via nos canaux." },
    ],
  },

  common: {
    locked: '🔒 Verrouillé',
    claimable: '✓ Réclamable',
    today: "Aujourd'hui",
    unlockDate: '⏰ Date de déverrouillage',
    claimed: 'Réclamé',
    viewOnGithub: 'Voir sur GitHub',
  },
};
