import { DocsContent } from './types';

export const docsIt: DocsContent = {
  sidebarTitle: 'Documentazione',
  sections: [
    { id: 'overview', title: 'Panoramica', description: "Cos'è Orion Safe?" },
    { id: 'quickstart', title: 'Avvio Rapido', description: 'Guida alla configurazione in 5 minuti' },
    { id: 'features', title: 'Funzionalità Principali', description: 'Cosa puoi fare' },
    { id: 'roles', title: 'Ruoli e Permessi', description: 'Chi può fare cosa' },
    { id: 'locks', title: 'Blocchi Temporali e Vesting', description: 'Pianifica i rilasci di token' },
    { id: 'tokens', title: 'Token Supportati', description: 'USDC, XLM e altro' },
    { id: 'architecture', title: 'Come Funziona', description: 'Dietro le quinte' },
    { id: 'security', title: 'Sicurezza', description: 'Come ti proteggiamo' },
    { id: 'faq', title: 'FAQ', description: 'Domande frequenti' },
    { id: 'roadmap', title: 'Roadmap', description: 'Cosa arriverà' },
  ],

  overview: {
    heading: 'Benvenuto su Orion Safe',
    intro:
      'Orion Safe è una **piattaforma di tesoreria multifirma** costruita su Stellar. ' +
      'Pensala come un conto bancario condiviso per il tuo team, la tua DAO o organizzazione, ma con superpoteri.',
    whyTitle: 'Perché usare Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Nessun Punto Singolo di Guasto', desc: 'Sono richieste più approvazioni — anche se una chiave viene compromessa, i fondi restano al sicuro' },
      { emoji: '⚡', title: 'Velocissimo ed Economico', desc: 'Transazioni in ~5 secondi, meno di $0,0001 a transazione' },
      { emoji: '⏰', title: 'Controlli Basati sul Tempo', desc: 'Blocca i token fino a una data, o rilasciali gradualmente nel tempo' },
      { emoji: '🌍', title: 'Piena Trasparenza', desc: 'Ogni azione registrata on-chain — condividi link in sola lettura con chiunque' },
    ],
    perfectForTitle: 'Perfetto Per',
    perfectFor: [
      { icon: '🏛️', title: 'DAO e Tesorerie', desc: 'Gestisci fondi comunitari con una governance multifirma trasparente' },
      { icon: '👥', title: 'Team e Startup', desc: 'Proteggi la tesoreria aziendale con accesso basato sui ruoli' },
      { icon: '💼', title: 'Vesting dei Dipendenti', desc: 'Vesting di token su 4 anni con cliff di 1 anno, completamente automatizzato' },
      { icon: '🤝', title: 'Servizi di Deposito a Garanzia', desc: 'Accordo reciproco 2-su-2 per transazioni sicure' },
      { icon: '🎁', title: 'Sovvenzioni e Buste Paga', desc: 'Distribuzioni di token in blocco con rilasci pianificati' },
      { icon: '📊', title: 'Fondi di Investimento', desc: 'Approvazione del comitato per la gestione dei fondi' },
    ],
    liveTitle: 'Attivo sulla Testnet di Stellar',
    liveDesc:
      'Orion Safe è attualmente attivo sulla testnet di Stellar. Provalo ora con token di prova! ' +
      'Lancio sulla mainnet previsto per il Q4 2026 dopo l\'audit di sicurezza.',
  },

  quickstart: {
    heading: 'Guida all\'Avvio Rapido',
    subtitle: 'Metti in funzione il tuo primo vault in meno di 5 minuti.',
    step1Title: 'Collega il Tuo Wallet',
    step1Intro: 'Clicca su **"Collega Wallet"** in alto a destra e seleziona il tuo wallet preferito:',
    wallets: [
      { name: 'Freighter', note: 'Consigliato' },
      { name: 'Lobstr', note: 'Ottimo per mobile' },
      { name: 'xBull', note: 'Utenti esperti' },
      { name: 'Albedo', note: 'Basato sul web' },
    ],
    noWalletTitle: 'Non hai un wallet?',
    noWalletDesc: 'Installa {{freighter}} — è un\'estensione gratuita per browser che si configura in 2 minuti.',
    step2Title: 'Crea il Tuo Vault',
    step2Items: [
      'Clicca su **"Crea Vault"**',
      'Dai un nome al tuo vault (es. "Tesoreria del Team")',
      'Aggiungi gli indirizzi wallet dei firmatari (persone che possono approvare le transazioni)',
      'Imposta la tua **soglia** — quante approvazioni servono',
    ],
    exampleLabel: 'Esempio: Multifirma 2-su-3',
    approvedLabel: '2/3 = Approvato!',
    step3Title: 'Finanzia il Tuo Vault',
    step3Intro: 'Il tuo vault ha il proprio indirizzo. Invia token a esso come a qualsiasi wallet Stellar:',
    step3Items: [
      'Copia l\'indirizzo del tuo vault dalla dashboard',
      'Invia XLM, USDC o qualsiasi token Stellar a quell\'indirizzo',
      'I fondi compaiono entro ~5 secondi',
    ],
    proTipTitle: 'Consiglio da Esperto',
    proTipDesc: 'Per la testnet, ottieni XLM di prova gratuiti dal {{friendbot}}.',
    step4Title: 'Effettua la Tua Prima Transazione',
    step4Steps: [
      { title: 'Crea Proposta', desc: 'Vai su Transazioni → Nuova → Inserisci i dettagli → Invia' },
      { title: 'Raccogli Approvazioni', desc: 'Gli altri firmatari verificano e cliccano su "Approva"' },
      { title: 'Esegui', desc: 'Una volta raggiunta la soglia, chiunque può cliccare su "Esegui"' },
    ],
    doneTitle: '🎉 Ecco fatto!',
    doneDesc:
      'Ora hai un vault multifirma sicuro. Esplora la barra laterale per scoprire blocchi temporali, ' +
      'piani di vesting e funzionalità più avanzate.',
  },

  features: {
    heading: 'Funzionalità Principali',
    multiSig: {
      title: 'Sicurezza Multifirma',
      desc: 'Richiedi che più persone approvino le transazioni. Scegli tu la soglia — che sia 2-su-3 per un piccolo team o 5-su-9 per una grande DAO.',
      configs: ['2-su-3', '3-su-5', '4-su-7', '5-su-9'],
    },
    proposal: {
      title: 'Flusso Basato su Proposte',
      desc: 'Tutte le transazioni passano attraverso un processo di proposta trasparente. Nessuna sorpresa, piena responsabilità.',
      steps: [
        { title: 'Proponi', sub: 'Qualsiasi firmatario' },
        { title: 'Approva', sub: 'Raggiungi la soglia' },
        { title: 'Esegui', sub: 'Chiunque' },
      ],
    },
    txTypes: {
      title: 'Tipi di Transazione',
      items: [
        { icon: '💸', title: 'Trasferimento', desc: 'Invia token immediatamente dopo l\'approvazione. Pagamenti semplici e diretti.' },
        { icon: '🔒', title: 'Blocco Temporale', desc: 'Blocca i token fino a una data specifica. Perfetto per depositi a garanzia o rilasci pianificati.' },
        { icon: '📈', title: 'Vesting', desc: 'Rilascio graduale nel tempo con cliff opzionale. Ideale per i token dei dipendenti.' },
      ],
    },
    dashboard: {
      title: 'Navigazione della Dashboard',
      views: [
        { name: 'Dashboard', desc: 'Panoramica e statistiche' },
        { name: 'Asset', desc: 'Saldi dei token' },
        { name: 'Transazioni', desc: 'Proposte e cronologia' },
        { name: 'Membri', desc: 'Firmatari e ruoli' },
        { name: 'Blocchi Temporali', desc: 'Rilasci pianificati' },
        { name: 'Vesting', desc: 'Vesting dei token' },
        { name: 'Contatti', desc: 'Rubrica indirizzi' },
        { name: 'Impostazioni', desc: 'Configurazione' },
      ],
    },
    publicAccess: {
      title: 'Accesso Pubblico e Condivisione',
      cards: [
        { title: '🔗 Link di Visualizzazione Pubblica', desc: 'Condividi una vista in sola lettura con investitori, revisori o il pubblico. Possono vedere saldi e attività ma non possono compiere alcuna azione.' },
        { title: '🎁 Link di Riscatto', desc: 'I beneficiari possono riscattare i loro token bloccati o maturati direttamente con il proprio wallet — senza bisogno di accesso al vault.' },
      ],
    },
  },

  roles: {
    heading: 'Ruoli e Permessi',
    intro: 'Orion Safe utilizza un sistema basato sui ruoli per controllare chi può fare cosa. Questo offre flessibilità mantenendo la sicurezza.',
    cards: [
      { name: 'SuperAdmin', badge: 'Controllo Totale', desc: 'Controllo completo del vault. I SuperAdmin possono fare tutto, comprese le azioni che riguardano la struttura e la sicurezza del vault.', canLabel: 'Può:', can: 'Aggiungere/rimuovere firmatari, modificare la soglia di approvazione, annullare qualsiasi blocco revocabile, aggiornare le impostazioni del vault, oltre a tutto ciò che possono fare gli Admin e gli Executor.' },
      { name: 'Admin', badge: 'Operazioni', desc: 'Responsabile delle operazioni quotidiane. Gli Admin gestiscono la maggior parte delle attività di tesoreria ma non possono modificare le impostazioni di sicurezza del vault.', canLabel: 'Può:', can: 'Creare proposte, approvare transazioni, eseguire transazioni approvate, creare blocchi temporali e piani di vesting, gestire i contatti.' },
      { name: 'Executor', badge: 'Approva ed Esegui', desc: 'Autorità di approvazione. Gli Executor possono votare le proposte ed eseguire le transazioni approvate, ma non possono avviarne di nuove.', canLabel: 'Può:', can: 'Approvare o rifiutare proposte, eseguire transazioni che hanno raggiunto la soglia.' },
      { name: 'Viewer', badge: 'Sola Lettura', desc: 'Accesso da osservatore. I Viewer possono vedere tutto ma non possono compiere alcuna azione. Perfetto per revisori o stakeholder.', canLabel: 'Può:', can: 'Visualizzare i saldi del vault, la cronologia delle transazioni, le proposte, i blocchi e tutta l\'attività.' },
    ],
    matrixTitle: 'Riepilogo dei Permessi',
    matrixHeaders: { action: 'Azione', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Visualizzare vault e saldi', super: true, admin: true, exec: true, view: true },
      { action: 'Creare proposte', super: true, admin: true, exec: false, view: false },
      { action: 'Approvare proposte', super: true, admin: true, exec: true, view: false },
      { action: 'Eseguire transazioni', super: true, admin: true, exec: true, view: false },
      { action: 'Creare blocchi temporali / vesting', super: true, admin: true, exec: false, view: false },
      { action: 'Annullare blocchi revocabili', super: true, admin: false, exec: false, view: false },
      { action: 'Aggiungere/rimuovere firmatari', super: true, admin: false, exec: false, view: false },
      { action: 'Modificare la soglia', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Buona Pratica: Assegnazione dei Ruoli',
    bestPractice: [
      'Limita SuperAdmin a 1-2 persone fidate (fondatori, dirigenti)',
      'Usa Admin per i membri del team finanziario che gestiscono le operazioni quotidiane',
      'Usa Executor per i membri del consiglio che si limitano ad approvare, non ad avviare',
      'Usa Viewer per stakeholder, revisori o trasparenza pubblica',
    ],
  },

  locks: {
    heading: 'Blocchi Temporali e Vesting',
    intro: 'Controlla quando i token diventano disponibili. Che tu abbia bisogno di depositi a garanzia, pagamenti pianificati o vesting di token per i dipendenti — ci pensiamo noi.',
    timeLockTitle: 'Blocchi Temporali',
    timeLockDesc: 'Blocca i token fino a una data specifica. Il beneficiario può riscattare l\'**intero importo** solo dopo che è trascorso l\'orario di sblocco. Prima di quella data, i token sono completamente inaccessibili.',
    timeLockExampleLabel: 'Esempio: Deposito a Garanzia',
    timeLockExampleAmount: '10.000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Deposito a Garanzia', desc: 'Trattieni i fondi finché le condizioni non sono soddisfatte' },
      { icon: '🎯', title: 'Pagamenti a Milestone', desc: 'Rilascia quando il deliverable è completato' },
      { icon: '🏦', title: 'Obiettivi di Risparmio', desc: 'Previeni prelievi impulsivi' },
    ],
    vestingTitle: 'Piani di Vesting',
    vestingDesc: 'Rilascia i token **gradualmente nel tempo** con un periodo di cliff opzionale. È lo standard del settore per la retribuzione dei dipendenti e le assegnazioni agli investitori.',
    vestingExampleLabel: 'Esempio: Vesting Dipendente di 4 Anni con Cliff di 1 Anno',
    vestingExampleAmount: '100.000 token',
    vestingBarCliff: 'Cliff (1 anno)',
    vestingBarLinear: 'Vesting Lineare → 100%',
    vestingTimeline: { start: 'Inizio', cliff: 'Cliff: si sblocca il 25%', y2: 'Anno 2: 50%', y3: 'Anno 3: 75%', y4: 'Anno 4: 100%' },
    howVestingTitle: 'Come Funziona il Vesting',
    howVestingSteps: [
      { title: 'Periodo di Cliff:', desc: 'Nulla matura fino alla data del cliff. Se qualcuno se ne va prima del cliff, non riceve nulla.' },
      { title: 'Sblocco del Cliff:', desc: 'Alla data del cliff, una porzione si sblocca immediatamente (tipicamente il 25% per un piano di 4 anni).' },
      { title: 'Vesting Lineare:', desc: 'Dopo il cliff, i token maturano continuamente fino alla data finale.' },
      { title: 'Riscatta Quando Vuoi:', desc: 'I beneficiari possono riscattare i loro token maturati quando vogliono — senza scadenze.' },
    ],
    revTitle: 'Revocabile vs. Non Revocabile',
    revocable: { title: '✓ Revocabile', desc: 'Il SuperAdmin può annullare il blocco e restituire i token non maturati al vault.', bestFor: 'Ideale per: Vesting dei dipendenti (con clausola di cessazione), sovvenzioni condizionate, assegnazioni interne' },
    nonRevocable: { title: '✗ Non Revocabile', desc: 'Non può essere annullato una volta creato. I token sono garantiti al beneficiario a prescindere da tutto.', bestFor: 'Ideale per: Assegnazioni agli investitori, sovvenzioni irrevocabili, deposito a garanzia trustless, token per consulenti' },
    bulkTitle: 'Creazione in Blocco',
    bulkDesc: 'Devi creare molti blocchi in una volta? Usa la funzione di caricamento in blocco con un file CSV. Perfetta per distribuzioni di token al team, buste paga o programmi di sovvenzione.',
    bulkPrepLabel: 'Prepara semplicemente un foglio di calcolo con:',
    bulkFields: [
      'Indirizzo wallet del beneficiario',
      'Quantità di token',
      'Data di sblocco (per i blocchi temporali) o parametri di vesting',
      'Se è revocabile',
      'Descrizione opzionale',
    ],
    bulkNote: 'Carica il CSV, controlla le voci e crea fino a 10 blocchi per lotto.',
  },

  tokens: {
    heading: 'Token Supportati',
    usdcTitle: 'USDC Nativo su Stellar',
    usdcSubtitle: 'La stablecoin ufficiale di Circle — non wrapped, non bridged',
    usdcDesc: 'Orion Safe offre supporto di prima classe per USDC. Crea vault denominati in dollari, imposta il vesting degli stipendi in valuta stabile o blocca fondi in deposito a garanzia senza rischio di volatilità.',
    allTitle: 'Tutti gli Asset Supportati',
    allIntro: 'Orion Safe supporta **qualsiasi token sulla rete Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Il token nativo di Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin del dollaro USA' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin dell\'euro' },
      { emoji: '🪙', name: 'Qualsiasi Token', desc: 'Asset Stellar personalizzati' },
    ],
    whatTitle: 'Cosa Puoi Fare con i Token',
    whatItems: [
      { icon: '💸', title: 'Trasferimenti Multifirma', desc: 'Invia qualsiasi token con approvazione multifirma' },
      { icon: '🔒', title: 'Blocca Qualsiasi Asset', desc: 'Blocca USDC, XLM o token personalizzati fino a una data specifica' },
      { icon: '📈', title: 'Vesting dei Token', desc: 'Crea piani di vesting per qualsiasi asset Stellar' },
      { icon: '📊', title: 'Distribuzioni in Blocco', desc: 'Distribuisci token a più destinatari tramite CSV' },
    ],
    testTitle: 'Ottenere Token sulla Testnet',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Vai su {{laboratory}}',
      'Inserisci l\'indirizzo del tuo wallet di testnet',
      'Clicca su "Fund account with Friendbot"',
      'Ricevi 10.000 XLM di prova all\'istante!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Aggiungi la trustline USDC nel tuo wallet (Freighter → Manage Assets → Add USDC)',
      'Usa un faucet USDC di testnet o scambia XLM sul DEX di testnet',
    ],
  },

  architecture: {
    heading: 'Come Funziona',
    intro: 'Una spiegazione semplice di cosa accade dietro le quinte quando usi Orion Safe.',
    basicsTitle: 'Le Basi',
    basicsParas: [
      'Quando crei un vault, Orion Safe distribuisce uno **smart contract** sulla blockchain di Stellar. Questo smart contract è come una cassetta di sicurezza programmabile che custodisce i tuoi asset.',
      'Lo smart contract applica tutte le regole: chi può proporre transazioni, quante approvazioni servono, quando i token bloccati possono essere rilasciati e altro. **Nessuno può aggirare queste regole** — nemmeno il team di Orion Safe.',
    ],
    flowTitle: 'Cosa Accade Quando Invii Token',
    flowSteps: [
      { title: 'Crei una Proposta', desc: 'Specifica destinatario, importo e un memo opzionale. La proposta viene registrata sulla blockchain.' },
      { title: 'Altri Firmatari Approvano', desc: 'Ogni approvazione viene registrata on-chain. Tutti possono vedere chi ha approvato.' },
      { title: 'Soglia Raggiunta', desc: 'Una volta che abbastanza firmatari approvano (es. 2 su 3), la transazione è pronta per l\'esecuzione.' },
      { title: 'Esegui e Conferma', desc: 'Chiunque può avviare l\'esecuzione. I token si spostano all\'istante (~5 secondi). Fatto!' },
    ],
    whyTitle: 'Perché Abbiamo Costruito su Stellar',
    whyItems: [
      { icon: '⚡', title: 'Veloce', desc: 'Le transazioni si confermano in ~5 secondi' },
      { icon: '💰', title: 'Economico', desc: 'Meno di $0,0001 a transazione' },
      { icon: '🏦', title: 'Affidabile', desc: 'Usato da Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Sicuro', desc: 'Rete collaudata sul campo dal 2015' },
      { icon: '💵', title: 'USDC Nativo', desc: 'Stablecoin reali, non token wrapped' },
      { icon: '🌍', title: 'Globale', desc: 'Funziona ovunque con accesso a internet' },
    ],
    truthTitle: 'Importante: la Blockchain è la Fonte della Verità',
    truthDesc: 'Il tuo vault esiste sulla blockchain di Stellar, non sui nostri server. Anche se il nostro sito andasse offline, il tuo vault e i tuoi fondi resterebbero sicuri e accessibili tramite altri strumenti Stellar. Noi forniamo semplicemente un\'interfaccia facile da usare per interagire con il tuo vault on-chain.',
  },

  security: {
    heading: 'Sicurezza',
    intro: 'Come Orion Safe mantiene sicuri i tuoi asset.',
    principlesTitle: 'Principi Fondamentali di Sicurezza',
    principles: [
      { title: 'Applicazione On-Chain', desc: 'Tutte le regole sono applicate dallo smart contract sulla blockchain. Il sito web è solo un\'interfaccia utente — la blockchain è l\'autorità.' },
      { title: 'Nessuna Backdoor', desc: 'Nessuno — nemmeno il team di Orion Safe — può accedere al tuo vault o spostare i tuoi fondi senza le firme adeguate.' },
      { title: 'Multifirma per Impostazione Predefinita', desc: 'Anche se una chiave viene compromessa, gli aggressori non possono spostare fondi senza raggiungere la tua soglia di approvazione.' },
    ],
    threatsTitle: 'Come Proteggiamo dalle Minacce',
    threats: [
      { threat: 'Chiave di un firmatario compromessa', mitigation: 'La soglia multifirma previene gli attacchi a chiave singola. Altri firmatari possono rimuovere la chiave compromessa.' },
      { threat: 'Proposta malevola', mitigation: 'Richiede più approvazioni. Altri firmatari possono rifiutare le proposte dannose.' },
      { threat: 'Chiavi smarrite', mitigation: 'Finché i firmatari rimanenti raggiungono la soglia, il vault resta accessibile.' },
      { threat: 'Il sito web va offline', mitigation: 'Il tuo vault esiste sulla blockchain. Accedici tramite altri strumenti Stellar.' },
      { threat: 'Violazione del database', mitigation: 'Il nostro database è solo una cache per un caricamento più rapido. La blockchain è la fonte della verità.' },
    ],
    bestTitle: 'Buone Pratiche di Sicurezza',
    doTitle: '✓ Cosa Fare',
    dos: [
      'Usa wallet hardware (come Ledger) per le chiavi dei firmatari',
      'Mantieni la soglia a 2 o più (mai un singolo firmatario)',
      'Rivedi regolarmente il tuo elenco di firmatari',
      'Usa vault separati per scopi diversi',
      'Fai prima delle prove con piccoli importi',
      'Esegui un backup sicuro delle tue frasi di recupero',
    ],
    dontTitle: '✗ Cosa Non Fare',
    donts: [
      'Condividere chiavi private via email o chat',
      'Usare la stessa chiave per più vault critici',
      'Ignorare proposte in sospeso troppo a lungo',
      'Impostare la soglia uguale al totale dei firmatari (nessuna ridondanza)',
      'Conservare le frasi di recupero in formato digitale non cifrato',
      'Concedere l\'accesso SuperAdmin a persone di cui non ti fidi pienamente',
    ],
    statusTitle: 'Stato della Sicurezza',
    statuses: [
      { color: 'green', text: 'Costruito sulla rete Stellar collaudata sul campo (dal 2015)' },
      { color: 'green', text: 'Integrazione del framework Smart Account di OpenZeppelin' },
      { color: 'yellow', text: 'Audit di sicurezza professionale previsto prima della mainnet (Q4 2026)' },
      { color: 'gray', text: 'Programma di bug bounty in arrivo dopo il lancio sulla mainnet' },
    ],
  },

  roadmap: {
    heading: 'Roadmap',
    liveTitle: 'Attualmente Attivo sulla Testnet',
    liveFeatures: ['Vault multifirma', 'Accesso basato sui ruoli', 'Blocchi temporali', 'Piani di vesting', 'Importazione in blocco da CSV', 'Link di visualizzazione pubblica', 'Portale di riscatto', 'Supporto multi-wallet'],
    phases: [
      { color: 'purple', title: 'Fase 1: Pronto per la Produzione', target: 'Obiettivo: Luglio 2026', items: ['Preparazione del deployment sulla mainnet', 'Rafforzamento e test di sicurezza', 'Ottimizzazione delle prestazioni', 'Migliore gestione degli errori'] },
      { color: 'blue', title: 'Fase 2: Funzionalità Avanzate', target: 'Obiettivo: Settembre 2026', items: ['Limiti di spesa (massimali giornalieri/settimanali/mensili)', 'Modelli di vesting migliorati', 'Opzioni avanzate per le proposte', 'Esperienza mobile migliorata'] },
      { color: 'cyan', title: 'Fase 3: Lancio sulla Mainnet', target: 'Obiettivo: Novembre 2026', items: ['Audit di sicurezza professionale', 'Integrazione con il DEX di Stellar (trading nel vault)', 'SDK per sviluppatori', 'Guide e tutorial completi per gli utenti', '🚀 **Deployment sulla mainnet**'] },
    ],
    futureTitle: 'Visione Futura (2027+)',
    future: [
      { title: 'Integrazione DeFi', desc: 'Strategie di rendimento, protocolli di prestito, fornitura di liquidità' },
      { title: 'Suite Enterprise', desc: 'Opzioni white-label, SSO, report di conformità' },
      { title: 'Automazione', desc: 'Pagamenti ricorrenti pianificati, condizioni intelligenti' },
      { title: 'Integrazioni', desc: 'API, webhook, connessioni con software di contabilità' },
    ],
    followTitle: 'Segui i Nostri Progressi',
    followDesc: 'Stiamo costruendo in pubblico. Tieni d\'occhio il nostro repository GitHub per gli aggiornamenti, o torna qui per le ultime novità.',
  },

  faq: {
    heading: 'Domande Frequenti',
    items: [
      { q: 'Orion Safe è gratuito?', a: 'Sì! La piattaforma è gratuita. Paghi solo le normali commissioni della rete Stellar (meno di $0,0001 a transazione) più un piccolo deposito una tantum alla creazione di un vault.' },
      { q: 'Cosa succede se perdo la mia chiave privata?', a: 'Finché i firmatari rimanenti raggiungono la soglia di approvazione, il vault resta pienamente accessibile. Ad esempio, in un vault 2-su-3, se una chiave viene persa, gli altri 2 firmatari possono comunque operare il vault e persino aggiungere un firmatario sostitutivo.' },
      { q: 'Il team di Orion Safe può accedere ai miei fondi?', a: 'No. Il tuo vault è uno smart contract sulla blockchain di Stellar. Solo i firmatari che aggiungi possono autorizzare le transazioni. Non abbiamo accessi speciali, backdoor o chiavi di amministrazione al tuo vault.' },
      { q: 'Quali token posso conservare?', a: 'Qualsiasi asset Stellar: XLM (nativo), USDC, EURC e migliaia di altri token emessi sulla rete Stellar.' },
      { q: 'Quanto sono veloci le transazioni?', a: 'Circa 5 secondi dopo l\'esecuzione. Il processo di approvazione dipende dalla rapidità con cui rispondono i tuoi firmatari.' },
      { q: 'Posso annullare un blocco temporale o un piano di vesting?', a: 'Solo se è stato creato come "revocabile". I blocchi non revocabili non possono essere annullati una volta creati — i token sono garantiti al beneficiario.' },
      { q: "Esiste un'app mobile?", a: 'La dashboard è completamente responsive e funziona benissimo sui browser mobili. Usala con wallet mobili come Lobstr o collegati tramite WalletConnect.' },
      { q: 'E se il sito web va offline?', a: 'Il tuo vault esiste sulla blockchain di Stellar, non sui nostri server. Puoi interagirci usando lo Stellar Laboratory o qualsiasi strumento compatibile, anche se il nostro sito non è disponibile.' },
      { q: 'Come riscattano i loro token i beneficiari?', a: 'Condividi con loro un link di riscatto (lo trovi in Impostazioni → Condividi). Collegano il proprio wallet e riscattano direttamente — senza bisogno di accesso al vault.' },
      { q: 'Esiste un limite al numero di firmatari?', a: 'Attualmente supporta fino a 10 firmatari per vault. Ne servono di più? Contattaci per soluzioni enterprise.' },
      { q: 'Qual è la differenza tra testnet e mainnet?', a: 'La testnet usa token falsi per i test — senza valore reale. La mainnet usa token reali e denaro reale. Attualmente siamo sulla testnet, con il lancio sulla mainnet previsto per il Q4 2026.' },
      { q: 'Come ricevo aiuto se qualcosa va storto?', a: 'Consulta prima questa documentazione. Se hai ancora bisogno di aiuto, apri una issue sul nostro repository GitHub o contattaci attraverso i nostri canali.' },
    ],
  },

  common: {
    locked: '🔒 Bloccato',
    claimable: '✓ Riscattabile',
    today: 'Oggi',
    unlockDate: '⏰ Data di Sblocco',
    claimed: 'Riscattato',
    viewOnGithub: 'Vedi su GitHub',
  },
};
