import { DocsContent } from './types';

export const docsNl: DocsContent = {
  sidebarTitle: 'Documentatie',
  sections: [
    { id: 'overview', title: 'Overzicht', description: 'Wat is Orion Safe?' },
    { id: 'quickstart', title: 'Snel Starten', description: 'Installatiegids in 5 minuten' },
    { id: 'features', title: 'Kernfuncties', description: 'Wat je kunt doen' },
    { id: 'roles', title: 'Rollen & Rechten', description: 'Wie wat mag doen' },
    { id: 'locks', title: 'Tijdsloten & Vesting', description: 'Plan token-vrijgaven' },
    { id: 'tokens', title: 'Ondersteunde Tokens', description: 'USDC, XLM & meer' },
    { id: 'architecture', title: 'Hoe Het Werkt', description: 'Onder de motorkap' },
    { id: 'security', title: 'Beveiliging', description: 'Hoe we je veilig houden' },
    { id: 'faq', title: 'FAQ', description: 'Veelgestelde vragen' },
    { id: 'roadmap', title: 'Roadmap', description: 'Wat er aankomt' },
  ],

  overview: {
    heading: 'Welkom bij Orion Safe',
    intro:
      'Orion Safe is een **multi-signature treasury-platform** gebouwd op Stellar. ' +
      'Zie het als een gedeelde bankrekening voor je team, DAO of organisatie — maar met superkrachten.',
    whyTitle: 'Waarom Orion Safe gebruiken?',
    whyItems: [
      { emoji: '🔐', title: 'Geen Enkel Faalpunt', desc: 'Meerdere goedkeuringen vereist — zelfs als één sleutel wordt gecompromitteerd, blijven de fondsen veilig' },
      { emoji: '⚡', title: 'Bliksemsnel & Goedkoop', desc: 'Transacties in ~5 seconden, minder dan $0,0001 per transactie' },
      { emoji: '⏰', title: 'Tijdgebonden Controles', desc: 'Vergrendel tokens tot een datum, of geef ze geleidelijk vrij in de tijd' },
      { emoji: '🌍', title: 'Volledige Transparantie', desc: 'Elke actie on-chain vastgelegd — deel alleen-lezen links met iedereen' },
    ],
    perfectForTitle: 'Perfect Voor',
    perfectFor: [
      { icon: '🏛️', title: "DAO's & Treasuries", desc: 'Beheer gemeenschapsfondsen met transparante multi-sig governance' },
      { icon: '👥', title: 'Teams & Startups', desc: 'Beveilig de bedrijfstreasury met rolgebaseerde toegang' },
      { icon: '💼', title: 'Medewerker-Vesting', desc: '4-jarige token-vesting met cliff van 1 jaar, volledig geautomatiseerd' },
      { icon: '🤝', title: 'Escrow-Diensten', desc: '2-van-2 wederzijdse overeenkomst voor veilige transacties' },
      { icon: '🎁', title: 'Subsidies & Salarissen', desc: 'Bulk-tokenuitkeringen met geplande vrijgaven' },
      { icon: '📊', title: 'Investeringsfondsen', desc: 'Goedkeuring door commissie voor fondsbeheer' },
    ],
    liveTitle: 'Live op de Stellar-Testnet',
    liveDesc:
      'Orion Safe is momenteel live op de Stellar-testnet. Probeer het nu met test-tokens! ' +
      'Mainnet-lancering gepland voor Q4 2026 na de beveiligingsaudit.',
  },

  quickstart: {
    heading: 'Snelstartgids',
    subtitle: 'Krijg je eerste vault binnen 5 minuten draaiend.',
    step1Title: 'Verbind Je Wallet',
    step1Intro: 'Klik op **"Wallet Verbinden"** rechtsboven en selecteer je voorkeurswallet:',
    wallets: [
      { name: 'Freighter', note: 'Aanbevolen' },
      { name: 'Lobstr', note: 'Mobielvriendelijk' },
      { name: 'xBull', note: 'Gevorderde gebruikers' },
      { name: 'Albedo', note: 'Webgebaseerd' },
    ],
    noWalletTitle: 'Heb je geen wallet?',
    noWalletDesc: 'Installeer {{freighter}} — het is een gratis browserextensie die in 2 minuten is ingesteld.',
    step2Title: 'Maak Je Vault',
    step2Items: [
      'Klik op **"Vault Maken"**',
      'Geef je vault een naam (bijv. "Team-Treasury")',
      'Voeg wallet-adressen van ondertekenaars toe (mensen die transacties kunnen goedkeuren)',
      'Stel je **drempel** in — hoeveel goedkeuringen er nodig zijn',
    ],
    exampleLabel: 'Voorbeeld: 2-van-3 Multi-Sig',
    approvedLabel: '2/3 = Goedgekeurd!',
    step3Title: 'Financier Je Vault',
    step3Intro: 'Je vault heeft een eigen adres. Stuur er tokens naartoe zoals naar elke Stellar-wallet:',
    step3Items: [
      'Kopieer je vault-adres vanuit het dashboard',
      'Stuur XLM, USDC of een willekeurig Stellar-token naar dat adres',
      'Fondsen verschijnen binnen ~5 seconden',
    ],
    proTipTitle: 'Pro-Tip',
    proTipDesc: 'Voor de testnet krijg je gratis test-XLM van de {{friendbot}}.',
    step4Title: 'Voer Je Eerste Transactie Uit',
    step4Steps: [
      { title: 'Voorstel Maken', desc: 'Ga naar Transacties → Nieuw → Voer details in → Verzenden' },
      { title: 'Goedkeuringen Verzamelen', desc: 'Andere ondertekenaars bekijken en klikken op "Goedkeuren"' },
      { title: 'Uitvoeren', desc: 'Zodra de drempel is bereikt, kan iedereen op "Uitvoeren" klikken' },
    ],
    doneTitle: '🎉 Klaar!',
    doneDesc:
      'Je hebt nu een veilige multi-sig vault. Verken de zijbalk om tijdsloten, ' +
      'vesting-schema\'s en meer geavanceerde functies te ontdekken.',
  },

  features: {
    heading: 'Kernfuncties',
    multiSig: {
      title: 'Multi-Signature Beveiliging',
      desc: 'Vereis dat meerdere mensen transacties goedkeuren. Jij kiest de drempel — of het nu 2-van-3 is voor een klein team of 5-van-9 voor een grote DAO.',
      configs: ['2-van-3', '3-van-5', '4-van-7', '5-van-9'],
    },
    proposal: {
      title: 'Voorstelgebaseerde Workflow',
      desc: 'Alle transacties doorlopen een transparant voorstelproces. Geen verrassingen, volledige verantwoording.',
      steps: [
        { title: 'Voorstellen', sub: 'Elke ondertekenaar' },
        { title: 'Goedkeuren', sub: 'Drempel bereiken' },
        { title: 'Uitvoeren', sub: 'Iedereen' },
      ],
    },
    txTypes: {
      title: 'Transactietypes',
      items: [
        { icon: '💸', title: 'Overdracht', desc: 'Verstuur tokens direct na goedkeuring. Eenvoudige, directe betalingen.' },
        { icon: '🔒', title: 'Tijdslot', desc: 'Vergrendel tokens tot een specifieke datum. Perfect voor escrow of geplande vrijgaven.' },
        { icon: '📈', title: 'Vesting', desc: 'Geleidelijke vrijgave in de tijd met optionele cliff. Ideaal voor medewerker-tokens.' },
      ],
    },
    dashboard: {
      title: 'Dashboardnavigatie',
      views: [
        { name: 'Dashboard', desc: 'Overzicht & statistieken' },
        { name: 'Activa', desc: 'Tokensaldi' },
        { name: 'Transacties', desc: 'Voorstellen & geschiedenis' },
        { name: 'Leden', desc: 'Ondertekenaars & rollen' },
        { name: 'Tijdsloten', desc: 'Geplande vrijgaven' },
        { name: 'Vesting', desc: 'Token-vesting' },
        { name: 'Contacten', desc: 'Adresboek' },
        { name: 'Instellingen', desc: 'Configuratie' },
      ],
    },
    publicAccess: {
      title: 'Openbare Toegang & Delen',
      cards: [
        { title: '🔗 Openbare Weergavelink', desc: 'Deel een alleen-lezen weergave met investeerders, auditors of het publiek. Ze kunnen saldi en activiteit zien maar geen acties uitvoeren.' },
        { title: '🎁 Claimlink', desc: 'Begunstigden kunnen hun vergrendelde of gevestigde tokens rechtstreeks claimen met hun eigen wallet — geen vault-toegang nodig.' },
      ],
    },
  },

  roles: {
    heading: 'Rollen & Rechten',
    intro: 'Orion Safe gebruikt een rolgebaseerd systeem om te bepalen wie wat mag doen. Dit biedt flexibiliteit met behoud van beveiliging.',
    cards: [
      { name: 'SuperAdmin', badge: 'Volledige Controle', desc: 'Volledige vault-controle. SuperAdmins kunnen alles doen, inclusief acties die de structuur en beveiliging van de vault beïnvloeden.', canLabel: 'Kan:', can: 'Ondertekenaars toevoegen/verwijderen, de goedkeuringsdrempel wijzigen, elk herroepbaar slot annuleren, vault-instellingen bijwerken, plus alles wat Admins en Executors kunnen.' },
      { name: 'Admin', badge: 'Operaties', desc: 'Beheerder van de dagelijkse gang van zaken. Admins handelen de meeste treasury-activiteiten af maar kunnen de beveiligingsinstellingen van de vault niet wijzigen.', canLabel: 'Kan:', can: 'Voorstellen maken, transacties goedkeuren, goedgekeurde transacties uitvoeren, tijdsloten en vesting-schema\'s maken, contacten beheren.' },
      { name: 'Executor', badge: 'Goedkeuren & Uitvoeren', desc: 'Goedkeuringsbevoegdheid. Executors kunnen op voorstellen stemmen en goedgekeurde transacties uitvoeren, maar geen nieuwe initiëren.', canLabel: 'Kan:', can: 'Voorstellen goedkeuren of afwijzen, transacties uitvoeren die de drempel hebben bereikt.' },
      { name: 'Viewer', badge: 'Alleen-Lezen', desc: 'Waarnemerstoegang. Viewers kunnen alles zien maar geen acties uitvoeren. Perfect voor auditors of belanghebbenden.', canLabel: 'Kan:', can: 'Vault-saldi, transactiegeschiedenis, voorstellen, sloten en alle activiteit bekijken.' },
    ],
    matrixTitle: 'Overzicht van Rechten',
    matrixHeaders: { action: 'Actie', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Vault & saldi bekijken', super: true, admin: true, exec: true, view: true },
      { action: 'Voorstellen maken', super: true, admin: true, exec: false, view: false },
      { action: 'Voorstellen goedkeuren', super: true, admin: true, exec: true, view: false },
      { action: 'Transacties uitvoeren', super: true, admin: true, exec: true, view: false },
      { action: 'Tijdsloten / vesting maken', super: true, admin: true, exec: false, view: false },
      { action: 'Herroepbare sloten annuleren', super: true, admin: false, exec: false, view: false },
      { action: 'Ondertekenaars toevoegen/verwijderen', super: true, admin: false, exec: false, view: false },
      { action: 'Drempel wijzigen', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Beste Praktijk: Roltoewijzing',
    bestPractice: [
      'Houd SuperAdmin bij 1-2 vertrouwde personen (oprichters, leidinggevenden)',
      'Gebruik Admin voor leden van het financiële team die de dagelijkse gang van zaken beheren',
      'Gebruik Executor voor bestuursleden die alleen goedkeuren, niet initiëren',
      'Gebruik Viewer voor belanghebbenden, auditors of openbare transparantie',
    ],
  },

  locks: {
    heading: 'Tijdsloten & Vesting',
    intro: 'Bepaal wanneer tokens beschikbaar komen. Of je nu escrow, geplande betalingen of medewerker-token-vesting nodig hebt — wij hebben het voor je geregeld.',
    timeLockTitle: 'Tijdsloten',
    timeLockDesc: 'Vergrendel tokens tot een specifieke datum. De begunstigde kan het **volledige bedrag** pas claimen nadat het ontgrendelingstijdstip is verstreken. Vóór die datum zijn de tokens volledig ontoegankelijk.',
    timeLockExampleLabel: 'Voorbeeld: Escrow-Storting',
    timeLockExampleAmount: '10.000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Escrow', desc: 'Houd fondsen vast tot aan voorwaarden is voldaan' },
      { icon: '🎯', title: 'Mijlpaalbetalingen', desc: 'Geef vrij wanneer de oplevering is voltooid' },
      { icon: '🏦', title: 'Spaardoelen', desc: 'Voorkom impulsieve opnames' },
    ],
    vestingTitle: 'Vesting-Schema\'s',
    vestingDesc: 'Geef tokens **geleidelijk in de tijd** vrij met een optionele cliff-periode. Dit is de industriestandaard voor medewerkersvergoeding en investeerderstoewijzingen.',
    vestingExampleLabel: 'Voorbeeld: 4-Jarige Medewerker-Vesting met Cliff van 1 Jaar',
    vestingExampleAmount: '100.000 tokens',
    vestingBarCliff: 'Cliff (1 jr)',
    vestingBarLinear: 'Lineaire Vesting → 100%',
    vestingTimeline: { start: 'Start', cliff: 'Cliff: 25% ontgrendeld', y2: 'Jaar 2: 50%', y3: 'Jaar 3: 75%', y4: 'Jaar 4: 100%' },
    howVestingTitle: 'Hoe Vesting Werkt',
    howVestingSteps: [
      { title: 'Cliff-Periode:', desc: 'Er vest niets tot de cliff-datum. Als iemand voor de cliff vertrekt, krijgt diegene niets.' },
      { title: 'Cliff-Ontgrendeling:', desc: 'Op de cliff-datum wordt een deel direct ontgrendeld (doorgaans 25% voor een 4-jarig schema).' },
      { title: 'Lineaire Vesting:', desc: 'Na de cliff vesten de tokens continu tot de einddatum.' },
      { title: 'Altijd Claimen:', desc: 'Begunstigden kunnen hun gevestigde tokens claimen wanneer ze willen — zonder deadlines.' },
    ],
    revTitle: 'Herroepbaar vs. Niet-Herroepbaar',
    revocable: { title: '✓ Herroepbaar', desc: 'De SuperAdmin kan het slot annuleren en niet-gevestigde tokens terugsturen naar de vault.', bestFor: 'Beste voor: Medewerker-vesting (met beëindigingsclausule), voorwaardelijke subsidies, interne toewijzingen' },
    nonRevocable: { title: '✗ Niet-Herroepbaar', desc: 'Kan niet worden geannuleerd zodra het is gemaakt. De tokens zijn hoe dan ook gegarandeerd aan de begunstigde.', bestFor: 'Beste voor: Investeerderstoewijzingen, onherroepelijke subsidies, trustless escrow, adviseur-tokens' },
    bulkTitle: 'Bulk-Aanmaak',
    bulkDesc: 'Moet je veel sloten tegelijk aanmaken? Gebruik de bulk-uploadfunctie met een CSV-bestand. Perfect voor team-tokenuitkeringen, salarissen of subsidieprogramma\'s.',
    bulkPrepLabel: 'Bereid simpelweg een spreadsheet voor met:',
    bulkFields: [
      'Wallet-adres van de begunstigde',
      'Token-hoeveelheid',
      'Ontgrendelingsdatum (voor tijdsloten) of vesting-parameters',
      'Of het herroepbaar is',
      'Optionele beschrijving',
    ],
    bulkNote: 'Upload de CSV, bekijk de invoer en maak tot 10 sloten per batch.',
  },

  tokens: {
    heading: 'Ondersteunde Tokens',
    usdcTitle: 'Native USDC op Stellar',
    usdcSubtitle: "Circle's officiële stablecoin — niet wrapped, niet bridged",
    usdcDesc: 'Orion Safe biedt eersteklas ondersteuning voor USDC. Maak in dollars gedenomineerde vaults, stel salaris-vesting in stabiele valuta in, of vergrendel escrow-fondsen zonder volatiliteitsrisico.',
    allTitle: 'Alle Ondersteunde Activa',
    allIntro: 'Orion Safe ondersteunt **elk token op het Stellar-netwerk**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Het native token van Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin van de Amerikaanse dollar' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin van de euro' },
      { emoji: '🪙', name: 'Elk Token', desc: 'Aangepaste Stellar-activa' },
    ],
    whatTitle: 'Wat Je met Tokens Kunt Doen',
    whatItems: [
      { icon: '💸', title: 'Multi-Sig Overdrachten', desc: 'Verstuur elk token met multi-signature goedkeuring' },
      { icon: '🔒', title: 'Elk Activum Vergrendelen', desc: 'Vergrendel USDC, XLM of aangepaste tokens tot een specifieke datum' },
      { icon: '📈', title: 'Token-Vesting', desc: 'Maak vesting-schema\'s voor elk Stellar-activum' },
      { icon: '📊', title: 'Bulk-Uitkeringen', desc: 'Distribueer tokens naar meerdere ontvangers via CSV' },
    ],
    testTitle: 'Testnet-Tokens Verkrijgen',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Ga naar {{laboratory}}',
      'Voer je testnet-wallet-adres in',
      'Klik op "Fund account with Friendbot"',
      'Ontvang direct 10.000 test-XLM!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Voeg een USDC-trustline toe in je wallet (Freighter → Manage Assets → Add USDC)',
      'Gebruik een testnet-USDC-faucet of ruil XLM op de testnet-DEX',
    ],
  },

  architecture: {
    heading: 'Hoe Het Werkt',
    intro: 'Een eenvoudige uitleg van wat er achter de schermen gebeurt wanneer je Orion Safe gebruikt.',
    basicsTitle: 'De Basis',
    basicsParas: [
      'Wanneer je een vault maakt, implementeert Orion Safe een **smart contract** op de Stellar-blockchain. Dit smart contract is als een programmeerbare kluis die je activa bewaart.',
      'Het smart contract handhaaft alle regels: wie transacties mag voorstellen, hoeveel goedkeuringen er nodig zijn, wanneer vergrendelde tokens kunnen worden vrijgegeven en meer. **Niemand kan deze regels omzeilen** — zelfs het Orion Safe-team niet.',
    ],
    flowTitle: 'Wat Er Gebeurt Wanneer Je Tokens Verstuurt',
    flowSteps: [
      { title: 'Je Maakt een Voorstel', desc: 'Specificeer ontvanger, bedrag en een optioneel memo. Het voorstel wordt op de blockchain vastgelegd.' },
      { title: 'Andere Ondertekenaars Keuren Goed', desc: 'Elke goedkeuring wordt on-chain vastgelegd. Iedereen kan zien wie heeft goedgekeurd.' },
      { title: 'Drempel Bereikt', desc: 'Zodra genoeg ondertekenaars goedkeuren (bijv. 2 van 3), is de transactie klaar om uit te voeren.' },
      { title: 'Uitvoeren & Bevestigen', desc: 'Iedereen kan de uitvoering activeren. Tokens verplaatsen direct (~5 seconden). Klaar!' },
    ],
    whyTitle: 'Waarom We op Stellar Hebben Gebouwd',
    whyItems: [
      { icon: '⚡', title: 'Snel', desc: 'Transacties bevestigen in ~5 seconden' },
      { icon: '💰', title: 'Goedkoop', desc: 'Minder dan $0,0001 per transactie' },
      { icon: '🏦', title: 'Vertrouwd', desc: 'Gebruikt door Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Veilig', desc: 'In de praktijk beproefd netwerk sinds 2015' },
      { icon: '💵', title: 'Native USDC', desc: 'Echte stablecoins, geen wrapped tokens' },
      { icon: '🌍', title: 'Wereldwijd', desc: 'Werkt overal met internettoegang' },
    ],
    truthTitle: 'Belangrijk: de Blockchain is de Bron van Waarheid',
    truthDesc: 'Je vault bestaat op de Stellar-blockchain, niet op onze servers. Zelfs als onze website offline zou gaan, blijven je vault en fondsen veilig en toegankelijk via andere Stellar-tools. Wij bieden simpelweg een gebruiksvriendelijke interface om met je on-chain vault te communiceren.',
  },

  security: {
    heading: 'Beveiliging',
    intro: 'Hoe Orion Safe je activa veilig houdt.',
    principlesTitle: 'Kernprincipes van Beveiliging',
    principles: [
      { title: 'On-Chain Handhaving', desc: 'Alle regels worden gehandhaafd door het smart contract op de blockchain. De website is slechts een gebruikersinterface — de blockchain is de autoriteit.' },
      { title: 'Geen Achterdeuren', desc: 'Niemand — zelfs het Orion Safe-team niet — kan toegang krijgen tot je vault of je fondsen verplaatsen zonder de juiste handtekeningen.' },
      { title: 'Multi-Sig Standaard', desc: 'Zelfs als één sleutel wordt gecompromitteerd, kunnen aanvallers geen fondsen verplaatsen zonder je goedkeuringsdrempel te bereiken.' },
    ],
    threatsTitle: 'Hoe We Beschermen Tegen Bedreigingen',
    threats: [
      { threat: 'Gecompromitteerde ondertekenaarssleutel', mitigation: 'De multi-sig drempel voorkomt aanvallen met één sleutel. Andere ondertekenaars kunnen de gecompromitteerde sleutel verwijderen.' },
      { threat: 'Kwaadaardig voorstel', mitigation: 'Vereist meerdere goedkeuringen. Andere ondertekenaars kunnen slechte voorstellen afwijzen.' },
      { threat: 'Verloren sleutels', mitigation: 'Zolang de resterende ondertekenaars de drempel bereiken, blijft de vault toegankelijk.' },
      { threat: 'Website gaat offline', mitigation: 'Je vault bestaat op de blockchain. Krijg er toegang toe via andere Stellar-tools.' },
      { threat: 'Datalek', mitigation: 'Onze database is slechts een cache voor sneller laden. De blockchain is de bron van waarheid.' },
    ],
    bestTitle: 'Beste Beveiligingspraktijken',
    doTitle: '✓ Doen',
    dos: [
      'Gebruik hardware-wallets (zoals Ledger) voor ondertekenaarssleutels',
      'Houd de drempel op 2 of hoger (nooit één ondertekenaar)',
      'Bekijk regelmatig je lijst met ondertekenaars',
      'Gebruik aparte vaults voor verschillende doeleinden',
      'Test eerst met kleine bedragen',
      'Maak veilig een back-up van je herstelzinnen',
    ],
    dontTitle: '✗ Niet Doen',
    donts: [
      'Privésleutels delen via e-mail of chat',
      'Dezelfde sleutel gebruiken voor meerdere kritieke vaults',
      'Openstaande voorstellen te lang negeren',
      'De drempel gelijk stellen aan het totaal aantal ondertekenaars (geen redundantie)',
      'Herstelzinnen digitaal onversleuteld opslaan',
      'SuperAdmin-toegang geven aan mensen die je niet volledig vertrouwt',
    ],
    statusTitle: 'Beveiligingsstatus',
    statuses: [
      { color: 'green', text: 'Gebouwd op het in de praktijk beproefde Stellar-netwerk (sinds 2015)' },
      { color: 'green', text: 'Integratie van het OpenZeppelin Smart Account-framework' },
      { color: 'yellow', text: 'Professionele beveiligingsaudit gepland vóór de mainnet (Q4 2026)' },
      { color: 'gray', text: 'Bug-bountyprogramma komt na de mainnet-lancering' },
    ],
  },

  roadmap: {
    heading: 'Roadmap',
    liveTitle: 'Momenteel Live op de Testnet',
    liveFeatures: ['Multi-sig vaults', 'Rolgebaseerde toegang', 'Tijdsloten', 'Vesting-schema\'s', 'Bulk-CSV-import', 'Openbare weergavelinks', 'Claimportaal', 'Multi-wallet-ondersteuning'],
    phases: [
      { color: 'purple', title: 'Fase 1: Gereed voor Productie', target: 'Doel: Juli 2026', items: ['Voorbereiding mainnet-implementatie', 'Beveiligingsversterking en testen', 'Prestatie-optimalisatie', 'Verbeterde foutafhandeling'] },
      { color: 'blue', title: 'Fase 2: Geavanceerde Functies', target: 'Doel: September 2026', items: ['Bestedingslimieten (dagelijkse/wekelijkse/maandelijkse plafonds)', 'Verbeterde vesting-sjablonen', 'Geavanceerde voorstelopties', 'Verbeterde mobiele ervaring'] },
      { color: 'cyan', title: 'Fase 3: Mainnet-Lancering', target: 'Doel: November 2026', items: ['Professionele beveiligingsaudit', 'Stellar-DEX-integratie (handelen in de vault)', 'SDK voor ontwikkelaars', 'Uitgebreide gebruikershandleidingen en tutorials', '🚀 **Mainnet-implementatie**'] },
    ],
    futureTitle: 'Toekomstvisie (2027+)',
    future: [
      { title: 'DeFi-Integratie', desc: 'Rendementsstrategieën, leenprotocollen, liquiditeitsvoorziening' },
      { title: 'Enterprise-Suite', desc: 'White-label-opties, SSO, compliance-rapportage' },
      { title: 'Automatisering', desc: 'Geplande terugkerende betalingen, slimme voorwaarden' },
      { title: 'Integraties', desc: 'API, webhooks, koppelingen met boekhoudsoftware' },
    ],
    followTitle: 'Volg Onze Voortgang',
    followDesc: 'We bouwen in het openbaar. Houd onze GitHub-repository in de gaten voor updates, of kom hier terug voor het laatste nieuws.',
  },

  faq: {
    heading: 'Veelgestelde Vragen',
    items: [
      { q: 'Is Orion Safe gratis te gebruiken?', a: 'Ja! Het platform is gratis. Je betaalt alleen de standaard Stellar-netwerkkosten (minder dan $0,0001 per transactie) plus een kleine eenmalige storting bij het maken van een vault.' },
      { q: 'Wat gebeurt er als ik mijn privésleutel verlies?', a: 'Zolang de resterende ondertekenaars de goedkeuringsdrempel bereiken, blijft de vault volledig toegankelijk. In een 2-van-3 vault kunnen bijvoorbeeld, als één sleutel verloren gaat, de andere 2 ondertekenaars de vault nog steeds bedienen en zelfs een vervangende ondertekenaar toevoegen.' },
      { q: 'Kan het Orion Safe-team bij mijn fondsen?', a: 'Nee. Je vault is een smart contract op de Stellar-blockchain. Alleen ondertekenaars die jij toevoegt kunnen transacties autoriseren. We hebben geen speciale toegang, achterdeuren of admin-sleutels tot je vault.' },
      { q: 'Welke tokens kan ik opslaan?', a: 'Elk Stellar-activum: XLM (native), USDC, EURC en duizenden andere tokens uitgegeven op het Stellar-netwerk.' },
      { q: 'Hoe snel zijn transacties?', a: 'Ongeveer 5 seconden na uitvoering. Het goedkeuringsproces hangt af van hoe snel je ondertekenaars reageren.' },
      { q: 'Kan ik een tijdslot of vesting-schema annuleren?', a: 'Alleen als het als "herroepbaar" is gemaakt. Niet-herroepbare sloten kunnen na het maken niet worden geannuleerd — de tokens zijn gegarandeerd aan de begunstigde.' },
      { q: 'Is er een mobiele app?', a: 'Het dashboard is volledig responsief en werkt uitstekend in mobiele browsers. Gebruik het met mobiele wallets zoals Lobstr of verbind via WalletConnect.' },
      { q: 'Wat als de website offline gaat?', a: 'Je vault bestaat op de Stellar-blockchain, niet op onze servers. Je kunt ermee communiceren via het Stellar Laboratory of elk compatibel hulpmiddel, zelfs als onze website niet beschikbaar is.' },
      { q: 'Hoe claimen begunstigden hun tokens?', a: 'Deel een claimlink met hen (te vinden in Instellingen → Delen). Ze verbinden hun eigen wallet en claimen rechtstreeks — geen vault-toegang nodig.' },
      { q: 'Is er een limiet op het aantal ondertekenaars?', a: 'Momenteel worden tot 10 ondertekenaars per vault ondersteund. Meer nodig? Neem contact met ons op voor enterprise-oplossingen.' },
      { q: 'Wat is het verschil tussen testnet en mainnet?', a: 'De testnet gebruikt nep-tokens om te testen — geen echte waarde. De mainnet gebruikt echte tokens en echt geld. We zitten momenteel op de testnet, met een mainnet-lancering gepland voor Q4 2026.' },
      { q: 'Hoe krijg ik hulp als er iets misgaat?', a: 'Raadpleeg eerst deze documentatie. Heb je nog hulp nodig, open dan een issue op onze GitHub-repository of neem contact op via onze kanalen.' },
    ],
  },

  common: {
    locked: '🔒 Vergrendeld',
    claimable: '✓ Claimbaar',
    today: 'Vandaag',
    unlockDate: '⏰ Ontgrendelingsdatum',
    claimed: 'Geclaimd',
    viewOnGithub: 'Bekijk op GitHub',
  },
};
