import { DocsContent } from './types';

export const docsPl: DocsContent = {
  sidebarTitle: 'Dokumentacja',
  sections: [
    { id: 'overview', title: 'Przegląd', description: 'Czym jest Orion Safe?' },
    { id: 'quickstart', title: 'Szybki Start', description: 'Przewodnik konfiguracji w 5 minut' },
    { id: 'features', title: 'Główne Funkcje', description: 'Co możesz zrobić' },
    { id: 'roles', title: 'Role i Uprawnienia', description: 'Kto co może zrobić' },
    { id: 'locks', title: 'Blokady Czasowe i Vesting', description: 'Zaplanuj uwalnianie tokenów' },
    { id: 'tokens', title: 'Obsługiwane Tokeny', description: 'USDC, XLM i więcej' },
    { id: 'architecture', title: 'Jak To Działa', description: 'Pod maską' },
    { id: 'security', title: 'Bezpieczeństwo', description: 'Jak dbamy o Twoje bezpieczeństwo' },
    { id: 'faq', title: 'FAQ', description: 'Częste pytania' },
    { id: 'roadmap', title: 'Plan Rozwoju', description: 'Co dalej' },
  ],

  overview: {
    heading: 'Witamy w Orion Safe',
    intro:
      'Orion Safe to **platforma skarbcowa z wieloma podpisami** zbudowana na Stellar. ' +
      'Pomyśl o niej jak o wspólnym koncie bankowym dla Twojego zespołu, DAO lub organizacji — ale z supermocami.',
    whyTitle: 'Dlaczego warto używać Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Brak Pojedynczego Punktu Awarii', desc: 'Wymaganych jest wiele zatwierdzeń — nawet jeśli jeden klucz zostanie naruszony, środki pozostają bezpieczne' },
      { emoji: '⚡', title: 'Błyskawicznie i Tanio', desc: 'Transakcje w ~5 sekund, mniej niż 0,0001 USD za transakcję' },
      { emoji: '⏰', title: 'Kontrola Oparta na Czasie', desc: 'Zablokuj tokeny do określonej daty lub uwalniaj je stopniowo w czasie' },
      { emoji: '🌍', title: 'Pełna Przejrzystość', desc: 'Każde działanie zapisane on-chain — udostępniaj linki tylko do odczytu komukolwiek' },
    ],
    perfectForTitle: 'Idealne Dla',
    perfectFor: [
      { icon: '🏛️', title: 'DAO i Skarbce', desc: 'Zarządzaj funduszami społeczności dzięki przejrzystemu zarządzaniu z wieloma podpisami' },
      { icon: '👥', title: 'Zespoły i Startupy', desc: 'Zabezpiecz skarbiec firmy dostępem opartym na rolach' },
      { icon: '💼', title: 'Vesting Pracowników', desc: '4-letni vesting tokenów z rocznym cliffem, w pełni zautomatyzowany' },
      { icon: '🤝', title: 'Usługi Escrow', desc: 'Wzajemne porozumienie 2-z-2 dla bezpiecznych transakcji' },
      { icon: '🎁', title: 'Dotacje i Wypłaty', desc: 'Masowe dystrybucje tokenów z zaplanowanym uwalnianiem' },
      { icon: '📊', title: 'Fundusze Inwestycyjne', desc: 'Zatwierdzanie przez komitet do zarządzania funduszem' },
    ],
    liveTitle: 'Działa na Testnecie Stellar',
    liveDesc:
      'Orion Safe jest obecnie aktywny na testnecie Stellar. Wypróbuj go teraz z tokenami testowymi! ' +
      'Uruchomienie na mainnecie planowane na Q4 2026 po audycie bezpieczeństwa.',
  },

  quickstart: {
    heading: 'Przewodnik Szybkiego Startu',
    subtitle: 'Uruchom swój pierwszy skarbiec w mniej niż 5 minut.',
    step1Title: 'Połącz Swój Portfel',
    step1Intro: 'Kliknij **„Połącz Portfel"** w prawym górnym rogu i wybierz preferowany portfel:',
    wallets: [
      { name: 'Freighter', note: 'Zalecany' },
      { name: 'Lobstr', note: 'Przyjazny dla urządzeń mobilnych' },
      { name: 'xBull', note: 'Zaawansowani użytkownicy' },
      { name: 'Albedo', note: 'Oparty na przeglądarce' },
    ],
    noWalletTitle: 'Nie masz portfela?',
    noWalletDesc: 'Zainstaluj {{freighter}} — to darmowe rozszerzenie przeglądarki, którego konfiguracja zajmuje 2 minuty.',
    step2Title: 'Utwórz Swój Skarbiec',
    step2Items: [
      'Kliknij **„Utwórz Skarbiec"**',
      'Nadaj skarbcowi nazwę (np. „Skarbiec Zespołu")',
      'Dodaj adresy portfeli sygnatariuszy (osób, które mogą zatwierdzać transakcje)',
      'Ustaw swój **próg** — ile zatwierdzeń jest wymaganych',
    ],
    exampleLabel: 'Przykład: Wiele Podpisów 2-z-3',
    approvedLabel: '2/3 = Zatwierdzone!',
    step3Title: 'Zasil Swój Skarbiec',
    step3Intro: 'Twój skarbiec ma własny adres. Wyślij na niego tokeny jak na dowolny portfel Stellar:',
    step3Items: [
      'Skopiuj adres skarbca z panelu',
      'Wyślij XLM, USDC lub dowolny token Stellar na ten adres',
      'Środki pojawiają się w ~5 sekund',
    ],
    proTipTitle: 'Profesjonalna Wskazówka',
    proTipDesc: 'Na testnecie zdobądź darmowe testowe XLM z {{friendbot}}.',
    step4Title: 'Wykonaj Swoją Pierwszą Transakcję',
    step4Steps: [
      { title: 'Utwórz Propozycję', desc: 'Przejdź do Transakcje → Nowa → Wprowadź szczegóły → Wyślij' },
      { title: 'Zbierz Zatwierdzenia', desc: 'Inni sygnatariusze sprawdzają i klikają „Zatwierdź"' },
      { title: 'Wykonaj', desc: 'Po osiągnięciu progu każdy może kliknąć „Wykonaj"' },
    ],
    doneTitle: '🎉 To wszystko!',
    doneDesc:
      'Masz teraz bezpieczny skarbiec z wieloma podpisami. Przeglądaj pasek boczny, aby odkryć blokady czasowe, ' +
      'harmonogramy vestingu i bardziej zaawansowane funkcje.',
  },

  features: {
    heading: 'Główne Funkcje',
    multiSig: {
      title: 'Bezpieczeństwo z Wieloma Podpisami',
      desc: 'Wymagaj, aby wiele osób zatwierdzało transakcje. Ty wybierasz próg — czy to 2-z-3 dla małego zespołu, czy 5-z-9 dla dużej DAO.',
      configs: ['2-z-3', '3-z-5', '4-z-7', '5-z-9'],
    },
    proposal: {
      title: 'Proces Oparty na Propozycjach',
      desc: 'Wszystkie transakcje przechodzą przez przejrzysty proces propozycji. Bez niespodzianek, z pełną odpowiedzialnością.',
      steps: [
        { title: 'Zaproponuj', sub: 'Dowolny sygnatariusz' },
        { title: 'Zatwierdź', sub: 'Osiągnij próg' },
        { title: 'Wykonaj', sub: 'Każdy' },
      ],
    },
    txTypes: {
      title: 'Typy Transakcji',
      items: [
        { icon: '💸', title: 'Przelew', desc: 'Wyślij tokeny natychmiast po zatwierdzeniu. Proste, bezpośrednie płatności.' },
        { icon: '🔒', title: 'Blokada Czasowa', desc: 'Zablokuj tokeny do określonej daty. Idealne do escrow lub zaplanowanych uwolnień.' },
        { icon: '📈', title: 'Vesting', desc: 'Stopniowe uwalnianie w czasie z opcjonalnym cliffem. Idealne dla tokenów pracowniczych.' },
      ],
    },
    dashboard: {
      title: 'Nawigacja Panelu',
      views: [
        { name: 'Panel', desc: 'Przegląd i statystyki' },
        { name: 'Aktywa', desc: 'Salda tokenów' },
        { name: 'Transakcje', desc: 'Propozycje i historia' },
        { name: 'Członkowie', desc: 'Sygnatariusze i role' },
        { name: 'Blokady Czasowe', desc: 'Zaplanowane uwolnienia' },
        { name: 'Vesting', desc: 'Vesting tokenów' },
        { name: 'Kontakty', desc: 'Książka adresowa' },
        { name: 'Ustawienia', desc: 'Konfiguracja' },
      ],
    },
    publicAccess: {
      title: 'Dostęp Publiczny i Udostępnianie',
      cards: [
        { title: '🔗 Link do Widoku Publicznego', desc: 'Udostępnij widok tylko do odczytu inwestorom, audytorom lub publiczności. Mogą zobaczyć salda i aktywność, ale nie mogą podejmować żadnych działań.' },
        { title: '🎁 Link do Odbioru', desc: 'Beneficjenci mogą odebrać swoje zablokowane lub nabyte tokeny bezpośrednio za pomocą własnego portfela — bez potrzeby dostępu do skarbca.' },
      ],
    },
  },

  roles: {
    heading: 'Role i Uprawnienia',
    intro: 'Orion Safe wykorzystuje system oparty na rolach, aby kontrolować, kto co może robić. Zapewnia to elastyczność przy zachowaniu bezpieczeństwa.',
    cards: [
      { name: 'SuperAdmin', badge: 'Pełna Kontrola', desc: 'Pełna kontrola nad skarbcem. SuperAdmini mogą robić wszystko, w tym działania wpływające na strukturę i bezpieczeństwo skarbca.', canLabel: 'Może:', can: 'Dodawać/usuwać sygnatariuszy, zmieniać próg zatwierdzeń, anulować dowolną odwołalną blokadę, aktualizować ustawienia skarbca, a także wszystko, co mogą Admini i Executorzy.' },
      { name: 'Admin', badge: 'Operacje', desc: 'Menedżer codziennych operacji. Admini obsługują większość działań skarbcowych, ale nie mogą zmieniać ustawień bezpieczeństwa skarbca.', canLabel: 'Może:', can: 'Tworzyć propozycje, zatwierdzać transakcje, wykonywać zatwierdzone transakcje, tworzyć blokady czasowe i harmonogramy vestingu, zarządzać kontaktami.' },
      { name: 'Executor', badge: 'Zatwierdzaj i Wykonuj', desc: 'Uprawnienia do zatwierdzania. Executorzy mogą głosować nad propozycjami i wykonywać zatwierdzone transakcje, ale nie mogą inicjować nowych.', canLabel: 'Może:', can: 'Zatwierdzać lub odrzucać propozycje, wykonywać transakcje, które osiągnęły próg.' },
      { name: 'Viewer', badge: 'Tylko Odczyt', desc: 'Dostęp obserwatora. Viewerzy mogą wszystko zobaczyć, ale nie mogą podejmować żadnych działań. Idealne dla audytorów lub interesariuszy.', canLabel: 'Może:', can: 'Przeglądać salda skarbca, historię transakcji, propozycje, blokady i całą aktywność.' },
    ],
    matrixTitle: 'Podsumowanie Uprawnień',
    matrixHeaders: { action: 'Działanie', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Przeglądanie skarbca i sald', super: true, admin: true, exec: true, view: true },
      { action: 'Tworzenie propozycji', super: true, admin: true, exec: false, view: false },
      { action: 'Zatwierdzanie propozycji', super: true, admin: true, exec: true, view: false },
      { action: 'Wykonywanie transakcji', super: true, admin: true, exec: true, view: false },
      { action: 'Tworzenie blokad czasowych / vestingu', super: true, admin: true, exec: false, view: false },
      { action: 'Anulowanie odwołalnych blokad', super: true, admin: false, exec: false, view: false },
      { action: 'Dodawanie/usuwanie sygnatariuszy', super: true, admin: false, exec: false, view: false },
      { action: 'Zmiana progu', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Dobra Praktyka: Przydzielanie Ról',
    bestPractice: [
      'Ogranicz SuperAdmina do 1-2 zaufanych osób (założyciele, kadra kierownicza)',
      'Używaj Admina dla członków zespołu finansowego zarządzających codziennymi operacjami',
      'Używaj Executora dla członków zarządu, którzy tylko zatwierdzają, a nie inicjują',
      'Używaj Viewera dla interesariuszy, audytorów lub publicznej przejrzystości',
    ],
  },

  locks: {
    heading: 'Blokady Czasowe i Vesting',
    intro: 'Kontroluj, kiedy tokeny stają się dostępne. Niezależnie od tego, czy potrzebujesz escrow, zaplanowanych płatności czy vestingu tokenów pracowniczych — mamy to dla Ciebie.',
    timeLockTitle: 'Blokady Czasowe',
    timeLockDesc: 'Zablokuj tokeny do określonej daty. Beneficjent może odebrać **pełną kwotę** dopiero po upływie czasu odblokowania. Przed tą datą tokeny są całkowicie niedostępne.',
    timeLockExampleLabel: 'Przykład: Depozyt Escrow',
    timeLockExampleAmount: '10 000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Escrow', desc: 'Przechowuj środki do czasu spełnienia warunków' },
      { icon: '🎯', title: 'Płatności za Kamienie Milowe', desc: 'Uwolnij po ukończeniu rezultatu' },
      { icon: '🏦', title: 'Cele Oszczędnościowe', desc: 'Zapobiegaj impulsywnym wypłatom' },
    ],
    vestingTitle: 'Harmonogramy Vestingu',
    vestingDesc: 'Uwalniaj tokeny **stopniowo w czasie** z opcjonalnym okresem cliffu. To branżowy standard dla wynagrodzeń pracowniczych i alokacji dla inwestorów.',
    vestingExampleLabel: 'Przykład: 4-letni Vesting Pracownika z Rocznym Cliffem',
    vestingExampleAmount: '100 000 tokenów',
    vestingBarCliff: 'Cliff (1 r.)',
    vestingBarLinear: 'Vesting Liniowy → 100%',
    vestingTimeline: { start: 'Start', cliff: 'Cliff: odblokowane 25%', y2: 'Rok 2: 50%', y3: 'Rok 3: 75%', y4: 'Rok 4: 100%' },
    howVestingTitle: 'Jak Działa Vesting',
    howVestingSteps: [
      { title: 'Okres Cliffu:', desc: 'Nic nie jest nabywane do daty cliffu. Jeśli ktoś odejdzie przed cliffem, nie otrzymuje nic.' },
      { title: 'Odblokowanie Cliffu:', desc: 'W dacie cliffu część odblokowuje się natychmiast (zwykle 25% dla 4-letniego harmonogramu).' },
      { title: 'Vesting Liniowy:', desc: 'Po cliffie tokeny są nabywane w sposób ciągły aż do daty końcowej.' },
      { title: 'Odbiór w Dowolnym Momencie:', desc: 'Beneficjenci mogą odebrać swoje nabyte tokeny, kiedy tylko chcą — bez terminów.' },
    ],
    revTitle: 'Odwołalne vs. Nieodwołalne',
    revocable: { title: '✓ Odwołalne', desc: 'SuperAdmin może anulować blokadę i zwrócić nienabyte tokeny do skarbca.', bestFor: 'Najlepsze do: Vestingu pracowników (z klauzulą rozwiązania umowy), dotacji warunkowych, alokacji wewnętrznych' },
    nonRevocable: { title: '✗ Nieodwołalne', desc: 'Nie można anulować po utworzeniu. Tokeny są gwarantowane beneficjentowi bez względu na wszystko.', bestFor: 'Najlepsze do: Alokacji dla inwestorów, nieodwołalnych dotacji, bezzaufaniowego escrow, tokenów dla doradców' },
    bulkTitle: 'Tworzenie Masowe',
    bulkDesc: 'Musisz utworzyć wiele blokad naraz? Skorzystaj z funkcji przesyłania masowego z plikiem CSV. Idealne do dystrybucji tokenów w zespole, wypłat lub programów dotacji.',
    bulkPrepLabel: 'Wystarczy przygotować arkusz kalkulacyjny z:',
    bulkFields: [
      'Adresem portfela beneficjenta',
      'Ilością tokenów',
      'Datą odblokowania (dla blokad czasowych) lub parametrami vestingu',
      'Czy jest odwołalna',
      'Opcjonalnym opisem',
    ],
    bulkNote: 'Prześlij plik CSV, sprawdź wpisy i utwórz maksymalnie 10 blokad na partię.',
  },

  tokens: {
    heading: 'Obsługiwane Tokeny',
    usdcTitle: 'Natywne USDC na Stellar',
    usdcSubtitle: 'Oficjalny stablecoin Circle — nieopakowany, niemostkowany',
    usdcDesc: 'Orion Safe oferuje pierwszorzędną obsługę USDC. Twórz skarbce denominowane w dolarach, ustaw vesting wynagrodzeń w stabilnej walucie lub zablokuj środki escrow bez ryzyka zmienności.',
    allTitle: 'Wszystkie Obsługiwane Aktywa',
    allIntro: 'Orion Safe obsługuje **dowolny token w sieci Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Natywny token Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin dolara amerykańskiego' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin euro' },
      { emoji: '🪙', name: 'Dowolny Token', desc: 'Niestandardowe aktywa Stellar' },
    ],
    whatTitle: 'Co Możesz Zrobić z Tokenami',
    whatItems: [
      { icon: '💸', title: 'Przelewy z Wieloma Podpisami', desc: 'Wysyłaj dowolny token z zatwierdzeniem wielopodpisowym' },
      { icon: '🔒', title: 'Zablokuj Dowolne Aktywo', desc: 'Zablokuj USDC, XLM lub niestandardowe tokeny do określonej daty' },
      { icon: '📈', title: 'Vesting Tokenów', desc: 'Twórz harmonogramy vestingu dla dowolnego aktywa Stellar' },
      { icon: '📊', title: 'Masowe Dystrybucje', desc: 'Rozdzielaj tokeny do wielu odbiorców za pomocą CSV' },
    ],
    testTitle: 'Zdobywanie Tokenów Testnet',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Przejdź do {{laboratory}}',
      'Wprowadź adres swojego portfela testnet',
      'Kliknij „Fund account with Friendbot"',
      'Otrzymaj 10 000 testowych XLM natychmiast!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Dodaj trustline USDC w swoim portfelu (Freighter → Manage Assets → Add USDC)',
      'Użyj kranu USDC testnet lub wymień XLM na DEX-ie testnet',
    ],
  },

  architecture: {
    heading: 'Jak To Działa',
    intro: 'Proste wyjaśnienie, co dzieje się za kulisami, gdy używasz Orion Safe.',
    basicsTitle: 'Podstawy',
    basicsParas: [
      'Gdy tworzysz skarbiec, Orion Safe wdraża **smart kontrakt** na blockchainie Stellar. Ten smart kontrakt jest jak programowalny sejf depozytowy, który przechowuje Twoje aktywa.',
      'Smart kontrakt egzekwuje wszystkie zasady: kto może proponować transakcje, ile zatwierdzeń jest wymaganych, kiedy zablokowane tokeny mogą zostać uwolnione i więcej. **Nikt nie może obejść tych zasad** — nawet zespół Orion Safe.',
    ],
    flowTitle: 'Co Się Dzieje, Gdy Wysyłasz Tokeny',
    flowSteps: [
      { title: 'Tworzysz Propozycję', desc: 'Określ odbiorcę, kwotę i opcjonalne memo. Propozycja zostaje zapisana na blockchainie.' },
      { title: 'Inni Sygnatariusze Zatwierdzają', desc: 'Każde zatwierdzenie jest zapisywane on-chain. Każdy widzi, kto zatwierdził.' },
      { title: 'Próg Osiągnięty', desc: 'Gdy wystarczająca liczba sygnatariuszy zatwierdzi (np. 2 z 3), transakcja jest gotowa do wykonania.' },
      { title: 'Wykonaj i Potwierdź', desc: 'Każdy może uruchomić wykonanie. Tokeny przemieszczają się natychmiast (~5 sekund). Gotowe!' },
    ],
    whyTitle: 'Dlaczego Zbudowaliśmy na Stellar',
    whyItems: [
      { icon: '⚡', title: 'Szybko', desc: 'Transakcje potwierdzają się w ~5 sekund' },
      { icon: '💰', title: 'Tanio', desc: 'Mniej niż 0,0001 USD za transakcję' },
      { icon: '🏦', title: 'Zaufane', desc: 'Używane przez Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Bezpieczne', desc: 'Sprawdzona w boju sieć od 2015 roku' },
      { icon: '💵', title: 'Natywne USDC', desc: 'Prawdziwe stablecoiny, nie opakowane tokeny' },
      { icon: '🌍', title: 'Globalne', desc: 'Działa wszędzie z dostępem do internetu' },
    ],
    truthTitle: 'Ważne: Blockchain Jest Źródłem Prawdy',
    truthDesc: 'Twój skarbiec istnieje na blockchainie Stellar, a nie na naszych serwerach. Nawet gdyby nasza strona przestała działać, Twój skarbiec i środki pozostałyby bezpieczne i dostępne za pośrednictwem innych narzędzi Stellar. Po prostu zapewniamy przyjazny interfejs do interakcji z Twoim skarbcem on-chain.',
  },

  security: {
    heading: 'Bezpieczeństwo',
    intro: 'Jak Orion Safe chroni Twoje aktywa.',
    principlesTitle: 'Podstawowe Zasady Bezpieczeństwa',
    principles: [
      { title: 'Egzekwowanie On-Chain', desc: 'Wszystkie zasady są egzekwowane przez smart kontrakt na blockchainie. Strona internetowa to tylko interfejs użytkownika — blockchain jest autorytetem.' },
      { title: 'Brak Tylnych Furtek', desc: 'Nikt — nawet zespół Orion Safe — nie może uzyskać dostępu do Twojego skarbca ani przenieść Twoich środków bez odpowiednich podpisów.' },
      { title: 'Wiele Podpisów Domyślnie', desc: 'Nawet jeśli jeden klucz zostanie naruszony, atakujący nie mogą przenieść środków bez osiągnięcia Twojego progu zatwierdzeń.' },
    ],
    threatsTitle: 'Jak Chronimy Przed Zagrożeniami',
    threats: [
      { threat: 'Naruszony klucz sygnatariusza', mitigation: 'Próg wielopodpisowy zapobiega atakom na pojedynczy klucz. Inni sygnatariusze mogą usunąć naruszony klucz.' },
      { threat: 'Złośliwa propozycja', mitigation: 'Wymaga wielu zatwierdzeń. Inni sygnatariusze mogą odrzucić szkodliwe propozycje.' },
      { threat: 'Utracone klucze', mitigation: 'Dopóki pozostali sygnatariusze osiągają próg, skarbiec pozostaje dostępny.' },
      { threat: 'Strona przestaje działać', mitigation: 'Twój skarbiec istnieje na blockchainie. Uzyskaj do niego dostęp za pomocą innych narzędzi Stellar.' },
      { threat: 'Naruszenie bazy danych', mitigation: 'Nasza baza danych to tylko pamięć podręczna dla szybszego ładowania. Blockchain jest źródłem prawdy.' },
    ],
    bestTitle: 'Najlepsze Praktyki Bezpieczeństwa',
    doTitle: '✓ Rób',
    dos: [
      'Używaj portfeli sprzętowych (takich jak Ledger) dla kluczy sygnatariuszy',
      'Utrzymuj próg na poziomie 2 lub wyższym (nigdy pojedynczy sygnatariusz)',
      'Regularnie przeglądaj swoją listę sygnatariuszy',
      'Używaj oddzielnych skarbców do różnych celów',
      'Najpierw testuj na małych kwotach',
      'Bezpiecznie twórz kopie zapasowe swoich fraz odzyskiwania',
    ],
    dontTitle: '✗ Nie Rób',
    donts: [
      'Udostępniać kluczy prywatnych przez e-mail lub czat',
      'Używać tego samego klucza do wielu krytycznych skarbców',
      'Ignorować oczekujących propozycji zbyt długo',
      'Ustawiać progu równego całkowitej liczbie sygnatariuszy (brak redundancji)',
      'Przechowywać fraz odzyskiwania cyfrowo bez szyfrowania',
      'Nadawać dostępu SuperAdmina osobom, którym nie ufasz w pełni',
    ],
    statusTitle: 'Status Bezpieczeństwa',
    statuses: [
      { color: 'green', text: 'Zbudowane na sprawdzonej w boju sieci Stellar (od 2015 roku)' },
      { color: 'green', text: 'Integracja frameworka Smart Account od OpenZeppelin' },
      { color: 'yellow', text: 'Profesjonalny audyt bezpieczeństwa planowany przed mainnetem (Q4 2026)' },
      { color: 'gray', text: 'Program nagród za błędy po uruchomieniu mainnetu' },
    ],
  },

  roadmap: {
    heading: 'Plan Rozwoju',
    liveTitle: 'Obecnie Działa na Testnecie',
    liveFeatures: ['Skarbce z wieloma podpisami', 'Dostęp oparty na rolach', 'Blokady czasowe', 'Harmonogramy vestingu', 'Masowy import CSV', 'Linki do widoku publicznego', 'Portal odbioru', 'Obsługa wielu portfeli'],
    phases: [
      { color: 'purple', title: 'Faza 1: Gotowość Produkcyjna', target: 'Cel: Lipiec 2026', items: ['Przygotowanie wdrożenia na mainnecie', 'Wzmocnienie bezpieczeństwa i testy', 'Optymalizacja wydajności', 'Lepsza obsługa błędów'] },
      { color: 'blue', title: 'Faza 2: Zaawansowane Funkcje', target: 'Cel: Wrzesień 2026', items: ['Limity wydatków (dzienne/tygodniowe/miesięczne pułapy)', 'Ulepszone szablony vestingu', 'Zaawansowane opcje propozycji', 'Ulepszone doświadczenie mobilne'] },
      { color: 'cyan', title: 'Faza 3: Uruchomienie Mainnetu', target: 'Cel: Listopad 2026', items: ['Profesjonalny audyt bezpieczeństwa', 'Integracja z DEX-em Stellar (handel w skarbcu)', 'SDK dla deweloperów', 'Kompleksowe przewodniki i samouczki dla użytkowników', '🚀 **Wdrożenie na mainnecie**'] },
    ],
    futureTitle: 'Wizja Przyszłości (2027+)',
    future: [
      { title: 'Integracja DeFi', desc: 'Strategie dochodowe, protokoły pożyczkowe, dostarczanie płynności' },
      { title: 'Pakiet Enterprise', desc: 'Opcje white-label, SSO, raportowanie zgodności' },
      { title: 'Automatyzacja', desc: 'Zaplanowane płatności cykliczne, inteligentne warunki' },
      { title: 'Integracje', desc: 'API, webhooki, połączenia z oprogramowaniem księgowym' },
    ],
    followTitle: 'Śledź Nasze Postępy',
    followDesc: 'Budujemy publicznie. Obserwuj nasze repozytorium GitHub, aby śledzić aktualizacje, lub wracaj tutaj po najnowsze wiadomości.',
  },

  faq: {
    heading: 'Najczęściej Zadawane Pytania',
    items: [
      { q: 'Czy Orion Safe jest darmowy?', a: 'Tak! Platforma jest darmowa. Płacisz tylko standardowe opłaty sieci Stellar (mniej niż 0,0001 USD za transakcję) plus niewielki jednorazowy depozyt przy tworzeniu skarbca.' },
      { q: 'Co się stanie, jeśli zgubię swój klucz prywatny?', a: 'Dopóki pozostali sygnatariusze osiągają próg zatwierdzeń, skarbiec pozostaje w pełni dostępny. Na przykład w skarbcu 2-z-3, jeśli jeden klucz zostanie utracony, pozostali 2 sygnatariusze nadal mogą obsługiwać skarbiec, a nawet dodać zastępczego sygnatariusza.' },
      { q: 'Czy zespół Orion Safe może uzyskać dostęp do moich środków?', a: 'Nie. Twój skarbiec to smart kontrakt na blockchainie Stellar. Tylko dodani przez Ciebie sygnatariusze mogą autoryzować transakcje. Nie mamy specjalnego dostępu, tylnych furtek ani kluczy administratora do Twojego skarbca.' },
      { q: 'Jakie tokeny mogę przechowywać?', a: 'Dowolne aktywo Stellar: XLM (natywne), USDC, EURC i tysiące innych tokenów wyemitowanych w sieci Stellar.' },
      { q: 'Jak szybkie są transakcje?', a: 'Około 5 sekund po wykonaniu. Proces zatwierdzania zależy od tego, jak szybko reagują Twoi sygnatariusze.' },
      { q: 'Czy mogę anulować blokadę czasową lub harmonogram vestingu?', a: 'Tylko jeśli została utworzona jako „odwołalna". Nieodwołalnych blokad nie można anulować po utworzeniu — tokeny są gwarantowane beneficjentowi.' },
      { q: 'Czy istnieje aplikacja mobilna?', a: 'Panel jest w pełni responsywny i świetnie działa w przeglądarkach mobilnych. Korzystaj z niego z portfelami mobilnymi, takimi jak Lobstr, lub łącz się przez WalletConnect.' },
      { q: 'Co jeśli strona przestanie działać?', a: 'Twój skarbiec istnieje na blockchainie Stellar, a nie na naszych serwerach. Możesz z nim współdziałać za pomocą Stellar Laboratory lub dowolnego kompatybilnego narzędzia, nawet jeśli nasza strona jest niedostępna.' },
      { q: 'Jak beneficjenci odbierają swoje tokeny?', a: 'Udostępnij im link do odbioru (znajdziesz go w Ustawienia → Udostępnij). Łączą swój własny portfel i odbierają bezpośrednio — bez potrzeby dostępu do skarbca.' },
      { q: 'Czy istnieje limit liczby sygnatariuszy?', a: 'Obecnie obsługuje do 10 sygnatariuszy na skarbiec. Potrzebujesz więcej? Skontaktuj się z nami w sprawie rozwiązań dla przedsiębiorstw.' },
      { q: 'Jaka jest różnica między testnetem a mainnetem?', a: 'Testnet używa fałszywych tokenów do testów — bez rzeczywistej wartości. Mainnet używa prawdziwych tokenów i prawdziwych pieniędzy. Obecnie jesteśmy na testnecie, a uruchomienie mainnetu planowane jest na Q4 2026.' },
      { q: 'Jak uzyskać pomoc, jeśli coś pójdzie nie tak?', a: 'Najpierw sprawdź tę dokumentację. Jeśli nadal potrzebujesz pomocy, otwórz zgłoszenie w naszym repozytorium GitHub lub skontaktuj się przez nasze kanały.' },
    ],
  },

  common: {
    locked: '🔒 Zablokowane',
    claimable: '✓ Do Odbioru',
    today: 'Dzisiaj',
    unlockDate: '⏰ Data Odblokowania',
    claimed: 'Odebrane',
    viewOnGithub: 'Zobacz na GitHub',
  },
};
