import { DocsContent } from './types';

export const docsPt: DocsContent = {
  sidebarTitle: 'Documentação',
  sections: [
    { id: 'overview', title: 'Visão Geral', description: 'O que é o Orion Safe?' },
    { id: 'quickstart', title: 'Início Rápido', description: 'Guia de configuração em 5 minutos' },
    { id: 'features', title: 'Recursos Principais', description: 'O que você pode fazer' },
    { id: 'roles', title: 'Funções e Permissões', description: 'Quem pode fazer o quê' },
    { id: 'locks', title: 'Bloqueios Temporais e Vesting', description: 'Programe liberações de tokens' },
    { id: 'tokens', title: 'Tokens Suportados', description: 'USDC, XLM e mais' },
    { id: 'architecture', title: 'Como Funciona', description: 'Nos bastidores' },
    { id: 'security', title: 'Segurança', description: 'Como mantemos você seguro' },
    { id: 'faq', title: 'Perguntas Frequentes', description: 'Perguntas comuns' },
    { id: 'roadmap', title: 'Roteiro', description: 'O que vem a seguir' },
  ],

  overview: {
    heading: 'Bem-vindo ao Orion Safe',
    intro:
      'O Orion Safe é uma **plataforma de tesouraria multiassinatura** construída sobre a Stellar. ' +
      'Pense nela como uma conta bancária compartilhada para sua equipe, DAO ou organização — mas com superpoderes.',
    whyTitle: 'Por que usar o Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Sem Ponto Único de Falha', desc: 'Várias aprovações necessárias — mesmo que uma chave seja comprometida, os fundos permanecem seguros' },
      { emoji: '⚡', title: 'Rápido e Barato', desc: 'Transações em ~5 segundos, menos de US$ 0,0001 por transação' },
      { emoji: '⏰', title: 'Controles Baseados em Tempo', desc: 'Bloqueie tokens até uma data ou libere-os gradualmente ao longo do tempo' },
      { emoji: '🌍', title: 'Total Transparência', desc: 'Cada ação registrada na cadeia — compartilhe links somente leitura com qualquer pessoa' },
    ],
    perfectForTitle: 'Perfeito Para',
    perfectFor: [
      { icon: '🏛️', title: 'DAOs e Tesourarias', desc: 'Gerencie fundos comunitários com governança multiassinatura transparente' },
      { icon: '👥', title: 'Equipes e Startups', desc: 'Proteja a tesouraria da empresa com acesso baseado em funções' },
      { icon: '💼', title: 'Vesting de Funcionários', desc: 'Vesting de tokens em 4 anos com cliff de 1 ano, totalmente automatizado' },
      { icon: '🤝', title: 'Serviços de Custódia', desc: 'Acordo mútuo 2-de-2 para transações seguras' },
      { icon: '🎁', title: 'Subsídios e Folha de Pagamento', desc: 'Distribuições em massa de tokens com liberações programadas' },
      { icon: '📊', title: 'Fundos de Investimento', desc: 'Aprovação por comitê para gestão de fundos' },
    ],
    liveTitle: 'No Ar na Testnet da Stellar',
    liveDesc:
      'O Orion Safe está atualmente ativo na testnet da Stellar. Experimente agora com tokens de teste! ' +
      'Lançamento na mainnet previsto para o Q4 2026 após a auditoria de segurança.',
  },

  quickstart: {
    heading: 'Guia de Início Rápido',
    subtitle: 'Coloque seu primeiro vault em funcionamento em menos de 5 minutos.',
    step1Title: 'Conecte Sua Carteira',
    step1Intro: 'Clique em **"Conectar Carteira"** no canto superior direito e selecione sua carteira preferida:',
    wallets: [
      { name: 'Freighter', note: 'Recomendada' },
      { name: 'Lobstr', note: 'Ideal para celular' },
      { name: 'xBull', note: 'Usuários avançados' },
      { name: 'Albedo', note: 'Baseada na web' },
    ],
    noWalletTitle: 'Não tem uma carteira?',
    noWalletDesc: 'Instale o {{freighter}} — é uma extensão de navegador gratuita que leva 2 minutos para configurar.',
    step2Title: 'Crie Seu Vault',
    step2Items: [
      'Clique em **"Criar Vault"**',
      'Dê um nome ao seu vault (ex.: "Tesouraria da Equipe")',
      'Adicione os endereços de carteira dos signatários (pessoas que podem aprovar transações)',
      'Defina seu **limite** — quantas aprovações são necessárias',
    ],
    exampleLabel: 'Exemplo: Multiassinatura 2-de-3',
    approvedLabel: '2/3 = Aprovado!',
    step3Title: 'Financie Seu Vault',
    step3Intro: 'Seu vault tem seu próprio endereço. Envie tokens para ele como em qualquer carteira Stellar:',
    step3Items: [
      'Copie o endereço do seu vault no painel',
      'Envie XLM, USDC ou qualquer token Stellar para esse endereço',
      'Os fundos aparecem em ~5 segundos',
    ],
    proTipTitle: 'Dica Profissional',
    proTipDesc: 'Para a testnet, obtenha XLM de teste grátis no {{friendbot}}.',
    step4Title: 'Faça Sua Primeira Transação',
    step4Steps: [
      { title: 'Criar Proposta', desc: 'Vá em Transações → Nova → Insira os detalhes → Enviar' },
      { title: 'Coletar Aprovações', desc: 'Outros signatários revisam e clicam em "Aprovar"' },
      { title: 'Executar', desc: 'Uma vez atingido o limite, qualquer um pode clicar em "Executar"' },
    ],
    doneTitle: '🎉 É isso!',
    doneDesc:
      'Agora você tem um vault multiassinatura seguro. Explore a barra lateral para descobrir bloqueios temporais, ' +
      'cronogramas de vesting e recursos mais avançados.',
  },

  features: {
    heading: 'Recursos Principais',
    multiSig: {
      title: 'Segurança Multiassinatura',
      desc: 'Exija que várias pessoas aprovem as transações. Você escolhe o limite — seja 2-de-3 para uma equipe pequena ou 5-de-9 para uma DAO grande.',
      configs: ['2-de-3', '3-de-5', '4-de-7', '5-de-9'],
    },
    proposal: {
      title: 'Fluxo Baseado em Propostas',
      desc: 'Todas as transações passam por um processo de proposta transparente. Sem surpresas, com total responsabilidade.',
      steps: [
        { title: 'Propor', sub: 'Qualquer signatário' },
        { title: 'Aprovar', sub: 'Atingir o limite' },
        { title: 'Executar', sub: 'Qualquer um' },
      ],
    },
    txTypes: {
      title: 'Tipos de Transação',
      items: [
        { icon: '💸', title: 'Transferência', desc: 'Envie tokens imediatamente após a aprovação. Pagamentos simples e diretos.' },
        { icon: '🔒', title: 'Bloqueio Temporal', desc: 'Bloqueie tokens até uma data específica. Perfeito para custódia ou liberações programadas.' },
        { icon: '📈', title: 'Vesting', desc: 'Liberação gradual ao longo do tempo com cliff opcional. Ideal para tokens de funcionários.' },
      ],
    },
    dashboard: {
      title: 'Navegação do Painel',
      views: [
        { name: 'Painel', desc: 'Visão geral e estatísticas' },
        { name: 'Ativos', desc: 'Saldos de tokens' },
        { name: 'Transações', desc: 'Propostas e histórico' },
        { name: 'Membros', desc: 'Signatários e funções' },
        { name: 'Bloqueios Temporais', desc: 'Liberações programadas' },
        { name: 'Vesting', desc: 'Vesting de tokens' },
        { name: 'Contatos', desc: 'Catálogo de endereços' },
        { name: 'Configurações', desc: 'Configuração' },
      ],
    },
    publicAccess: {
      title: 'Acesso Público e Compartilhamento',
      cards: [
        { title: '🔗 Link de Visualização Pública', desc: 'Compartilhe uma visualização somente leitura com investidores, auditores ou o público. Eles podem ver saldos e atividades, mas não podem realizar nenhuma ação.' },
        { title: '🎁 Link de Resgate', desc: 'Os beneficiários podem resgatar seus tokens bloqueados ou adquiridos diretamente com sua própria carteira — sem necessidade de acesso ao vault.' },
      ],
    },
  },

  roles: {
    heading: 'Funções e Permissões',
    intro: 'O Orion Safe usa um sistema baseado em funções para controlar quem pode fazer o quê. Isso oferece flexibilidade mantendo a segurança.',
    cards: [
      { name: 'SuperAdmin', badge: 'Controle Total', desc: 'Controle completo do vault. SuperAdmins podem fazer tudo, incluindo ações que afetam a estrutura e a segurança do vault.', canLabel: 'Pode:', can: 'Adicionar/remover signatários, alterar o limite de aprovação, cancelar qualquer bloqueio revogável, atualizar configurações do vault, além de tudo o que Admins e Executors podem fazer.' },
      { name: 'Admin', badge: 'Operações', desc: 'Responsável pelas operações do dia a dia. Admins lidam com a maioria das atividades de tesouraria, mas não podem alterar as configurações de segurança do vault.', canLabel: 'Pode:', can: 'Criar propostas, aprovar transações, executar transações aprovadas, criar bloqueios temporais e cronogramas de vesting, gerenciar contatos.' },
      { name: 'Executor', badge: 'Aprovar e Executar', desc: 'Autoridade de aprovação. Executors podem votar em propostas e executar transações aprovadas, mas não podem iniciar novas.', canLabel: 'Pode:', can: 'Aprovar ou rejeitar propostas, executar transações que atingiram o limite.' },
      { name: 'Viewer', badge: 'Somente Leitura', desc: 'Acesso de observador. Viewers podem ver tudo, mas não podem realizar nenhuma ação. Perfeito para auditores ou partes interessadas.', canLabel: 'Pode:', can: 'Ver saldos do vault, histórico de transações, propostas, bloqueios e toda a atividade.' },
    ],
    matrixTitle: 'Resumo de Permissões',
    matrixHeaders: { action: 'Ação', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Ver vault e saldos', super: true, admin: true, exec: true, view: true },
      { action: 'Criar propostas', super: true, admin: true, exec: false, view: false },
      { action: 'Aprovar propostas', super: true, admin: true, exec: true, view: false },
      { action: 'Executar transações', super: true, admin: true, exec: true, view: false },
      { action: 'Criar bloqueios temporais / vesting', super: true, admin: true, exec: false, view: false },
      { action: 'Cancelar bloqueios revogáveis', super: true, admin: false, exec: false, view: false },
      { action: 'Adicionar/remover signatários', super: true, admin: false, exec: false, view: false },
      { action: 'Alterar o limite', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Boa Prática: Atribuição de Funções',
    bestPractice: [
      'Mantenha o SuperAdmin com 1-2 pessoas de confiança (fundadores, executivos)',
      'Use Admin para membros da equipe financeira que gerenciam as operações diárias',
      'Use Executor para membros do conselho que apenas aprovam, não iniciam',
      'Use Viewer para partes interessadas, auditores ou transparência pública',
    ],
  },

  locks: {
    heading: 'Bloqueios Temporais e Vesting',
    intro: 'Controle quando os tokens ficam disponíveis. Seja para custódia, pagamentos programados ou vesting de tokens de funcionários — nós cobrimos isso.',
    timeLockTitle: 'Bloqueios Temporais',
    timeLockDesc: 'Bloqueie tokens até uma data específica. O beneficiário pode resgatar o **valor total** apenas depois que o horário de desbloqueio passar. Antes dessa data, os tokens ficam completamente inacessíveis.',
    timeLockExampleLabel: 'Exemplo: Depósito em Custódia',
    timeLockExampleAmount: '10.000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Custódia', desc: 'Retenha fundos até que as condições sejam atendidas' },
      { icon: '🎯', title: 'Pagamentos por Marcos', desc: 'Libere quando a entrega for concluída' },
      { icon: '🏦', title: 'Metas de Poupança', desc: 'Evite retiradas impulsivas' },
    ],
    vestingTitle: 'Cronogramas de Vesting',
    vestingDesc: 'Libere tokens **gradualmente ao longo do tempo** com um período de cliff opcional. Este é o padrão do setor para remuneração de funcionários e alocações de investidores.',
    vestingExampleLabel: 'Exemplo: Vesting de Funcionário de 4 Anos com Cliff de 1 Ano',
    vestingExampleAmount: '100.000 tokens',
    vestingBarCliff: 'Cliff (1 ano)',
    vestingBarLinear: 'Vesting Linear → 100%',
    vestingTimeline: { start: 'Início', cliff: 'Cliff: 25% desbloqueado', y2: 'Ano 2: 50%', y3: 'Ano 3: 75%', y4: 'Ano 4: 100%' },
    howVestingTitle: 'Como o Vesting Funciona',
    howVestingSteps: [
      { title: 'Período de Cliff:', desc: 'Nada é adquirido até a data do cliff. Se alguém sair antes do cliff, não recebe nada.' },
      { title: 'Desbloqueio do Cliff:', desc: 'Na data do cliff, uma parte é desbloqueada imediatamente (tipicamente 25% para um cronograma de 4 anos).' },
      { title: 'Vesting Linear:', desc: 'Após o cliff, os tokens são adquiridos continuamente até a data final.' },
      { title: 'Resgate a Qualquer Momento:', desc: 'Os beneficiários podem resgatar seus tokens adquiridos quando quiserem — sem prazos.' },
    ],
    revTitle: 'Revogável vs. Não Revogável',
    revocable: { title: '✓ Revogável', desc: 'O SuperAdmin pode cancelar o bloqueio e devolver os tokens não adquiridos ao vault.', bestFor: 'Melhor para: Vesting de funcionários (com cláusula de rescisão), subsídios condicionais, alocações internas' },
    nonRevocable: { title: '✗ Não Revogável', desc: 'Não pode ser cancelado depois de criado. Os tokens são garantidos ao beneficiário não importa o quê.', bestFor: 'Melhor para: Alocações de investidores, subsídios irrevogáveis, custódia sem confiança, tokens de consultores' },
    bulkTitle: 'Criação em Massa',
    bulkDesc: 'Precisa criar muitos bloqueios de uma vez? Use o recurso de upload em massa com um arquivo CSV. Perfeito para distribuições de tokens de equipe, folha de pagamento ou programas de subsídios.',
    bulkPrepLabel: 'Basta preparar uma planilha com:',
    bulkFields: [
      'Endereço de carteira do beneficiário',
      'Quantidade de tokens',
      'Data de desbloqueio (para bloqueios temporais) ou parâmetros de vesting',
      'Se é revogável',
      'Descrição opcional',
    ],
    bulkNote: 'Envie o CSV, revise as entradas e crie até 10 bloqueios por lote.',
  },

  tokens: {
    heading: 'Tokens Suportados',
    usdcTitle: 'USDC Nativo na Stellar',
    usdcSubtitle: 'A stablecoin oficial da Circle — não encapsulada, não em ponte',
    usdcDesc: 'O Orion Safe oferece suporte de primeira classe ao USDC. Crie vaults denominados em dólares, configure vesting de salários em moeda estável ou bloqueie fundos de custódia sem risco de volatilidade.',
    allTitle: 'Todos os Ativos Suportados',
    allIntro: 'O Orion Safe suporta **qualquer token na rede Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'O token nativo da Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin do dólar americano' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin do euro' },
      { emoji: '🪙', name: 'Qualquer Token', desc: 'Ativos personalizados da Stellar' },
    ],
    whatTitle: 'O Que Você Pode Fazer Com Tokens',
    whatItems: [
      { icon: '💸', title: 'Transferências Multiassinatura', desc: 'Envie qualquer token com aprovação multiassinatura' },
      { icon: '🔒', title: 'Bloquear Qualquer Ativo', desc: 'Bloqueie USDC, XLM ou tokens personalizados até uma data específica' },
      { icon: '📈', title: 'Vesting de Tokens', desc: 'Crie cronogramas de vesting para qualquer ativo da Stellar' },
      { icon: '📊', title: 'Distribuições em Massa', desc: 'Distribua tokens para vários destinatários via CSV' },
    ],
    testTitle: 'Obtendo Tokens da Testnet',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Vá até {{laboratory}}',
      'Insira o endereço da sua carteira de testnet',
      'Clique em "Fund account with Friendbot"',
      'Receba 10.000 XLM de teste instantaneamente!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Adicione a trustline de USDC na sua carteira (Freighter → Manage Assets → Add USDC)',
      'Use uma faucet de USDC de testnet ou troque XLM no DEX da testnet',
    ],
  },

  architecture: {
    heading: 'Como Funciona',
    intro: 'Uma explicação simples do que acontece nos bastidores quando você usa o Orion Safe.',
    basicsTitle: 'O Básico',
    basicsParas: [
      'Quando você cria um vault, o Orion Safe implanta um **contrato inteligente** na blockchain da Stellar. Esse contrato inteligente é como um cofre programável que guarda seus ativos.',
      'O contrato inteligente impõe todas as regras: quem pode propor transações, quantas aprovações são necessárias, quando os tokens bloqueados podem ser liberados e mais. **Ninguém pode contornar essas regras** — nem mesmo a equipe do Orion Safe.',
    ],
    flowTitle: 'O Que Acontece Quando Você Envia Tokens',
    flowSteps: [
      { title: 'Você Cria uma Proposta', desc: 'Especifique o destinatário, o valor e um memo opcional. A proposta é registrada na blockchain.' },
      { title: 'Outros Signatários Aprovam', desc: 'Cada aprovação é registrada na cadeia. Todos podem ver quem aprovou.' },
      { title: 'Limite Atingido', desc: 'Uma vez que signatários suficientes aprovem (ex.: 2 de 3), a transação fica pronta para ser executada.' },
      { title: 'Executar e Confirmar', desc: 'Qualquer um pode acionar a execução. Os tokens se movem instantaneamente (~5 segundos). Pronto!' },
    ],
    whyTitle: 'Por Que Construímos na Stellar',
    whyItems: [
      { icon: '⚡', title: 'Rápido', desc: 'Transações confirmam em ~5 segundos' },
      { icon: '💰', title: 'Barato', desc: 'Menos de US$ 0,0001 por transação' },
      { icon: '🏦', title: 'Confiável', desc: 'Usado por Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Seguro', desc: 'Rede testada em batalha desde 2015' },
      { icon: '💵', title: 'USDC Nativo', desc: 'Stablecoins reais, não tokens encapsulados' },
      { icon: '🌍', title: 'Global', desc: 'Funciona em qualquer lugar com acesso à internet' },
    ],
    truthTitle: 'Importante: A Blockchain é a Fonte da Verdade',
    truthDesc: 'Seu vault existe na blockchain da Stellar, não em nossos servidores. Mesmo que nosso site saísse do ar, seu vault e seus fundos permaneceriam seguros e acessíveis através de outras ferramentas Stellar. Nós apenas fornecemos uma interface amigável para interagir com seu vault na cadeia.',
  },

  security: {
    heading: 'Segurança',
    intro: 'Como o Orion Safe mantém seus ativos seguros.',
    principlesTitle: 'Princípios Fundamentais de Segurança',
    principles: [
      { title: 'Imposição na Cadeia', desc: 'Todas as regras são impostas pelo contrato inteligente na blockchain. O site é apenas uma interface de usuário — a blockchain é a autoridade.' },
      { title: 'Sem Portas dos Fundos', desc: 'Ninguém — nem mesmo a equipe do Orion Safe — pode acessar seu vault ou mover seus fundos sem as assinaturas adequadas.' },
      { title: 'Multiassinatura por Padrão', desc: 'Mesmo que uma chave seja comprometida, os atacantes não podem mover fundos sem atingir seu limite de aprovação.' },
    ],
    threatsTitle: 'Como Protegemos Contra Ameaças',
    threats: [
      { threat: 'Chave de signatário comprometida', mitigation: 'O limite multiassinatura impede ataques com chave única. Outros signatários podem remover a chave comprometida.' },
      { threat: 'Proposta maliciosa', mitigation: 'Requer várias aprovações. Outros signatários podem rejeitar propostas ruins.' },
      { threat: 'Chaves perdidas', mitigation: 'Enquanto os signatários restantes atingirem o limite, o vault permanece acessível.' },
      { threat: 'O site sai do ar', mitigation: 'Seu vault existe na blockchain. Acesse-o através de outras ferramentas Stellar.' },
      { threat: 'Violação do banco de dados', mitigation: 'Nosso banco de dados é apenas um cache para carregamento mais rápido. A blockchain é a fonte da verdade.' },
    ],
    bestTitle: 'Boas Práticas de Segurança',
    doTitle: '✓ Faça',
    dos: [
      'Use carteiras de hardware (como Ledger) para as chaves dos signatários',
      'Mantenha o limite em 2 ou mais (nunca um único signatário)',
      'Revise regularmente sua lista de signatários',
      'Use vaults separados para finalidades diferentes',
      'Teste primeiro com pequenas quantias',
      'Faça backup das suas frases de recuperação com segurança',
    ],
    dontTitle: '✗ Não Faça',
    donts: [
      'Compartilhar chaves privadas por e-mail ou chat',
      'Usar a mesma chave para vários vaults críticos',
      'Ignorar propostas pendentes por muito tempo',
      'Definir o limite igual ao total de signatários (sem redundância)',
      'Armazenar frases de recuperação digitalmente sem criptografia',
      'Dar acesso de SuperAdmin a pessoas em quem você não confia plenamente',
    ],
    statusTitle: 'Status de Segurança',
    statuses: [
      { color: 'green', text: 'Construído na rede Stellar testada em batalha (desde 2015)' },
      { color: 'green', text: 'Integração do framework Smart Account da OpenZeppelin' },
      { color: 'yellow', text: 'Auditoria de segurança profissional planejada antes da mainnet (Q4 2026)' },
      { color: 'gray', text: 'Programa de recompensas por bugs chegando após o lançamento na mainnet' },
    ],
  },

  roadmap: {
    heading: 'Roteiro',
    liveTitle: 'Atualmente no Ar na Testnet',
    liveFeatures: ['Vaults multiassinatura', 'Acesso baseado em funções', 'Bloqueios temporais', 'Cronogramas de vesting', 'Importação em massa por CSV', 'Links de visualização pública', 'Portal de resgate', 'Suporte a múltiplas carteiras'],
    phases: [
      { color: 'purple', title: 'Fase 1: Prontidão para Produção', target: 'Meta: Julho de 2026', items: ['Preparação da implantação na mainnet', 'Fortalecimento e testes de segurança', 'Otimização de desempenho', 'Melhor tratamento de erros'] },
      { color: 'blue', title: 'Fase 2: Recursos Avançados', target: 'Meta: Setembro de 2026', items: ['Limites de gastos (tetos diários/semanais/mensais)', 'Modelos de vesting aprimorados', 'Opções avançadas de propostas', 'Experiência móvel aprimorada'] },
      { color: 'cyan', title: 'Fase 3: Lançamento na Mainnet', target: 'Meta: Novembro de 2026', items: ['Auditoria de segurança profissional', 'Integração com o DEX da Stellar (negociação dentro do vault)', 'SDK para desenvolvedores', 'Guias e tutoriais completos para usuários', '🚀 **Implantação na mainnet**'] },
    ],
    futureTitle: 'Visão Futura (2027+)',
    future: [
      { title: 'Integração DeFi', desc: 'Estratégias de rendimento, protocolos de empréstimo, provisão de liquidez' },
      { title: 'Suíte Empresarial', desc: 'Opções white-label, SSO, relatórios de conformidade' },
      { title: 'Automação', desc: 'Pagamentos recorrentes programados, condições inteligentes' },
      { title: 'Integrações', desc: 'API, webhooks, conexões com software de contabilidade' },
    ],
    followTitle: 'Acompanhe Nosso Progresso',
    followDesc: 'Estamos construindo de forma pública. Acompanhe nosso repositório no GitHub para atualizações, ou volte aqui para as últimas novidades.',
  },

  faq: {
    heading: 'Perguntas Frequentes',
    items: [
      { q: 'O Orion Safe é gratuito?', a: 'Sim! A plataforma é gratuita. Você paga apenas as taxas padrão da rede Stellar (menos de US$ 0,0001 por transação) mais um pequeno depósito único ao criar um vault.' },
      { q: 'O que acontece se eu perder minha chave privada?', a: 'Enquanto os signatários restantes atingirem o limite de aprovação, o vault permanece totalmente acessível. Por exemplo, em um vault 2-de-3, se uma chave for perdida, os outros 2 signatários ainda podem operar o vault e até adicionar um signatário substituto.' },
      { q: 'A equipe do Orion Safe pode acessar meus fundos?', a: 'Não. Seu vault é um contrato inteligente na blockchain da Stellar. Apenas os signatários que você adicionar podem autorizar transações. Não temos acesso especial, portas dos fundos nem chaves de administrador ao seu vault.' },
      { q: 'Quais tokens posso armazenar?', a: 'Qualquer ativo da Stellar: XLM (nativo), USDC, EURC e milhares de outros tokens emitidos na rede Stellar.' },
      { q: 'Quão rápidas são as transações?', a: 'Cerca de 5 segundos após a execução. O processo de aprovação depende da rapidez com que seus signatários respondem.' },
      { q: 'Posso cancelar um bloqueio temporal ou cronograma de vesting?', a: 'Apenas se foi criado como "revogável". Bloqueios não revogáveis não podem ser cancelados depois de criados — os tokens são garantidos ao beneficiário.' },
      { q: 'Existe um aplicativo móvel?', a: 'O painel é totalmente responsivo e funciona muito bem em navegadores móveis. Use-o com carteiras móveis como Lobstr ou conecte-se via WalletConnect.' },
      { q: 'E se o site sair do ar?', a: 'Seu vault existe na blockchain da Stellar, não em nossos servidores. Você pode interagir com ele usando o Stellar Laboratory ou qualquer ferramenta compatível, mesmo que nosso site esteja indisponível.' },
      { q: 'Como os beneficiários resgatam seus tokens?', a: 'Compartilhe um link de resgate com eles (em Configurações → Compartilhar). Eles conectam sua própria carteira e resgatam diretamente — sem necessidade de acesso ao vault.' },
      { q: 'Existe um limite no número de signatários?', a: 'Atualmente suporta até 10 signatários por vault. Precisa de mais? Entre em contato conosco para soluções empresariais.' },
      { q: 'Qual é a diferença entre testnet e mainnet?', a: 'A testnet usa tokens falsos para testes — sem valor real. A mainnet usa tokens reais e dinheiro real. Estamos atualmente na testnet, com lançamento na mainnet previsto para o Q4 2026.' },
      { q: 'Como obtenho ajuda se algo der errado?', a: 'Consulte primeiro esta documentação. Se ainda precisar de ajuda, abra uma issue em nosso repositório no GitHub ou entre em contato pelos nossos canais.' },
    ],
  },

  common: {
    locked: '🔒 Bloqueado',
    claimable: '✓ Resgatável',
    today: 'Hoje',
    unlockDate: '⏰ Data de Desbloqueio',
    claimed: 'Resgatado',
    viewOnGithub: 'Ver no GitHub',
  },
};
