import { DocsContent } from './types';

export const docsRo: DocsContent = {
  sidebarTitle: 'Documentație',
  sections: [
    { id: 'overview', title: 'Prezentare Generală', description: 'Ce este Orion Safe?' },
    { id: 'quickstart', title: 'Pornire Rapidă', description: 'Ghid de configurare în 5 minute' },
    { id: 'features', title: 'Funcții Principale', description: 'Ce poți face' },
    { id: 'roles', title: 'Roluri și Permisiuni', description: 'Cine ce poate face' },
    { id: 'locks', title: 'Blocări Temporale și Vesting', description: 'Programează eliberări de tokenuri' },
    { id: 'tokens', title: 'Tokenuri Acceptate', description: 'USDC, XLM și altele' },
    { id: 'architecture', title: 'Cum Funcționează', description: 'În spatele scenei' },
    { id: 'security', title: 'Securitate', description: 'Cum te ținem în siguranță' },
    { id: 'faq', title: 'Întrebări Frecvente', description: 'Întrebări comune' },
    { id: 'roadmap', title: 'Foaie de Parcurs', description: 'Ce urmează' },
  ],

  overview: {
    heading: 'Bun venit la Orion Safe',
    intro:
      'Orion Safe este o **platformă de trezorerie cu semnături multiple** construită pe Stellar. ' +
      'Gândește-te la ea ca la un cont bancar comun pentru echipa, DAO-ul sau organizația ta — dar cu superputeri.',
    whyTitle: 'De ce să folosești Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Niciun Punct Unic de Eșec', desc: 'Sunt necesare aprobări multiple — chiar dacă o cheie este compromisă, fondurile rămân în siguranță' },
      { emoji: '⚡', title: 'Rapid și Ieftin', desc: 'Tranzacții în ~5 secunde, mai puțin de 0,0001 $ per tranzacție' },
      { emoji: '⏰', title: 'Controale Bazate pe Timp', desc: 'Blochează tokenuri până la o dată sau eliberează-le treptat în timp' },
      { emoji: '🌍', title: 'Transparență Totală', desc: 'Fiecare acțiune înregistrată on-chain — partajează linkuri doar pentru citire cu oricine' },
    ],
    perfectForTitle: 'Perfect Pentru',
    perfectFor: [
      { icon: '🏛️', title: 'DAO-uri și Trezorerii', desc: 'Gestionează fondurile comunității cu o guvernanță transparentă cu semnături multiple' },
      { icon: '👥', title: 'Echipe și Startup-uri', desc: 'Securizează trezoreria companiei cu acces bazat pe roluri' },
      { icon: '💼', title: 'Vesting pentru Angajați', desc: 'Vesting de tokenuri pe 4 ani cu cliff de 1 an, complet automatizat' },
      { icon: '🤝', title: 'Servicii de Custodie', desc: 'Acord reciproc 2-din-2 pentru tranzacții sigure' },
      { icon: '🎁', title: 'Granturi și Salarizare', desc: 'Distribuții în masă de tokenuri cu eliberări programate' },
      { icon: '📊', title: 'Fonduri de Investiții', desc: 'Aprobare prin comitet pentru gestionarea fondului' },
    ],
    liveTitle: 'Activ pe Testnet-ul Stellar',
    liveDesc:
      'Orion Safe este în prezent activ pe testnet-ul Stellar. Încearcă-l acum cu tokenuri de test! ' +
      'Lansarea pe mainnet este planificată pentru Q4 2026 după auditul de securitate.',
  },

  quickstart: {
    heading: 'Ghid de Pornire Rapidă',
    subtitle: 'Pune în funcțiune primul tău seif în mai puțin de 5 minute.',
    step1Title: 'Conectează-ți Portofelul',
    step1Intro: 'Apasă pe **„Conectează Portofelul"** în colțul din dreapta sus și selectează portofelul preferat:',
    wallets: [
      { name: 'Freighter', note: 'Recomandat' },
      { name: 'Lobstr', note: 'Prietenos cu mobilul' },
      { name: 'xBull', note: 'Utilizatori avansați' },
      { name: 'Albedo', note: 'Bazat pe web' },
    ],
    noWalletTitle: 'Nu ai un portofel?',
    noWalletDesc: 'Instalează {{freighter}} — este o extensie gratuită de browser care se configurează în 2 minute.',
    step2Title: 'Creează-ți Seiful',
    step2Items: [
      'Apasă pe **„Creează Seif"**',
      'Dă un nume seifului tău (ex. „Trezoreria Echipei")',
      'Adaugă adresele portofelelor semnatarilor (persoanele care pot aproba tranzacțiile)',
      'Stabilește-ți **pragul** — câte aprobări sunt necesare',
    ],
    exampleLabel: 'Exemplu: Semnături Multiple 2-din-3',
    approvedLabel: '2/3 = Aprobat!',
    step3Title: 'Alimentează-ți Seiful',
    step3Intro: 'Seiful tău are propria adresă. Trimite-i tokenuri ca oricărui portofel Stellar:',
    step3Items: [
      'Copiază adresa seifului tău din panou',
      'Trimite XLM, USDC sau orice token Stellar la acea adresă',
      'Fondurile apar în ~5 secunde',
    ],
    proTipTitle: 'Sfat Profesionist',
    proTipDesc: 'Pentru testnet, obține XLM de test gratuit de la {{friendbot}}.',
    step4Title: 'Efectuează Prima Ta Tranzacție',
    step4Steps: [
      { title: 'Creează Propunere', desc: 'Mergi la Tranzacții → Nouă → Introdu detaliile → Trimite' },
      { title: 'Colectează Aprobări', desc: 'Ceilalți semnatari verifică și apasă pe „Aprobă"' },
      { title: 'Execută', desc: 'Odată ce pragul este atins, oricine poate apăsa pe „Execută"' },
    ],
    doneTitle: '🎉 Asta e tot!',
    doneDesc:
      'Acum ai un seif sigur cu semnături multiple. Explorează bara laterală pentru a descoperi blocări temporale, ' +
      'programe de vesting și funcții mai avansate.',
  },

  features: {
    heading: 'Funcții Principale',
    multiSig: {
      title: 'Securitate cu Semnături Multiple',
      desc: 'Solicită ca mai multe persoane să aprobe tranzacțiile. Tu alegi pragul — fie 2-din-3 pentru o echipă mică, fie 5-din-9 pentru un DAO mare.',
      configs: ['2-din-3', '3-din-5', '4-din-7', '5-din-9'],
    },
    proposal: {
      title: 'Flux Bazat pe Propuneri',
      desc: 'Toate tranzacțiile trec printr-un proces transparent de propunere. Fără surprize, cu responsabilitate deplină.',
      steps: [
        { title: 'Propune', sub: 'Orice semnatar' },
        { title: 'Aprobă', sub: 'Atinge pragul' },
        { title: 'Execută', sub: 'Oricine' },
      ],
    },
    txTypes: {
      title: 'Tipuri de Tranzacții',
      items: [
        { icon: '💸', title: 'Transfer', desc: 'Trimite tokenuri imediat după aprobare. Plăți simple și directe.' },
        { icon: '🔒', title: 'Blocare Temporală', desc: 'Blochează tokenuri până la o dată specifică. Perfect pentru custodie sau eliberări programate.' },
        { icon: '📈', title: 'Vesting', desc: 'Eliberare treptată în timp cu cliff opțional. Ideal pentru tokenuri de angajați.' },
      ],
    },
    dashboard: {
      title: 'Navigarea Panoului',
      views: [
        { name: 'Panou', desc: 'Prezentare generală și statistici' },
        { name: 'Active', desc: 'Solduri de tokenuri' },
        { name: 'Tranzacții', desc: 'Propuneri și istoric' },
        { name: 'Membri', desc: 'Semnatari și roluri' },
        { name: 'Blocări Temporale', desc: 'Eliberări programate' },
        { name: 'Vesting', desc: 'Vesting de tokenuri' },
        { name: 'Contacte', desc: 'Agendă de adrese' },
        { name: 'Setări', desc: 'Configurare' },
      ],
    },
    publicAccess: {
      title: 'Acces Public și Partajare',
      cards: [
        { title: '🔗 Link de Vizualizare Publică', desc: 'Partajează o vizualizare doar pentru citire cu investitori, auditori sau publicul. Pot vedea soldurile și activitatea, dar nu pot întreprinde nicio acțiune.' },
        { title: '🎁 Link de Revendicare', desc: 'Beneficiarii își pot revendica tokenurile blocate sau dobândite direct folosind propriul portofel — fără a fi nevoie de acces la seif.' },
      ],
    },
  },

  roles: {
    heading: 'Roluri și Permisiuni',
    intro: 'Orion Safe folosește un sistem bazat pe roluri pentru a controla cine ce poate face. Acest lucru oferă flexibilitate menținând securitatea.',
    cards: [
      { name: 'SuperAdmin', badge: 'Control Total', desc: 'Control complet asupra seifului. SuperAdminii pot face orice, inclusiv acțiuni care afectează structura și securitatea seifului.', canLabel: 'Poate:', can: 'Adăuga/elimina semnatari, schimba pragul de aprobare, anula orice blocare revocabilă, actualiza setările seifului, plus tot ce pot face Adminii și Executorii.' },
      { name: 'Admin', badge: 'Operațiuni', desc: 'Manager al operațiunilor de zi cu zi. Adminii gestionează majoritatea activităților de trezorerie, dar nu pot schimba setările de securitate ale seifului.', canLabel: 'Poate:', can: 'Crea propuneri, aproba tranzacții, executa tranzacții aprobate, crea blocări temporale și programe de vesting, gestiona contacte.' },
      { name: 'Executor', badge: 'Aprobă și Execută', desc: 'Autoritate de aprobare. Executorii pot vota propuneri și executa tranzacții aprobate, dar nu pot iniția altele noi.', canLabel: 'Poate:', can: 'Aproba sau respinge propuneri, executa tranzacții care au atins pragul.' },
      { name: 'Viewer', badge: 'Doar Citire', desc: 'Acces de observator. Viewerii pot vedea totul, dar nu pot întreprinde nicio acțiune. Perfect pentru auditori sau părți interesate.', canLabel: 'Poate:', can: 'Vizualiza soldurile seifului, istoricul tranzacțiilor, propunerile, blocările și toată activitatea.' },
    ],
    matrixTitle: 'Rezumatul Permisiunilor',
    matrixHeaders: { action: 'Acțiune', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Vizualizare seif și solduri', super: true, admin: true, exec: true, view: true },
      { action: 'Creare propuneri', super: true, admin: true, exec: false, view: false },
      { action: 'Aprobare propuneri', super: true, admin: true, exec: true, view: false },
      { action: 'Executare tranzacții', super: true, admin: true, exec: true, view: false },
      { action: 'Creare blocări temporale / vesting', super: true, admin: true, exec: false, view: false },
      { action: 'Anulare blocări revocabile', super: true, admin: false, exec: false, view: false },
      { action: 'Adăugare/eliminare semnatari', super: true, admin: false, exec: false, view: false },
      { action: 'Schimbare prag', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Bună Practică: Atribuirea Rolurilor',
    bestPractice: [
      'Limitează SuperAdmin la 1-2 persoane de încredere (fondatori, directori)',
      'Folosește Admin pentru membrii echipei financiare care gestionează operațiunile zilnice',
      'Folosește Executor pentru membrii consiliului care doar aprobă, nu inițiază',
      'Folosește Viewer pentru părți interesate, auditori sau transparență publică',
    ],
  },

  locks: {
    heading: 'Blocări Temporale și Vesting',
    intro: 'Controlează când devin disponibile tokenurile. Fie că ai nevoie de custodie, plăți programate sau vesting de tokenuri pentru angajați — te-am acoperit.',
    timeLockTitle: 'Blocări Temporale',
    timeLockDesc: 'Blochează tokenuri până la o dată specifică. Beneficiarul poate revendica **suma totală** doar după ce trece momentul deblocării. Înainte de acea dată, tokenurile sunt complet inaccesibile.',
    timeLockExampleLabel: 'Exemplu: Depozit în Custodie',
    timeLockExampleAmount: '10.000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Custodie', desc: 'Reține fondurile până la îndeplinirea condițiilor' },
      { icon: '🎯', title: 'Plăți pe Etape', desc: 'Eliberează când livrabilul este finalizat' },
      { icon: '🏦', title: 'Obiective de Economisire', desc: 'Previne retragerile impulsive' },
    ],
    vestingTitle: 'Programe de Vesting',
    vestingDesc: 'Eliberează tokenuri **treptat în timp** cu o perioadă de cliff opțională. Este standardul din industrie pentru remunerația angajaților și alocările către investitori.',
    vestingExampleLabel: 'Exemplu: Vesting de Angajat pe 4 Ani cu Cliff de 1 An',
    vestingExampleAmount: '100.000 tokenuri',
    vestingBarCliff: 'Cliff (1 an)',
    vestingBarLinear: 'Vesting Liniar → 100%',
    vestingTimeline: { start: 'Început', cliff: 'Cliff: se deblochează 25%', y2: 'Anul 2: 50%', y3: 'Anul 3: 75%', y4: 'Anul 4: 100%' },
    howVestingTitle: 'Cum Funcționează Vestingul',
    howVestingSteps: [
      { title: 'Perioada de Cliff:', desc: 'Nimic nu se dobândește până la data cliff-ului. Dacă cineva pleacă înainte de cliff, nu primește nimic.' },
      { title: 'Deblocarea Cliff-ului:', desc: 'La data cliff-ului, o porțiune se deblochează imediat (de obicei 25% pentru un program de 4 ani).' },
      { title: 'Vesting Liniar:', desc: 'După cliff, tokenurile se dobândesc continuu până la data finală.' },
      { title: 'Revendică Oricând:', desc: 'Beneficiarii își pot revendica tokenurile dobândite oricând doresc — fără termene-limită.' },
    ],
    revTitle: 'Revocabil vs. Nerevocabil',
    revocable: { title: '✓ Revocabil', desc: 'SuperAdmin poate anula blocarea și returna tokenurile nedobândite în seif.', bestFor: 'Cel mai potrivit pentru: Vesting de angajați (cu clauză de încetare), granturi condiționate, alocări interne' },
    nonRevocable: { title: '✗ Nerevocabil', desc: 'Nu poate fi anulat după creare. Tokenurile sunt garantate beneficiarului indiferent de situație.', bestFor: 'Cel mai potrivit pentru: Alocări către investitori, granturi irevocabile, custodie fără încredere, tokenuri pentru consultanți' },
    bulkTitle: 'Creare în Masă',
    bulkDesc: 'Trebuie să creezi multe blocări deodată? Folosește funcția de încărcare în masă cu un fișier CSV. Perfect pentru distribuții de tokenuri în echipă, salarizare sau programe de granturi.',
    bulkPrepLabel: 'Pur și simplu pregătește o foaie de calcul cu:',
    bulkFields: [
      'Adresa portofelului beneficiarului',
      'Cantitatea de tokenuri',
      'Data deblocării (pentru blocări temporale) sau parametrii de vesting',
      'Dacă este revocabil',
      'Descriere opțională',
    ],
    bulkNote: 'Încarcă fișierul CSV, verifică intrările și creează până la 10 blocări per lot.',
  },

  tokens: {
    heading: 'Tokenuri Acceptate',
    usdcTitle: 'USDC Nativ pe Stellar',
    usdcSubtitle: 'Stablecoin-ul oficial al Circle — neîmpachetat, fără punte',
    usdcDesc: 'Orion Safe oferă suport de primă clasă pentru USDC. Creează seifuri denominate în dolari, configurează vesting de salarii în monedă stabilă sau blochează fonduri de custodie fără risc de volatilitate.',
    allTitle: 'Toate Activele Acceptate',
    allIntro: 'Orion Safe acceptă **orice token din rețeaua Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Tokenul nativ al Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Stablecoin al dolarului american' },
      { emoji: '💶', name: 'EURC', desc: 'Stablecoin al euro' },
      { emoji: '🪙', name: 'Orice Token', desc: 'Active Stellar personalizate' },
    ],
    whatTitle: 'Ce Poți Face cu Tokenurile',
    whatItems: [
      { icon: '💸', title: 'Transferuri cu Semnături Multiple', desc: 'Trimite orice token cu aprobare prin semnături multiple' },
      { icon: '🔒', title: 'Blochează Orice Activ', desc: 'Blochează USDC, XLM sau tokenuri personalizate până la o dată specifică' },
      { icon: '📈', title: 'Vesting de Tokenuri', desc: 'Creează programe de vesting pentru orice activ Stellar' },
      { icon: '📊', title: 'Distribuții în Masă', desc: 'Distribuie tokenuri către mai mulți destinatari prin CSV' },
    ],
    testTitle: 'Obținerea de Tokenuri Testnet',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Mergi la {{laboratory}}',
      'Introdu adresa portofelului tău de testnet',
      'Apasă pe „Fund account with Friendbot"',
      'Primește instantaneu 10.000 XLM de test!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Adaugă trustline USDC în portofelul tău (Freighter → Manage Assets → Add USDC)',
      'Folosește un faucet USDC de testnet sau schimbă XLM pe DEX-ul de testnet',
    ],
  },

  architecture: {
    heading: 'Cum Funcționează',
    intro: 'O explicație simplă a ceea ce se întâmplă în culise când folosești Orion Safe.',
    basicsTitle: 'Noțiuni de Bază',
    basicsParas: [
      'Când creezi un seif, Orion Safe implementează un **contract inteligent** pe blockchain-ul Stellar. Acest contract inteligent este ca o cutie de valori programabilă care îți păstrează activele.',
      'Contractul inteligent impune toate regulile: cine poate propune tranzacții, câte aprobări sunt necesare, când pot fi eliberate tokenurile blocate și altele. **Nimeni nu poate ocoli aceste reguli** — nici măcar echipa Orion Safe.',
    ],
    flowTitle: 'Ce Se Întâmplă Când Trimiți Tokenuri',
    flowSteps: [
      { title: 'Creezi o Propunere', desc: 'Specifică destinatarul, suma și un memo opțional. Propunerea este înregistrată pe blockchain.' },
      { title: 'Ceilalți Semnatari Aprobă', desc: 'Fiecare aprobare este înregistrată on-chain. Toată lumea poate vedea cine a aprobat.' },
      { title: 'Prag Atins', desc: 'Odată ce suficienți semnatari aprobă (ex. 2 din 3), tranzacția este gata de executat.' },
      { title: 'Execută și Confirmă', desc: 'Oricine poate declanșa executarea. Tokenurile se mută instantaneu (~5 secunde). Gata!' },
    ],
    whyTitle: 'De Ce Am Construit pe Stellar',
    whyItems: [
      { icon: '⚡', title: 'Rapid', desc: 'Tranzacțiile se confirmă în ~5 secunde' },
      { icon: '💰', title: 'Ieftin', desc: 'Mai puțin de 0,0001 $ per tranzacție' },
      { icon: '🏦', title: 'De Încredere', desc: 'Folosit de Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Sigur', desc: 'Rețea testată în practică din 2015' },
      { icon: '💵', title: 'USDC Nativ', desc: 'Stablecoin-uri reale, nu tokenuri împachetate' },
      { icon: '🌍', title: 'Global', desc: 'Funcționează oriunde cu acces la internet' },
    ],
    truthTitle: 'Important: Blockchain-ul Este Sursa Adevărului',
    truthDesc: 'Seiful tău există pe blockchain-ul Stellar, nu pe serverele noastre. Chiar dacă site-ul nostru ar deveni inaccesibil, seiful și fondurile tale ar rămâne în siguranță și accesibile prin alte instrumente Stellar. Noi doar oferim o interfață ușor de utilizat pentru a interacționa cu seiful tău on-chain.',
  },

  security: {
    heading: 'Securitate',
    intro: 'Cum păstrează Orion Safe activele tale în siguranță.',
    principlesTitle: 'Principii Fundamentale de Securitate',
    principles: [
      { title: 'Impunere On-Chain', desc: 'Toate regulile sunt impuse de contractul inteligent pe blockchain. Site-ul este doar o interfață de utilizator — blockchain-ul este autoritatea.' },
      { title: 'Fără Uși Ascunse', desc: 'Nimeni — nici măcar echipa Orion Safe — nu poate accesa seiful tău sau muta fondurile tale fără semnăturile corespunzătoare.' },
      { title: 'Semnături Multiple în Mod Implicit', desc: 'Chiar dacă o cheie este compromisă, atacatorii nu pot muta fonduri fără a atinge pragul tău de aprobare.' },
    ],
    threatsTitle: 'Cum Protejăm Împotriva Amenințărilor',
    threats: [
      { threat: 'Cheie de semnatar compromisă', mitigation: 'Pragul cu semnături multiple previne atacurile cu o singură cheie. Ceilalți semnatari pot elimina cheia compromisă.' },
      { threat: 'Propunere malițioasă', mitigation: 'Necesită aprobări multiple. Ceilalți semnatari pot respinge propunerile rele.' },
      { threat: 'Chei pierdute', mitigation: 'Atâta timp cât semnatarii rămași ating pragul, seiful rămâne accesibil.' },
      { threat: 'Site-ul devine inaccesibil', mitigation: 'Seiful tău există pe blockchain. Accesează-l prin alte instrumente Stellar.' },
      { threat: 'Breșă în baza de date', mitigation: 'Baza noastră de date este doar un cache pentru încărcare mai rapidă. Blockchain-ul este sursa adevărului.' },
    ],
    bestTitle: 'Bune Practici de Securitate',
    doTitle: '✓ Fă',
    dos: [
      'Folosește portofele hardware (precum Ledger) pentru cheile semnatarilor',
      'Menține pragul la 2 sau mai mult (niciodată un singur semnatar)',
      'Verifică regulat lista ta de semnatari',
      'Folosește seifuri separate pentru scopuri diferite',
      'Testează mai întâi cu sume mici',
      'Fă o copie de rezervă sigură a frazelor tale de recuperare',
    ],
    dontTitle: '✗ Nu Face',
    donts: [
      'Partaja cheile private prin e-mail sau chat',
      'Folosi aceeași cheie pentru mai multe seifuri critice',
      'Ignora propunerile în așteptare prea mult timp',
      'Seta pragul egal cu numărul total de semnatari (fără redundanță)',
      'Stoca frazele de recuperare digital necriptate',
      'Acorda acces SuperAdmin persoanelor în care nu ai încredere deplină',
    ],
    statusTitle: 'Stare de Securitate',
    statuses: [
      { color: 'green', text: 'Construit pe rețeaua Stellar testată în practică (din 2015)' },
      { color: 'green', text: 'Integrarea framework-ului Smart Account de la OpenZeppelin' },
      { color: 'yellow', text: 'Audit de securitate profesional planificat înainte de mainnet (Q4 2026)' },
      { color: 'gray', text: 'Program de recompense pentru erori după lansarea pe mainnet' },
    ],
  },

  roadmap: {
    heading: 'Foaie de Parcurs',
    liveTitle: 'În Prezent Activ pe Testnet',
    liveFeatures: ['Seifuri cu semnături multiple', 'Acces bazat pe roluri', 'Blocări temporale', 'Programe de vesting', 'Import în masă CSV', 'Linkuri de vizualizare publică', 'Portal de revendicare', 'Suport pentru multiple portofele'],
    phases: [
      { color: 'purple', title: 'Faza 1: Pregătire pentru Producție', target: 'Țintă: Iulie 2026', items: ['Pregătirea implementării pe mainnet', 'Întărirea securității și testare', 'Optimizarea performanței', 'Gestionarea îmbunătățită a erorilor'] },
      { color: 'blue', title: 'Faza 2: Funcții Avansate', target: 'Țintă: Septembrie 2026', items: ['Limite de cheltuieli (plafoane zilnice/săptămânale/lunare)', 'Șabloane de vesting îmbunătățite', 'Opțiuni avansate de propuneri', 'Experiență mobilă îmbunătățită'] },
      { color: 'cyan', title: 'Faza 3: Lansarea pe Mainnet', target: 'Țintă: Noiembrie 2026', items: ['Audit de securitate profesional', 'Integrare cu DEX-ul Stellar (tranzacționare în seif)', 'SDK pentru dezvoltatori', 'Ghiduri și tutoriale complete pentru utilizatori', '🚀 **Implementare pe mainnet**'] },
    ],
    futureTitle: 'Viziune de Viitor (2027+)',
    future: [
      { title: 'Integrare DeFi', desc: 'Strategii de randament, protocoale de creditare, furnizare de lichiditate' },
      { title: 'Suită pentru Întreprinderi', desc: 'Opțiuni white-label, SSO, raportare de conformitate' },
      { title: 'Automatizare', desc: 'Plăți recurente programate, condiții inteligente' },
      { title: 'Integrări', desc: 'API, webhook-uri, conexiuni cu software de contabilitate' },
    ],
    followTitle: 'Urmărește Progresul Nostru',
    followDesc: 'Construim în mod public. Urmărește depozitul nostru GitHub pentru actualizări sau revino aici pentru cele mai recente noutăți.',
  },

  faq: {
    heading: 'Întrebări Frecvente',
    items: [
      { q: 'Este Orion Safe gratuit?', a: 'Da! Platforma este gratuită. Plătești doar taxele standard ale rețelei Stellar (mai puțin de 0,0001 $ per tranzacție) plus un mic depozit unic la crearea unui seif.' },
      { q: 'Ce se întâmplă dacă îmi pierd cheia privată?', a: 'Atâta timp cât semnatarii rămași ating pragul de aprobare, seiful rămâne complet accesibil. De exemplu, într-un seif 2-din-3, dacă o cheie este pierdută, ceilalți 2 semnatari pot opera în continuare seiful și chiar adăuga un semnatar înlocuitor.' },
      { q: 'Poate echipa Orion Safe accesa fondurile mele?', a: 'Nu. Seiful tău este un contract inteligent pe blockchain-ul Stellar. Doar semnatarii pe care îi adaugi pot autoriza tranzacții. Nu avem acces special, uși ascunse sau chei de administrator la seiful tău.' },
      { q: 'Ce tokenuri pot stoca?', a: 'Orice activ Stellar: XLM (nativ), USDC, EURC și mii de alte tokenuri emise în rețeaua Stellar.' },
      { q: 'Cât de rapide sunt tranzacțiile?', a: 'Aproximativ 5 secunde după executare. Procesul de aprobare depinde de cât de repede răspund semnatarii tăi.' },
      { q: 'Pot anula o blocare temporală sau un program de vesting?', a: 'Doar dacă a fost creat ca „revocabil". Blocările nerevocabile nu pot fi anulate după creare — tokenurile sunt garantate beneficiarului.' },
      { q: 'Există o aplicație mobilă?', a: 'Panoul este complet responsiv și funcționează excelent în browserele mobile. Folosește-l cu portofele mobile precum Lobstr sau conectează-te prin WalletConnect.' },
      { q: 'Ce se întâmplă dacă site-ul devine inaccesibil?', a: 'Seiful tău există pe blockchain-ul Stellar, nu pe serverele noastre. Poți interacționa cu el folosind Stellar Laboratory sau orice instrument compatibil, chiar dacă site-ul nostru este indisponibil.' },
      { q: 'Cum își revendică beneficiarii tokenurile?', a: 'Partajează un link de revendicare cu ei (găsit în Setări → Partajare). Își conectează propriul portofel și revendică direct — fără a fi nevoie de acces la seif.' },
      { q: 'Există o limită pentru numărul de semnatari?', a: 'În prezent acceptă până la 10 semnatari per seif. Ai nevoie de mai mulți? Contactează-ne pentru soluții pentru întreprinderi.' },
      { q: 'Care este diferența dintre testnet și mainnet?', a: 'Testnet folosește tokenuri false pentru testare — fără valoare reală. Mainnet folosește tokenuri reale și bani reali. În prezent suntem pe testnet, cu lansarea pe mainnet planificată pentru Q4 2026.' },
      { q: 'Cum obțin ajutor dacă ceva nu merge bine?', a: 'Consultă mai întâi această documentație. Dacă tot ai nevoie de ajutor, deschide un issue în depozitul nostru GitHub sau contactează-ne prin canalele noastre.' },
    ],
  },

  common: {
    locked: '🔒 Blocat',
    claimable: '✓ Revendicabil',
    today: 'Astăzi',
    unlockDate: '⏰ Data Deblocării',
    claimed: 'Revendicat',
    viewOnGithub: 'Vezi pe GitHub',
  },
};
