import { DocsContent } from './types';

export const docsSw: DocsContent = {
  sidebarTitle: 'Nyaraka',
  sections: [
    { id: 'overview', title: 'Muhtasari', description: 'Orion Safe ni nini?' },
    { id: 'quickstart', title: 'Anza Haraka', description: 'Mwongozo wa usanidi wa dakika 5' },
    { id: 'features', title: 'Vipengele Vikuu', description: 'Unachoweza kufanya' },
    { id: 'roles', title: 'Majukumu na Ruhusa', description: 'Nani anaweza kufanya nini' },
    { id: 'locks', title: 'Vifungo vya Muda na Ugawaji', description: 'Panga utoaji wa tokeni' },
    { id: 'tokens', title: 'Tokeni Zinazoungwa Mkono', description: 'USDC, XLM na zaidi' },
    { id: 'architecture', title: 'Jinsi Inavyofanya Kazi', description: 'Ndani ya pazia' },
    { id: 'security', title: 'Usalama', description: 'Jinsi tunavyokulinda' },
    { id: 'faq', title: 'Maswali Yanayoulizwa Mara kwa Mara', description: 'Maswali ya kawaida' },
    { id: 'roadmap', title: 'Ramani ya Maendeleo', description: 'Kinachokuja' },
  ],

  overview: {
    heading: 'Karibu Orion Safe',
    intro:
      'Orion Safe ni **jukwaa la hazina la saini nyingi** lililojengwa juu ya Stellar. ' +
      'Fikiria kama akaunti ya benki inayoshirikiwa kwa timu yako, DAO, au shirika lako — lakini ikiwa na uwezo wa ziada.',
    whyTitle: 'Kwa Nini Utumie Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Hakuna Hatua Moja ya Kushindwa', desc: 'Idhini nyingi zinahitajika — hata kama ufunguo mmoja utadukuliwa, fedha zinabaki salama' },
      { emoji: '⚡', title: 'Haraka na Nafuu', desc: 'Miamala ya sekunde ~5, chini ya $0.0001 kwa kila muamala' },
      { emoji: '⏰', title: 'Vidhibiti vya Muda', desc: 'Funga tokeni hadi tarehe fulani, au zitoe taratibu kwa muda' },
      { emoji: '🌍', title: 'Uwazi Kamili', desc: 'Kila kitendo kinarekodiwa kwenye mnyororo — shiriki viungo vya kusoma tu na mtu yeyote' },
    ],
    perfectForTitle: 'Inafaa Kwa',
    perfectFor: [
      { icon: '🏛️', title: 'DAO na Hazina', desc: 'Simamia fedha za jamii kwa utawala wa saini nyingi wenye uwazi' },
      { icon: '👥', title: 'Timu na Kampuni Changa', desc: 'Linda hazina ya kampuni kwa ufikiaji unaotegemea majukumu' },
      { icon: '💼', title: 'Ugawaji wa Wafanyakazi', desc: 'Ugawaji wa tokeni wa miaka 4 wenye kipindi cha mwaka 1, ulioendeshwa kiotomatiki kabisa' },
      { icon: '🤝', title: 'Huduma za Esikrow', desc: 'Makubaliano ya pande mbili ya 2-kati-ya-2 kwa miamala salama' },
      { icon: '🎁', title: 'Ruzuku na Mishahara', desc: 'Mgawanyo wa tokeni kwa wingi wenye utoaji uliopangwa' },
      { icon: '📊', title: 'Mifuko ya Uwekezaji', desc: 'Idhini ya kamati kwa usimamizi wa mfuko' },
    ],
    liveTitle: 'Hai kwenye Mtandao wa Majaribio wa Stellar',
    liveDesc:
      'Orion Safe kwa sasa iko hai kwenye mtandao wa majaribio wa Stellar. Ijaribu sasa kwa tokeni za majaribio! ' +
      'Uzinduzi wa mtandao mkuu umepangwa kwa robo ya 4 ya 2026 baada ya ukaguzi wa usalama.',
  },

  quickstart: {
    heading: 'Mwongozo wa Kuanza Haraka',
    subtitle: 'Endesha hazina yako ya kwanza ndani ya dakika chini ya 5.',
    step1Title: 'Unganisha Pochi Yako',
    step1Intro: 'Bofya **"Unganisha Pochi"** kwenye kona ya juu kulia na uchague pochi unayopendelea:',
    wallets: [
      { name: 'Freighter', note: 'Inapendekezwa' },
      { name: 'Lobstr', note: 'Rafiki kwa simu' },
      { name: 'xBull', note: 'Watumiaji wa hali ya juu' },
      { name: 'Albedo', note: 'Inategemea wavuti' },
    ],
    noWalletTitle: 'Huna pochi?',
    noWalletDesc: 'Sakinisha {{freighter}} — ni kiendelezi cha bure cha kivinjari kinachochukua dakika 2 kusanidi.',
    step2Title: 'Unda Hazina Yako',
    step2Items: [
      'Bofya **"Unda Hazina"**',
      'Ipe hazina yako jina (mfano, "Hazina ya Timu")',
      'Ongeza anwani za pochi za wasaini (watu wanaoweza kuidhinisha miamala)',
      'Weka **kizingiti** chako — idhini ngapi zinahitajika',
    ],
    exampleLabel: 'Mfano: Saini Nyingi 2-kati-ya-3',
    approvedLabel: '2/3 = Imeidhinishwa!',
    step3Title: 'Weka Fedha kwenye Hazina Yako',
    step3Intro: 'Hazina yako ina anwani yake mwenyewe. Tuma tokeni kwake kama pochi yoyote ya Stellar:',
    step3Items: [
      'Nakili anwani ya hazina yako kutoka kwenye dashibodi',
      'Tuma XLM, USDC, au tokeni yoyote ya Stellar kwa anwani hiyo',
      'Fedha zinaonekana ndani ya sekunde ~5',
    ],
    proTipTitle: 'Kidokezo cha Kitaalam',
    proTipDesc: 'Kwa mtandao wa majaribio, pata XLM ya majaribio bila malipo kutoka {{friendbot}}.',
    step4Title: 'Fanya Muamala Wako wa Kwanza',
    step4Steps: [
      { title: 'Unda Pendekezo', desc: 'Nenda Miamala → Mpya → Ingiza maelezo → Wasilisha' },
      { title: 'Kusanya Idhini', desc: 'Wasaini wengine wanapitia na kubofya "Idhinisha"' },
      { title: 'Tekeleza', desc: 'Mara kizingiti kinapofikiwa, mtu yeyote anaweza kubofya "Tekeleza"' },
    ],
    doneTitle: '🎉 Ndivyo ilivyo!',
    doneDesc:
      'Sasa una hazina salama ya saini nyingi. Chunguza upau wa kando ili kugundua vifungo vya muda, ' +
      'ratiba za ugawaji, na vipengele vya hali ya juu zaidi.',
  },

  features: {
    heading: 'Vipengele Vikuu',
    multiSig: {
      title: 'Usalama wa Saini Nyingi',
      desc: 'Hitaji watu wengi kuidhinisha miamala. Wewe huchagua kizingiti — iwe ni 2-kati-ya-3 kwa timu ndogo au 5-kati-ya-9 kwa DAO kubwa.',
      configs: ['2-kati-ya-3', '3-kati-ya-5', '4-kati-ya-7', '5-kati-ya-9'],
    },
    proposal: {
      title: 'Mtiririko Unaotegemea Mapendekezo',
      desc: 'Miamala yote hupitia mchakato wa pendekezo wenye uwazi. Hakuna mshangao, uwajibikaji kamili.',
      steps: [
        { title: 'Pendekeza', sub: 'Msaini yeyote' },
        { title: 'Idhinisha', sub: 'Fikia kizingiti' },
        { title: 'Tekeleza', sub: 'Mtu yeyote' },
      ],
    },
    txTypes: {
      title: 'Aina za Miamala',
      items: [
        { icon: '💸', title: 'Uhamisho', desc: 'Tuma tokeni mara moja baada ya idhini. Malipo rahisi, ya moja kwa moja.' },
        { icon: '🔒', title: 'Kifungo cha Muda', desc: 'Funga tokeni hadi tarehe fulani. Inafaa kwa esikrow au utoaji uliopangwa.' },
        { icon: '📈', title: 'Ugawaji', desc: 'Utoaji wa taratibu kwa muda wenye kipindi cha hiari. Bora kwa tokeni za wafanyakazi.' },
      ],
    },
    dashboard: {
      title: 'Urambazaji wa Dashibodi',
      views: [
        { name: 'Dashibodi', desc: 'Muhtasari na takwimu' },
        { name: 'Mali', desc: 'Salio za tokeni' },
        { name: 'Miamala', desc: 'Mapendekezo na historia' },
        { name: 'Wanachama', desc: 'Wasaini na majukumu' },
        { name: 'Vifungo vya Muda', desc: 'Utoaji uliopangwa' },
        { name: 'Ugawaji', desc: 'Ugawaji wa tokeni' },
        { name: 'Anwani', desc: 'Kitabu cha anwani' },
        { name: 'Mipangilio', desc: 'Usanidi' },
      ],
    },
    publicAccess: {
      title: 'Ufikiaji wa Umma na Kushiriki',
      cards: [
        { title: '🔗 Kiungo cha Mwonekano wa Umma', desc: 'Shiriki mwonekano wa kusoma tu na wawekezaji, wakaguzi, au umma. Wanaweza kuona salio na shughuli lakini hawawezi kuchukua hatua zozote.' },
        { title: '🎁 Kiungo cha Kudai', desc: 'Wanufaika wanaweza kudai tokeni zao zilizofungwa au zilizogawanywa moja kwa moja wakitumia pochi zao wenyewe — bila kuhitaji ufikiaji wa hazina.' },
      ],
    },
  },

  roles: {
    heading: 'Majukumu na Ruhusa',
    intro: 'Orion Safe hutumia mfumo unaotegemea majukumu kudhibiti nani anaweza kufanya nini. Hii hutoa unyumbufu huku ikidumisha usalama.',
    cards: [
      { name: 'SuperAdmin', badge: 'Udhibiti Kamili', desc: 'Udhibiti kamili wa hazina. SuperAdmins wanaweza kufanya kila kitu, ikiwa ni pamoja na vitendo vinavyoathiri muundo na usalama wa hazina.', canLabel: 'Anaweza:', can: 'Kuongeza/kuondoa wasaini, kubadilisha kizingiti cha idhini, kughairi kifungo chochote kinachoweza kughairiwa, kusasisha mipangilio ya hazina, pamoja na kila kitu ambacho Admins na Executors wanaweza kufanya.' },
      { name: 'Admin', badge: 'Uendeshaji', desc: 'Meneja wa uendeshaji wa kila siku. Admins hushughulikia shughuli nyingi za hazina lakini hawawezi kubadilisha mipangilio ya usalama ya hazina.', canLabel: 'Anaweza:', can: 'Kuunda mapendekezo, kuidhinisha miamala, kutekeleza miamala iliyoidhinishwa, kuunda vifungo vya muda na ratiba za ugawaji, kusimamia anwani.' },
      { name: 'Executor', badge: 'Idhinisha na Tekeleza', desc: 'Mamlaka ya idhini. Executors wanaweza kupiga kura kwenye mapendekezo na kutekeleza miamala iliyoidhinishwa, lakini hawawezi kuanzisha mipya.', canLabel: 'Anaweza:', can: 'Kuidhinisha au kukataa mapendekezo, kutekeleza miamala iliyofikia kizingiti.' },
      { name: 'Viewer', badge: 'Kusoma Tu', desc: 'Ufikiaji wa mtazamaji. Viewers wanaweza kuona kila kitu lakini hawawezi kuchukua hatua zozote. Inafaa kwa wakaguzi au wadau.', canLabel: 'Anaweza:', can: 'Kuona salio za hazina, historia ya miamala, mapendekezo, vifungo, na shughuli zote.' },
    ],
    matrixTitle: 'Muhtasari wa Ruhusa',
    matrixHeaders: { action: 'Kitendo', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Kuona hazina na salio', super: true, admin: true, exec: true, view: true },
      { action: 'Kuunda mapendekezo', super: true, admin: true, exec: false, view: false },
      { action: 'Kuidhinisha mapendekezo', super: true, admin: true, exec: true, view: false },
      { action: 'Kutekeleza miamala', super: true, admin: true, exec: true, view: false },
      { action: 'Kuunda vifungo vya muda / ugawaji', super: true, admin: true, exec: false, view: false },
      { action: 'Kughairi vifungo vinavyoweza kughairiwa', super: true, admin: false, exec: false, view: false },
      { action: 'Kuongeza/kuondoa wasaini', super: true, admin: false, exec: false, view: false },
      { action: 'Kubadilisha kizingiti', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Mazoezi Bora: Ugawaji wa Majukumu',
    bestPractice: [
      'Weka SuperAdmin kwa watu 1-2 wanaoaminika (waanzilishi, wakurugenzi)',
      'Tumia Admin kwa wanachama wa timu ya fedha wanaosimamia shughuli za kila siku',
      'Tumia Executor kwa wanachama wa bodi wanaoidhinisha tu, sio kuanzisha',
      'Tumia Viewer kwa wadau, wakaguzi, au uwazi wa umma',
    ],
  },

  locks: {
    heading: 'Vifungo vya Muda na Ugawaji',
    intro: 'Dhibiti wakati tokeni zinapokuwa zinapatikana. Iwe unahitaji esikrow, malipo yaliyopangwa, au ugawaji wa tokeni za wafanyakazi — tumekushughulikia.',
    timeLockTitle: 'Vifungo vya Muda',
    timeLockDesc: 'Funga tokeni hadi tarehe fulani. Mnufaika anaweza kudai **kiasi kamili** tu baada ya wakati wa kufungua kupita. Kabla ya tarehe hiyo, tokeni hazifikiki kabisa.',
    timeLockExampleLabel: 'Mfano: Amana ya Esikrow',
    timeLockExampleAmount: '10,000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'Esikrow', desc: 'Shikilia fedha hadi masharti yatimizwe' },
      { icon: '🎯', title: 'Malipo ya Hatua', desc: 'Toa wakati kazi inapokamilika' },
      { icon: '🏦', title: 'Malengo ya Akiba', desc: 'Zuia utoaji wa haraka usio na mpangilio' },
    ],
    vestingTitle: 'Ratiba za Ugawaji',
    vestingDesc: 'Toa tokeni **taratibu kwa muda** ikiwa na kipindi cha hiari cha awali. Hii ni kiwango cha sekta kwa fidia ya wafanyakazi na mgawanyo wa wawekezaji.',
    vestingExampleLabel: 'Mfano: Ugawaji wa Mfanyakazi wa Miaka 4 wenye Kipindi cha Mwaka 1',
    vestingExampleAmount: 'tokeni 100,000',
    vestingBarCliff: 'Kipindi (mwaka 1)',
    vestingBarLinear: 'Ugawaji wa Mstari → 100%',
    vestingTimeline: { start: 'Mwanzo', cliff: 'Kipindi: 25% inafunguliwa', y2: 'Mwaka 2: 50%', y3: 'Mwaka 3: 75%', y4: 'Mwaka 4: 100%' },
    howVestingTitle: 'Jinsi Ugawaji Unavyofanya Kazi',
    howVestingSteps: [
      { title: 'Kipindi cha Awali:', desc: 'Hakuna kinachogawanywa hadi tarehe ya kipindi. Mtu akiondoka kabla ya kipindi, hapati chochote.' },
      { title: 'Kufungua kwa Kipindi:', desc: 'Kwenye tarehe ya kipindi, sehemu inafunguliwa mara moja (kwa kawaida 25% kwa ratiba ya miaka 4).' },
      { title: 'Ugawaji wa Mstari:', desc: 'Baada ya kipindi, tokeni hugawanywa kwa kuendelea hadi tarehe ya mwisho.' },
      { title: 'Dai Wakati Wowote:', desc: 'Wanufaika wanaweza kudai tokeni zao zilizogawanywa wakati wowote wanaotaka — hakuna makataa.' },
    ],
    revTitle: 'Inayoweza Kughairiwa dhidi ya Isiyoweza Kughairiwa',
    revocable: { title: '✓ Inayoweza Kughairiwa', desc: 'SuperAdmin anaweza kughairi kifungo na kurudisha tokeni ambazo hazijagawanywa kwenye hazina.', bestFor: 'Bora kwa: Ugawaji wa wafanyakazi (wenye kifungu cha kuachishwa kazi), ruzuku za masharti, mgawanyo wa ndani' },
    nonRevocable: { title: '✗ Isiyoweza Kughairiwa', desc: 'Haiwezi kughairiwa mara baada ya kuundwa. Tokeni zinahakikishiwa kwa mnufaika hata iweje.', bestFor: 'Bora kwa: Mgawanyo wa wawekezaji, ruzuku zisizoweza kughairiwa, esikrow isiyo na uaminifu, tokeni za washauri' },
    bulkTitle: 'Uundaji kwa Wingi',
    bulkDesc: 'Unahitaji kuunda vifungo vingi mara moja? Tumia kipengele cha kupakia kwa wingi kwa faili ya CSV. Inafaa kwa mgawanyo wa tokeni za timu, mishahara, au programu za ruzuku.',
    bulkPrepLabel: 'Andaa tu lahajedwali yenye:',
    bulkFields: [
      'Anwani ya pochi ya mnufaika',
      'Kiasi cha tokeni',
      'Tarehe ya kufungua (kwa vifungo vya muda) au vigezo vya ugawaji',
      'Kama inaweza kughairiwa',
      'Maelezo ya hiari',
    ],
    bulkNote: 'Pakia CSV, kagua maingizo, na uunde hadi vifungo 10 kwa kila kundi.',
  },

  tokens: {
    heading: 'Tokeni Zinazoungwa Mkono',
    usdcTitle: 'USDC Asilia kwenye Stellar',
    usdcSubtitle: 'Sarafu thabiti rasmi ya Circle — sio iliyofungwa, sio iliyounganishwa',
    usdcDesc: 'Orion Safe ina msaada wa daraja la kwanza kwa USDC. Unda hazina zinazopimwa kwa dola, anzisha ugawaji wa mshahara kwa sarafu thabiti, au funga fedha za esikrow bila hatari ya kuyumba.',
    allTitle: 'Mali Zote Zinazoungwa Mkono',
    allIntro: 'Orion Safe inaunga mkono **tokeni yoyote kwenye mtandao wa Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Tokeni asilia ya Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Sarafu thabiti ya Dola ya Marekani' },
      { emoji: '💶', name: 'EURC', desc: 'Sarafu thabiti ya Euro' },
      { emoji: '🪙', name: 'Tokeni Yoyote', desc: 'Mali maalum za Stellar' },
    ],
    whatTitle: 'Unachoweza Kufanya na Tokeni',
    whatItems: [
      { icon: '💸', title: 'Uhamisho wa Saini Nyingi', desc: 'Tuma tokeni yoyote kwa idhini ya saini nyingi' },
      { icon: '🔒', title: 'Funga Mali Yoyote kwa Muda', desc: 'Funga USDC, XLM, au tokeni maalum hadi tarehe fulani' },
      { icon: '📈', title: 'Ugawaji wa Tokeni', desc: 'Unda ratiba za ugawaji kwa mali yoyote ya Stellar' },
      { icon: '📊', title: 'Mgawanyo kwa Wingi', desc: 'Sambaza tokeni kwa wapokeaji wengi kupitia CSV' },
    ],
    testTitle: 'Kupata Tokeni za Mtandao wa Majaribio',
    xlmTitle: '⭐ XLM (Mtandao wa Majaribio)',
    xlmSteps: [
      'Nenda {{laboratory}}',
      'Ingiza anwani ya pochi yako ya mtandao wa majaribio',
      'Bofya "Fund account with Friendbot"',
      'Pokea XLM 10,000 za majaribio papo hapo!',
    ],
    usdcTestTitle: '💵 USDC (Mtandao wa Majaribio)',
    usdcTestSteps: [
      'Ongeza mstari wa uaminifu wa USDC kwenye pochi yako (Freighter → Manage Assets → Add USDC)',
      'Tumia bomba la USDC la mtandao wa majaribio au badilisha XLM kwenye DEX ya mtandao wa majaribio',
    ],
  },

  architecture: {
    heading: 'Jinsi Inavyofanya Kazi',
    intro: 'Maelezo rahisi ya kinachotokea nyuma ya pazia unapotumia Orion Safe.',
    basicsTitle: 'Misingi',
    basicsParas: [
      'Unapounda hazina, Orion Safe husambaza **mkataba mahiri** kwenye mnyororo wa Stellar. Mkataba huu mahiri ni kama sanduku la amana linaloweza kupangwa ambalo hushikilia mali yako.',
      'Mkataba mahiri hutekeleza sheria zote: nani anaweza kupendekeza miamala, idhini ngapi zinahitajika, lini tokeni zilizofungwa zinaweza kutolewa, na zaidi. **Hakuna mtu anayeweza kupita sheria hizi** — hata timu ya Orion Safe.',
    ],
    flowTitle: 'Kinachotokea Unapotuma Tokeni',
    flowSteps: [
      { title: 'Unaunda Pendekezo', desc: 'Bainisha mpokeaji, kiasi, na noti ya hiari. Pendekezo hurekodiwa kwenye mnyororo.' },
      { title: 'Wasaini Wengine Wanaidhinisha', desc: 'Kila idhini hurekodiwa kwenye mnyororo. Kila mtu anaweza kuona nani ameidhinisha.' },
      { title: 'Kizingiti Kimefikiwa', desc: 'Mara wasaini wa kutosha wanapoidhinisha (mfano, 2 kati ya 3), muamala uko tayari kutekelezwa.' },
      { title: 'Tekeleza na Thibitisha', desc: 'Mtu yeyote anaweza kuchochea utekelezaji. Tokeni huhama papo hapo (sekunde ~5). Imekamilika!' },
    ],
    whyTitle: 'Kwa Nini Tulijenga kwenye Stellar',
    whyItems: [
      { icon: '⚡', title: 'Haraka', desc: 'Miamala huthibitishwa katika sekunde ~5' },
      { icon: '💰', title: 'Nafuu', desc: 'Chini ya $0.0001 kwa kila muamala' },
      { icon: '🏦', title: 'Inayoaminika', desc: 'Inatumiwa na Circle, MoneyGram, Franklin Templeton' },
      { icon: '🔐', title: 'Salama', desc: 'Mtandao uliojaribiwa kwa vita tangu 2015' },
      { icon: '💵', title: 'USDC Asilia', desc: 'Sarafu thabiti za kweli, sio tokeni zilizofungwa' },
      { icon: '🌍', title: 'Kimataifa', desc: 'Inafanya kazi popote palipo na ufikiaji wa intaneti' },
    ],
    truthTitle: 'Muhimu: Mnyororo ndio Chanzo cha Ukweli',
    truthDesc: 'Hazina yako ipo kwenye mnyororo wa Stellar, sio kwenye seva zetu. Hata kama tovuti yetu ingezimwa, hazina yako na fedha zako zingebaki salama na zinazoweza kufikiwa kupitia zana zingine za Stellar. Sisi tunatoa tu kiolesura rahisi cha kutumia kuingiliana na hazina yako iliyo kwenye mnyororo.',
  },

  security: {
    heading: 'Usalama',
    intro: 'Jinsi Orion Safe inavyoweka mali yako salama.',
    principlesTitle: 'Kanuni Kuu za Usalama',
    principles: [
      { title: 'Utekelezaji kwenye Mnyororo', desc: 'Sheria zote hutekelezwa na mkataba mahiri kwenye mnyororo. Tovuti ni kiolesura cha mtumiaji tu — mnyororo ndio mamlaka.' },
      { title: 'Hakuna Milango ya Nyuma', desc: 'Hakuna mtu — hata timu ya Orion Safe — anayeweza kufikia hazina yako au kuhamisha fedha zako bila saini sahihi.' },
      { title: 'Saini Nyingi kwa Chaguo-Msingi', desc: 'Hata kama ufunguo mmoja utadukuliwa, washambuliaji hawawezi kuhamisha fedha bila kufikia kizingiti chako cha idhini.' },
    ],
    threatsTitle: 'Jinsi Tunavyolinda Dhidi ya Vitisho',
    threats: [
      { threat: 'Ufunguo wa msaini uliodukuliwa', mitigation: 'Kizingiti cha saini nyingi huzuia mashambulizi ya ufunguo mmoja. Wasaini wengine wanaweza kuondoa ufunguo uliodukuliwa.' },
      { threat: 'Pendekezo lenye nia mbaya', mitigation: 'Linahitaji idhini nyingi. Wasaini wengine wanaweza kukataa mapendekezo mabaya.' },
      { threat: 'Funguo zilizopotea', mitigation: 'Maadamu wasaini waliobaki wanafikia kizingiti, hazina inabaki kufikika.' },
      { threat: 'Tovuti inazimika', mitigation: 'Hazina yako ipo kwenye mnyororo. Ifikie kupitia zana zingine za Stellar.' },
      { threat: 'Uvunjaji wa hifadhidata', mitigation: 'Hifadhidata yetu ni akiba tu kwa upakiaji wa haraka. Mnyororo ndio chanzo cha ukweli.' },
    ],
    bestTitle: 'Mazoezi Bora ya Usalama',
    doTitle: '✓ Fanya',
    dos: [
      'Tumia pochi za vifaa (kama Ledger) kwa funguo za wasaini',
      'Weka kizingiti kwa 2 au zaidi (kamwe usisaini peke yako)',
      'Kagua orodha yako ya wasaini mara kwa mara',
      'Tumia hazina tofauti kwa madhumuni tofauti',
      'Jaribu kwa kiasi kidogo kwanza',
      'Hifadhi nakala za misemo yako ya urejeshaji kwa usalama',
    ],
    dontTitle: '✗ Usifanye',
    donts: [
      'Kushiriki funguo za faragha kupitia barua pepe au gumzo',
      'Kutumia ufunguo sawa kwa hazina nyingi muhimu',
      'Kupuuza mapendekezo yaliyosubiri kwa muda mrefu sana',
      'Kuweka kizingiti sawa na jumla ya wasaini (hakuna nakala ya akiba)',
      'Kuhifadhi misemo ya urejeshaji kidijitali bila usimbaji',
      'Kutoa ufikiaji wa SuperAdmin kwa watu usiowaamini kikamilifu',
    ],
    statusTitle: 'Hali ya Usalama',
    statuses: [
      { color: 'green', text: 'Imejengwa kwenye mtandao wa Stellar uliojaribiwa kwa vita (tangu 2015)' },
      { color: 'green', text: 'Muunganisho wa mfumo wa OpenZeppelin Smart Account' },
      { color: 'yellow', text: 'Ukaguzi wa kitaalam wa usalama umepangwa kabla ya mtandao mkuu (robo ya 4 ya 2026)' },
      { color: 'gray', text: 'Programu ya zawadi ya hitilafu inakuja baada ya uzinduzi wa mtandao mkuu' },
    ],
  },

  roadmap: {
    heading: 'Ramani ya Maendeleo',
    liveTitle: 'Kwa Sasa Hai kwenye Mtandao wa Majaribio',
    liveFeatures: ['Hazina za saini nyingi', 'Ufikiaji unaotegemea majukumu', 'Vifungo vya muda', 'Ratiba za ugawaji', 'Uagizaji wa CSV kwa wingi', 'Viungo vya mwonekano wa umma', 'Lango la kudai', 'Msaada wa pochi nyingi'],
    phases: [
      { color: 'purple', title: 'Awamu ya 1: Utayari wa Uzalishaji', target: 'Lengo: Julai 2026', items: ['Maandalizi ya usambazaji wa mtandao mkuu', 'Kuimarisha na kujaribu usalama', 'Uboreshaji wa utendaji', 'Ushughulikiaji bora wa hitilafu'] },
      { color: 'blue', title: 'Awamu ya 2: Vipengele vya Hali ya Juu', target: 'Lengo: Septemba 2026', items: ['Vikomo vya matumizi (vikomo vya kila siku/wiki/mwezi)', 'Violezo vilivyoboreshwa vya ugawaji', 'Chaguo za mapendekezo za hali ya juu', 'Uzoefu ulioboreshwa wa simu'] },
      { color: 'cyan', title: 'Awamu ya 3: Uzinduzi wa Mtandao Mkuu', target: 'Lengo: Novemba 2026', items: ['Ukaguzi wa kitaalam wa usalama', 'Muunganisho wa Stellar DEX (biashara ndani ya hazina)', 'SDK ya wasanidi', 'Miongozo na mafunzo ya kina ya watumiaji', '🚀 **Usambazaji wa mtandao mkuu**'] },
    ],
    futureTitle: 'Maono ya Baadaye (2027+)',
    future: [
      { title: 'Muunganisho wa DeFi', desc: 'Mikakati ya mavuno, itifaki za kukopesha, utoaji wa ukwasi' },
      { title: 'Suite ya Biashara', desc: 'Chaguo za lebo nyeupe, SSO, ripoti za uzingatiaji' },
      { title: 'Uendeshaji wa Kiotomatiki', desc: 'Malipo ya mara kwa mara yaliyopangwa, masharti mahiri' },
      { title: 'Miunganisho', desc: 'API, webhooks, miunganisho ya programu za uhasibu' },
    ],
    followTitle: 'Fuata Maendeleo Yetu',
    followDesc: 'Tunajenga hadharani. Tazama hazina yetu ya GitHub kwa masasisho, au rudi hapa kwa habari za hivi karibuni.',
  },

  faq: {
    heading: 'Maswali Yanayoulizwa Mara kwa Mara',
    items: [
      { q: 'Je, Orion Safe ni ya bure kutumia?', a: 'Ndiyo! Jukwaa ni la bure. Unalipa tu ada za kawaida za mtandao wa Stellar (chini ya $0.0001 kwa kila muamala) pamoja na amana ndogo ya mara moja unapounda hazina.' },
      { q: 'Nini hutokea nikipoteza ufunguo wangu wa faragha?', a: 'Maadamu wasaini waliobaki wanafikia kizingiti cha idhini, hazina inabaki kufikika kikamilifu. Kwa mfano, katika hazina ya 2-kati-ya-3, ufunguo mmoja ukipotea, wasaini wengine 2 bado wanaweza kuendesha hazina na hata kuongeza msaini wa kubadilisha.' },
      { q: 'Je, timu ya Orion Safe inaweza kufikia fedha zangu?', a: 'Hapana. Hazina yako ni mkataba mahiri kwenye mnyororo wa Stellar. Ni wasaini unaowaongeza tu wanaweza kuidhinisha miamala. Hatuna ufikiaji maalum, milango ya nyuma, au funguo za msimamizi kwa hazina yako.' },
      { q: 'Naweza kuhifadhi tokeni zipi?', a: 'Mali yoyote ya Stellar: XLM (asilia), USDC, EURC, na maelfu ya tokeni zingine zilizotolewa kwenye mtandao wa Stellar.' },
      { q: 'Miamala ina kasi gani?', a: 'Takriban sekunde 5 baada ya utekelezaji. Mchakato wa idhini hutegemea jinsi wasaini wako wanavyojibu haraka.' },
      { q: 'Naweza kughairi kifungo cha muda au ratiba ya ugawaji?', a: 'Tu ikiwa iliundwa kama "inayoweza kughairiwa". Vifungo visivyoweza kughairiwa haviwezi kughairiwa mara baada ya kuundwa — tokeni zinahakikishiwa kwa mnufaika.' },
      { q: 'Je, kuna programu ya simu?', a: 'Dashibodi inaitikia kikamilifu na inafanya kazi vizuri kwenye vivinjari vya simu. Itumie kwa pochi za simu kama Lobstr au unganisha kupitia WalletConnect.' },
      { q: 'Vipi ikiwa tovuti itazimika?', a: 'Hazina yako ipo kwenye mnyororo wa Stellar, sio kwenye seva zetu. Unaweza kuingiliana nayo kwa kutumia Stellar Laboratory au zana yoyote inayooana hata kama tovuti yetu haipatikani.' },
      { q: 'Wanufaika hudai vipi tokeni zao?', a: 'Shiriki kiungo cha kudai nao (kinapatikana katika Mipangilio → Shiriki). Wanaunganisha pochi zao wenyewe na kudai moja kwa moja — bila kuhitaji ufikiaji wa hazina.' },
      { q: 'Je, kuna kikomo cha idadi ya wasaini?', a: 'Kwa sasa inaunga mkono hadi wasaini 10 kwa kila hazina. Unahitaji zaidi? Wasiliana nasi kwa suluhisho za biashara.' },
      { q: 'Kuna tofauti gani kati ya mtandao wa majaribio na mtandao mkuu?', a: 'Mtandao wa majaribio hutumia tokeni bandia kwa majaribio — hakuna thamani halisi. Mtandao mkuu hutumia tokeni halisi na pesa halisi. Kwa sasa tuko kwenye mtandao wa majaribio, na uzinduzi wa mtandao mkuu umepangwa kwa robo ya 4 ya 2026.' },
      { q: 'Naweza kupata msaada vipi ikiwa kitu kitaenda vibaya?', a: 'Angalia nyaraka hizi kwanza. Ikiwa bado unahitaji msaada, fungua tatizo kwenye hazina yetu ya GitHub au wasiliana kupitia njia zetu za mawasiliano.' },
    ],
  },

  common: {
    locked: '🔒 Imefungwa',
    claimable: '✓ Inayoweza Kudaiwa',
    today: 'Leo',
    unlockDate: '⏰ Tarehe ya Kufungua',
    claimed: 'Imedaiwa',
    viewOnGithub: 'Tazama kwenye GitHub',
  },
};
