import { DocsContent } from './types';

export const docsZhHans: DocsContent = {
  sidebarTitle: '文档',
  sections: [
    { id: 'overview', title: '概览', description: '什么是 Orion Safe？' },
    { id: 'quickstart', title: '快速开始', description: '5 分钟设置指南' },
    { id: 'features', title: '核心功能', description: '你能做什么' },
    { id: 'roles', title: '角色与权限', description: '谁能做什么' },
    { id: 'locks', title: '时间锁与归属', description: '安排代币释放' },
    { id: 'tokens', title: '支持的代币', description: 'USDC、XLM 等' },
    { id: 'architecture', title: '工作原理', description: '幕后机制' },
    { id: 'security', title: '安全性', description: '我们如何保障你的安全' },
    { id: 'faq', title: '常见问题', description: '常见问题解答' },
    { id: 'roadmap', title: '路线图', description: '接下来的计划' },
  ],

  overview: {
    heading: '欢迎使用 Orion Safe',
    intro:
      'Orion Safe 是构建于 Stellar 之上的**多重签名金库平台**。' +
      '可以把它想象成为你的团队、DAO 或组织设立的共享银行账户——但拥有超能力。',
    whyTitle: '为什么使用 Orion Safe？',
    whyItems: [
      { emoji: '🔐', title: '没有单点故障', desc: '需要多方批准——即使一个密钥被泄露，资金依然安全' },
      { emoji: '⚡', title: '极速且低成本', desc: '约 5 秒完成交易，每笔交易费用低于 $0.0001' },
      { emoji: '⏰', title: '基于时间的控制', desc: '将代币锁定至某个日期，或随时间逐步释放' },
      { emoji: '🌍', title: '完全透明', desc: '每个操作都记录在链上——可与任何人分享只读链接' },
    ],
    perfectForTitle: '适用于',
    perfectFor: [
      { icon: '🏛️', title: 'DAO 与金库', desc: '通过透明的多签治理管理社区资金' },
      { icon: '👥', title: '团队与初创公司', desc: '通过基于角色的访问保护公司金库' },
      { icon: '💼', title: '员工归属', desc: '4 年代币归属，含 1 年悬崖期，完全自动化' },
      { icon: '🤝', title: '托管服务', desc: '2-of-2 双方协议，保障交易安全' },
      { icon: '🎁', title: '赠款与薪资', desc: '批量代币分发，按计划释放' },
      { icon: '📊', title: '投资基金', desc: '委员会批准基金管理' },
    ],
    liveTitle: '已在 Stellar 测试网上线',
    liveDesc:
      'Orion Safe 目前已在 Stellar 测试网上线。立即使用测试代币试用！' +
      '主网计划在安全审计后于 2026 年第四季度上线。',
  },

  quickstart: {
    heading: '快速开始指南',
    subtitle: '在 5 分钟内运行你的第一个金库。',
    step1Title: '连接你的钱包',
    step1Intro: '点击右上角的**"连接钱包"**，然后选择你偏好的钱包：',
    wallets: [
      { name: 'Freighter', note: '推荐' },
      { name: 'Lobstr', note: '适合移动端' },
      { name: 'xBull', note: '高级用户' },
      { name: 'Albedo', note: '基于网页' },
    ],
    noWalletTitle: '没有钱包？',
    noWalletDesc: '安装 {{freighter}}——这是一个免费的浏览器扩展，仅需 2 分钟即可设置完成。',
    step2Title: '创建你的金库',
    step2Items: [
      '点击**"创建金库"**',
      '为你的金库命名（例如"团队金库"）',
      '添加签名者钱包地址（能够批准交易的人）',
      '设置你的**阈值**——需要多少个批准',
    ],
    exampleLabel: '示例：2-of-3 多重签名',
    approvedLabel: '2/3 = 已批准！',
    step3Title: '为你的金库充值',
    step3Intro: '你的金库拥有自己的地址。可以像任何 Stellar 钱包一样向其发送代币：',
    step3Items: [
      '从仪表板复制你的金库地址',
      '向该地址发送 XLM、USDC 或任何 Stellar 代币',
      '资金会在约 5 秒内到账',
    ],
    proTipTitle: '专业提示',
    proTipDesc: '对于测试网，可从 {{friendbot}} 获取免费的测试 XLM。',
    step4Title: '进行你的第一笔交易',
    step4Steps: [
      { title: '创建提案', desc: '前往 交易 → 新建 → 输入详情 → 提交' },
      { title: '收集批准', desc: '其他签名者审核后点击"批准"' },
      { title: '执行', desc: '一旦达到阈值，任何人都可以点击"执行"' },
    ],
    doneTitle: '🎉 就这么简单！',
    doneDesc:
      '你现在拥有了一个安全的多签金库。浏览侧边栏，探索时间锁、' +
      '归属计划以及更多高级功能。',
  },

  features: {
    heading: '核心功能',
    multiSig: {
      title: '多重签名安全',
      desc: '要求多人批准交易。阈值由你决定——无论是小团队的 2-of-3，还是大型 DAO 的 5-of-9。',
      configs: ['2-of-3', '3-of-5', '4-of-7', '5-of-9'],
    },
    proposal: {
      title: '基于提案的工作流程',
      desc: '所有交易都经过透明的提案流程。没有意外，完全可问责。',
      steps: [
        { title: '提案', sub: '任何签名者' },
        { title: '批准', sub: '达到阈值' },
        { title: '执行', sub: '任何人' },
      ],
    },
    txTypes: {
      title: '交易类型',
      items: [
        { icon: '💸', title: '转账', desc: '批准后立即发送代币。简单、直接的支付。' },
        { icon: '🔒', title: '时间锁', desc: '将代币锁定至特定日期。非常适合托管或计划释放。' },
        { icon: '📈', title: '归属', desc: '随时间逐步释放，含可选悬崖期。非常适合员工代币。' },
      ],
    },
    dashboard: {
      title: '仪表板导航',
      views: [
        { name: '仪表板', desc: '概览与统计' },
        { name: '资产', desc: '代币余额' },
        { name: '交易', desc: '提案与历史' },
        { name: '成员', desc: '签名者与角色' },
        { name: '时间锁', desc: '计划释放' },
        { name: '归属', desc: '代币归属' },
        { name: '联系人', desc: '地址簿' },
        { name: '设置', desc: '配置' },
      ],
    },
    publicAccess: {
      title: '公开访问与分享',
      cards: [
        { title: '🔗 公开查看链接', desc: '与投资者、审计师或公众分享只读视图。他们可以查看余额和活动，但无法执行任何操作。' },
        { title: '🎁 领取链接', desc: '受益人可以使用自己的钱包直接领取被锁定或已归属的代币——无需访问金库。' },
      ],
    },
  },

  roles: {
    heading: '角色与权限',
    intro: 'Orion Safe 使用基于角色的系统来控制谁能做什么。这在保持安全的同时提供了灵活性。',
    cards: [
      { name: 'SuperAdmin', badge: '完全控制', desc: '对金库的完全控制。SuperAdmin 可以执行所有操作，包括影响金库结构和安全性的操作。', canLabel: '可以：', can: '添加/移除签名者、更改批准阈值、取消任何可撤销的锁、更新金库设置，以及 Admin 和 Executor 能做的一切。' },
      { name: 'Admin', badge: '运营', desc: '日常运营管理者。Admin 处理大多数金库活动，但无法更改金库的安全设置。', canLabel: '可以：', can: '创建提案、批准交易、执行已批准的交易、创建时间锁和归属计划、管理联系人。' },
      { name: 'Executor', badge: '批准与执行', desc: '批准权限。Executor 可以对提案投票并执行已批准的交易，但无法发起新提案。', canLabel: '可以：', can: '批准或拒绝提案、执行已达到阈值的交易。' },
      { name: 'Viewer', badge: '只读', desc: '观察者访问权限。Viewer 可以查看一切，但无法执行任何操作。非常适合审计师或利益相关者。', canLabel: '可以：', can: '查看金库余额、交易历史、提案、锁定以及所有活动。' },
    ],
    matrixTitle: '权限摘要',
    matrixHeaders: { action: '操作', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: '查看金库与余额', super: true, admin: true, exec: true, view: true },
      { action: '创建提案', super: true, admin: true, exec: false, view: false },
      { action: '批准提案', super: true, admin: true, exec: true, view: false },
      { action: '执行交易', super: true, admin: true, exec: true, view: false },
      { action: '创建时间锁／归属', super: true, admin: true, exec: false, view: false },
      { action: '取消可撤销的锁', super: true, admin: false, exec: false, view: false },
      { action: '添加／移除签名者', super: true, admin: false, exec: false, view: false },
      { action: '更改阈值', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: '最佳实践：角色分配',
    bestPractice: [
      '将 SuperAdmin 限制在 1-2 名可信赖的人（创始人、高管）',
      '为管理日常运营的财务团队成员使用 Admin',
      '为只批准而不发起的董事会成员使用 Executor',
      '为利益相关者、审计师或公开透明使用 Viewer',
    ],
  },

  locks: {
    heading: '时间锁与归属',
    intro: '控制代币何时变得可用。无论你需要托管、计划支付还是员工代币归属——我们都能满足你。',
    timeLockTitle: '时间锁',
    timeLockDesc: '将代币锁定至特定日期。只有在解锁时间过后，受益人才能领取**全部金额**。在该日期之前，代币完全无法访问。',
    timeLockExampleLabel: '示例：托管存款',
    timeLockExampleAmount: '10,000 USDC',
    timeLockUses: [
      { icon: '💼', title: '托管', desc: '在条件满足前持有资金' },
      { icon: '🎯', title: '里程碑付款', desc: '交付物完成时释放' },
      { icon: '🏦', title: '储蓄目标', desc: '防止冲动取款' },
    ],
    vestingTitle: '归属计划',
    vestingDesc: '随时间**逐步释放**代币，含可选的悬崖期。这是员工薪酬和投资者分配的行业标准。',
    vestingExampleLabel: '示例：4 年员工归属，含 1 年悬崖期',
    vestingExampleAmount: '100,000 代币',
    vestingBarCliff: '悬崖期（1 年）',
    vestingBarLinear: '线性归属 → 100%',
    vestingTimeline: { start: '开始', cliff: '悬崖：解锁 25%', y2: '第 2 年：50%', y3: '第 3 年：75%', y4: '第 4 年：100%' },
    howVestingTitle: '归属如何运作',
    howVestingSteps: [
      { title: '悬崖期：', desc: '在悬崖日期之前不会归属任何代币。如果有人在悬崖期之前离开，将一无所获。' },
      { title: '悬崖解锁：', desc: '在悬崖日期，一部分会立即解锁（4 年计划通常为 25%）。' },
      { title: '线性归属：', desc: '悬崖期之后，代币会持续归属直到结束日期。' },
      { title: '随时领取：', desc: '受益人可以随时领取已归属的代币——没有截止期限。' },
    ],
    revTitle: '可撤销 vs. 不可撤销',
    revocable: { title: '✓ 可撤销', desc: 'SuperAdmin 可以取消锁定并将未归属的代币退回金库。', bestFor: '最适合：员工归属（含离职条款）、有条件赠款、内部分配' },
    nonRevocable: { title: '✗ 不可撤销', desc: '一旦创建便无法取消。无论如何，代币都将保证归受益人所有。', bestFor: '最适合：投资者分配、不可撤销的赠款、无信任托管、顾问代币' },
    bulkTitle: '批量创建',
    bulkDesc: '需要一次创建多个锁定？使用批量上传功能配合 CSV 文件。非常适合团队代币分发、薪资或赠款计划。',
    bulkPrepLabel: '只需准备一个包含以下内容的电子表格：',
    bulkFields: [
      '受益人钱包地址',
      '代币金额',
      '解锁日期（用于时间锁）或归属参数',
      '是否可撤销',
      '可选描述',
    ],
    bulkNote: '上传 CSV，审核条目，每批最多可创建 10 个锁定。',
  },

  tokens: {
    heading: '支持的代币',
    usdcTitle: 'Stellar 上的原生 USDC',
    usdcSubtitle: 'Circle 的官方稳定币——非封装、非跨链',
    usdcDesc: 'Orion Safe 对 USDC 提供一流支持。创建以美元计价的金库、用稳定货币设置薪资归属，或在无波动风险的情况下锁定托管资金。',
    allTitle: '所有支持的资产',
    allIntro: 'Orion Safe 支持 **Stellar 网络上的任何代币**：',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Stellar 的原生代币' },
      { emoji: '💵', name: 'USDC', desc: '美元稳定币' },
      { emoji: '💶', name: 'EURC', desc: '欧元稳定币' },
      { emoji: '🪙', name: '任何代币', desc: '自定义 Stellar 资产' },
    ],
    whatTitle: '你能用代币做什么',
    whatItems: [
      { icon: '💸', title: '多签转账', desc: '通过多重签名批准发送任何代币' },
      { icon: '🔒', title: '锁定任何资产', desc: '将 USDC、XLM 或自定义代币锁定至特定日期' },
      { icon: '📈', title: '代币归属', desc: '为任何 Stellar 资产创建归属计划' },
      { icon: '📊', title: '批量分发', desc: '通过 CSV 向多个接收方分发代币' },
    ],
    testTitle: '获取测试网代币',
    xlmTitle: '⭐ XLM（测试网）',
    xlmSteps: [
      '前往 {{laboratory}}',
      '输入你的测试网钱包地址',
      '点击 "Fund account with Friendbot"',
      '即时获得 10,000 测试 XLM！',
    ],
    usdcTestTitle: '💵 USDC（测试网）',
    usdcTestSteps: [
      '在你的钱包中添加 USDC 信任线（Freighter → Manage Assets → Add USDC）',
      '使用测试网 USDC 水龙头，或在测试网 DEX 上兑换 XLM',
    ],
  },

  architecture: {
    heading: '工作原理',
    intro: '简单说明你使用 Orion Safe 时幕后发生的事情。',
    basicsTitle: '基础知识',
    basicsParas: [
      '当你创建金库时，Orion Safe 会在 Stellar 区块链上部署一份**智能合约**。这份智能合约就像一个可编程的保险箱，用于保管你的资产。',
      '智能合约强制执行所有规则：谁可以发起交易、需要多少批准、被锁定的代币何时可以释放等等。**没有人能绕过这些规则**——即使是 Orion Safe 团队也不行。',
    ],
    flowTitle: '发送代币时发生的事情',
    flowSteps: [
      { title: '你创建提案', desc: '指定接收方、金额和可选备注。提案被记录到区块链上。' },
      { title: '其他签名者批准', desc: '每次批准都记录在链上。每个人都能看到谁已批准。' },
      { title: '达到阈值', desc: '一旦足够的签名者批准（例如 3 个中的 2 个），交易即可执行。' },
      { title: '执行并确认', desc: '任何人都可以触发执行。代币即时转移（约 5 秒）。完成！' },
    ],
    whyTitle: '我们为什么构建在 Stellar 上',
    whyItems: [
      { icon: '⚡', title: '快速', desc: '交易约 5 秒确认' },
      { icon: '💰', title: '低成本', desc: '每笔交易费用低于 $0.0001' },
      { icon: '🏦', title: '受信赖', desc: '被 Circle、MoneyGram、Franklin Templeton 使用' },
      { icon: '🔐', title: '安全', desc: '自 2015 年以来经受考验的网络' },
      { icon: '💵', title: '原生 USDC', desc: '真正的稳定币，非封装代币' },
      { icon: '🌍', title: '全球化', desc: '只要有互联网接入，随处可用' },
    ],
    truthTitle: '重要：区块链是真相之源',
    truthDesc: '你的金库存在于 Stellar 区块链上，而非我们的服务器上。即使我们的网站下线，你的金库和资金仍将安全，并可通过其他 Stellar 工具访问。我们只是提供一个易于使用的界面，用于与你的链上金库交互。',
  },

  security: {
    heading: '安全性',
    intro: 'Orion Safe 如何保障你的资产安全。',
    principlesTitle: '核心安全原则',
    principles: [
      { title: '链上强制执行', desc: '所有规则都由区块链上的智能合约强制执行。网站只是一个用户界面——区块链才是权威。' },
      { title: '没有后门', desc: '没有人——即使是 Orion Safe 团队——能在没有正确签名的情况下访问你的金库或转移你的资金。' },
      { title: '默认多重签名', desc: '即使一个密钥被泄露，攻击者在未达到你的批准阈值前也无法转移资金。' },
    ],
    threatsTitle: '我们如何防范威胁',
    threats: [
      { threat: '签名者密钥泄露', mitigation: '多签阈值可防止单密钥攻击。其他签名者可以移除被泄露的密钥。' },
      { threat: '恶意提案', mitigation: '需要多方批准。其他签名者可以拒绝不良提案。' },
      { threat: '密钥丢失', mitigation: '只要剩余签名者达到阈值，金库仍可访问。' },
      { threat: '网站宕机', mitigation: '你的金库存在于区块链上。可通过其他 Stellar 工具访问。' },
      { threat: '数据库泄露', mitigation: '我们的数据库只是用于加快加载的缓存。区块链才是真相之源。' },
    ],
    bestTitle: '安全最佳实践',
    doTitle: '✓ 应该做',
    dos: [
      '为签名者密钥使用硬件钱包（如 Ledger）',
      '将阈值保持在 2 或更高（切勿单一签名者）',
      '定期审查你的签名者列表',
      '为不同目的使用不同的金库',
      '先用小额进行测试',
      '安全地备份你的恢复短语',
    ],
    dontTitle: '✗ 不应该做',
    donts: [
      '通过电子邮件或聊天分享私钥',
      '为多个关键金库使用相同的密钥',
      '长时间忽视待处理的提案',
      '将阈值设为等于签名者总数（没有冗余）',
      '以未加密的数字方式存储恢复短语',
      '向你不完全信任的人授予 SuperAdmin 访问权限',
    ],
    statusTitle: '安全状态',
    statuses: [
      { color: 'green', text: '构建于经受考验的 Stellar 网络（自 2015 年）' },
      { color: 'green', text: '集成 OpenZeppelin Smart Account 框架' },
      { color: 'yellow', text: '计划在主网上线前进行专业安全审计（2026 年第四季度）' },
      { color: 'gray', text: '漏洞赏金计划将在主网上线后推出' },
    ],
  },

  roadmap: {
    heading: '路线图',
    liveTitle: '目前已在测试网上线',
    liveFeatures: ['多签金库', '基于角色的访问', '时间锁', '归属计划', '批量 CSV 导入', '公开查看链接', '领取门户', '多钱包支持'],
    phases: [
      { color: 'purple', title: '阶段 1：生产就绪', target: '目标：2026 年 7 月', items: ['主网部署准备', '安全加固与测试', '性能优化', '改进的错误处理'] },
      { color: 'blue', title: '阶段 2：高级功能', target: '目标：2026 年 9 月', items: ['支出限额（每日／每周／每月上限）', '增强的归属模板', '高级提案选项', '改进的移动端体验'] },
      { color: 'cyan', title: '阶段 3：主网上线', target: '目标：2026 年 11 月', items: ['专业安全审计', 'Stellar DEX 集成（金库内交易）', '开发者 SDK', '全面的用户指南与教程', '🚀 **主网部署**'] },
    ],
    futureTitle: '未来愿景（2027 年及以后）',
    future: [
      { title: 'DeFi 集成', desc: '收益策略、借贷协议、流动性提供' },
      { title: '企业套件', desc: '白标选项、SSO、合规报告' },
      { title: '自动化', desc: '计划的定期付款、智能条件' },
      { title: '集成', desc: 'API、webhook、会计软件连接' },
    ],
    followTitle: '关注我们的进展',
    followDesc: '我们正在公开构建。关注我们的 GitHub 仓库以获取更新，或随时回到这里查看最新消息。',
  },

  faq: {
    heading: '常见问题',
    items: [
      { q: 'Orion Safe 免费使用吗？', a: '是的！平台是免费的。你只需支付标准的 Stellar 网络费用（每笔交易低于 $0.0001），以及创建金库时的一笔小额一次性存款。' },
      { q: '如果我丢失了私钥会怎样？', a: '只要剩余的签名者达到批准阈值，金库仍可完全访问。例如，在 2-of-3 金库中，如果丢失一个密钥，其他 2 个签名者仍可操作金库，甚至可以添加替代签名者。' },
      { q: 'Orion Safe 团队能访问我的资金吗？', a: '不能。你的金库是 Stellar 区块链上的智能合约。只有你添加的签名者才能授权交易。我们对你的金库没有任何特殊访问权限、后门或管理员密钥。' },
      { q: '我可以存储哪些代币？', a: '任何 Stellar 资产：XLM（原生）、USDC、EURC，以及在 Stellar 网络上发行的数千种其他代币。' },
      { q: '交易有多快？', a: '执行后约 5 秒。批准流程取决于你的签名者响应的速度。' },
      { q: '我可以取消时间锁或归属计划吗？', a: '只有在创建时设置为"可撤销"的情况下才可以。不可撤销的锁一旦创建便无法取消——代币将保证归受益人所有。' },
      { q: '有移动应用吗？', a: '仪表板完全响应式，在移动浏览器上运行良好。可与 Lobstr 等移动钱包配合使用，或通过 WalletConnect 连接。' },
      { q: '如果网站宕机怎么办？', a: '你的金库存在于 Stellar 区块链上，而非我们的服务器上。即使我们的网站不可用，你也可以使用 Stellar Laboratory 或任何兼容工具与其交互。' },
      { q: '受益人如何领取他们的代币？', a: '与他们分享领取链接（位于 设置 → 分享）。他们连接自己的钱包并直接领取——无需访问金库。' },
      { q: '签名者数量有限制吗？', a: '目前每个金库最多支持 10 个签名者。需要更多？请联系我们获取企业解决方案。' },
      { q: '测试网和主网有什么区别？', a: '测试网使用虚拟代币进行测试——没有真实价值。主网使用真实代币和真实资金。我们目前在测试网上，主网计划于 2026 年第四季度上线。' },
      { q: '如果出现问题，我如何获得帮助？', a: '请先查阅本文档。如果仍需帮助，请在我们的 GitHub 仓库提交问题，或通过我们的联系渠道与我们取得联系。' },
    ],
  },

  common: {
    locked: '🔒 已锁定',
    claimable: '✓ 可领取',
    today: '今天',
    unlockDate: '⏰ 解锁日期',
    claimed: '已领取',
    viewOnGithub: '在 GitHub 上查看',
  },
};
