import { DocsContent } from './types';

export const docsZu: DocsContent = {
  sidebarTitle: 'Amabhukwana',
  sections: [
    { id: 'overview', title: 'Ukubuka Konke', description: 'Iyini i-Orion Safe?' },
    { id: 'quickstart', title: 'Ukuqala Okusheshayo', description: 'Umhlahlandlela wokusetha wemizuzu emi-5' },
    { id: 'features', title: 'Izici Eziyinhloko', description: 'Okungenziwa' },
    { id: 'roles', title: 'Izindima Nezimvume', description: 'Ubani ongenzani' },
    { id: 'locks', title: 'Ukukhiya Kwesikhathi Nokugcina', description: 'Hlela ukukhululwa kwamathokheni' },
    { id: 'tokens', title: 'Amathokheni Asekelwayo', description: 'I-USDC, i-XLM nokuningi' },
    { id: 'architecture', title: 'Indlela Esebenza Ngayo', description: 'Ngaphansi kwesigubhu' },
    { id: 'security', title: 'Ezokuphepha', description: 'Indlela esikugcina ngayo uphephile' },
    { id: 'faq', title: 'Imibuzo Evame Ukubuzwa', description: 'Imibuzo evamile' },
    { id: 'roadmap', title: 'Imephu Yendlela', description: 'Okuzayo' },
  ],

  overview: {
    heading: 'Wamukelekile ku-Orion Safe',
    intro:
      'I-Orion Safe iyinkundla **yesikhwama esinezimpawu eziningi** eyakhelwe ku-Stellar. ' +
      'Yicabange njenge-akhawunti yasebhange eyabelwana ngayo iqembu lakho, i-DAO, noma inhlangano yakho — kodwa enamandla angaphezulu.',
    whyTitle: 'Kungani Usebenzisa i-Orion Safe?',
    whyItems: [
      { emoji: '🔐', title: 'Akukho Iphuzu Elilodwa Lokwehluleka', desc: 'Kudingeka izimvume eziningi — noma ukhiye owodwa ungase ungenelelwe, izimali zihlala ziphephile' },
      { emoji: '⚡', title: 'Sheshayo Futhi Eshibhile', desc: 'Imisebenzi yamasekhondi angu-~5, ngaphansi kuka-$0.0001 ngomsebenzi ngamunye' },
      { emoji: '⏰', title: 'Izilawuli Ezisekelwe Esikhathini', desc: 'Khiya amathokheni kuze kufike usuku, noma uwakhulule kancane kancane ngokuhamba kwesikhathi' },
      { emoji: '🌍', title: 'Ukukhanya Okugcwele', desc: 'Sonke isenzo siqoshwa ku-cheni — yabelana ngamalinki okufunda kuphela nanoma ubani' },
    ],
    perfectForTitle: 'Ifanele',
    perfectFor: [
      { icon: '🏛️', title: 'Ama-DAO Nezikhwama', desc: 'Phatha izimali zomphakathi ngokubusa kwezimpawu eziningi okusobala' },
      { icon: '👥', title: 'Amaqembu Nezinkampani Ezisafufusa', desc: 'Vikela isikhwama senkampani ngokufinyelela okusekelwe ezindimeni' },
      { icon: '💼', title: 'Ukugcina Kwabasebenzi', desc: 'Ukugcina amathokheni weminyaka emi-4 nge-cliff yonyaka owodwa, okwenziwa ngokuzenzakalelayo ngokugcwele' },
      { icon: '🤝', title: 'Izinsizakalo ze-Escrow', desc: 'Isivumelwano esivumelekile esingu-2-kwezi-2 semisebenzi ephephile' },
      { icon: '🎁', title: 'Izibonelelo Nemiholo', desc: 'Ukusatshalaliswa kwamathokheni ngobuningi nokukhululwa okuhleliwe' },
      { icon: '📊', title: 'Izikhwama Zokutshala Imali', desc: 'Ukuvunywa kwekomidi ekuphatheni isikhwama' },
    ],
    liveTitle: 'Iqhutshwa ku-Stellar Testnet',
    liveDesc:
      'I-Orion Safe okwamanje iyaqhutshwa ku-Stellar testnet. Yizame manje ngamathokheni okuhlola! ' +
      'Ukwethulwa kwe-mainnet kuhlelelwe ikota yesi-4 ka-2026 ngemva kokuhlolwa kwezokuphepha.',
  },

  quickstart: {
    heading: 'Umhlahlandlela Wokuqala Ngokushesha',
    subtitle: 'Yenza isikhwama sakho sokuqala sisebenze ngaphansi kwemizuzu emi-5.',
    step1Title: 'Xhuma Isikhwama Sakho',
    step1Intro: 'Chofoza **"Xhuma Isikhwama"** ekhoneni eliphezulu ngakwesokudla bese ukhetha isikhwama osithandayo:',
    wallets: [
      { name: 'Freighter', note: 'Kunconywa' },
      { name: 'Lobstr', note: 'Inobungane neselula' },
      { name: 'xBull', note: 'Abasebenzisi abanamandla' },
      { name: 'Albedo', note: 'Esekelwe kuwebhu' },
    ],
    noWalletTitle: 'Awunaso isikhwama?',
    noWalletDesc: 'Faka i-{{freighter}} — kuyisandiso sesiphequluli samahhala esithatha imizuzu emi-2 ukusetha.',
    step2Title: 'Dala Isikhwama Sakho',
    step2Items: [
      'Chofoza **"Dala Isikhwama"**',
      'Nika isikhwama sakho igama (isb. "Isikhwama Seqembu")',
      'Faka amakheli ezikhwama zabasayini (abantu abangavuma imisebenzi)',
      'Setha **umkhawulo** wakho — zingaki izimvume ezidingekayo',
    ],
    exampleLabel: 'Isibonelo: I-2-kwezi-3 Yezimpawu Eziningi',
    approvedLabel: '2/3 = Kuvunyiwe!',
    step3Title: 'Faka Imali Esikhwameni Sakho',
    step3Intro: 'Isikhwama sakho sinekheli laso. Thumela amathokheni kuso njenganoma yisiphi isikhwama se-Stellar:',
    step3Items: [
      'Kopisha ikheli lesikhwama sakho kusuka kudeshibhodi',
      'Thumela i-XLM, i-USDC, noma noma yiliphi ithokheni le-Stellar kulelo kheli',
      'Izimali zivela kungakapheli amasekhondi angu-~5',
    ],
    proTipTitle: 'Ithiphu Lochwepheshe',
    proTipDesc: 'Kwi-testnet, thola i-XLM yokuhlola yamahhala ku-{{friendbot}}.',
    step4Title: 'Yenza Umsebenzi Wakho Wokuqala',
    step4Steps: [
      { title: 'Dala Isiphakamiso', desc: 'Iya ku-Imisebenzi → Okusha → Faka imininingwane → Hambisa' },
      { title: 'Qoqa Izimvume', desc: 'Abanye abasayini bayabuyekeza bese bechofoza "Vuma"' },
      { title: 'Yenza', desc: 'Lapho umkhawulo usufinyelelwe, noma ubani angachofoza "Yenza"' },
    ],
    doneTitle: '🎉 Yilokho!',
    doneDesc:
      'Manje usunesikhwama esiphephile sezimpawu eziningi. Hlola ibha eseceleni ukuze uthole ukukhiya kwesikhathi, ' +
      'izinhlelo zokugcina, nezici ezithuthukile.',
  },

  features: {
    heading: 'Izici Eziyinhloko',
    multiSig: {
      title: 'Ezokuphepha Zezimpawu Eziningi',
      desc: 'Funa abantu abaningi ukuthi bavume imisebenzi. Wena ukhetha umkhawulo — noma ku-2-kwezi-3 kuyiqembu elincane noma ku-5-kwezi-9 kuyi-DAO enkulu.',
      configs: ['2-kwezi-3', '3-kwezi-5', '4-kwezi-7', '5-kwezi-9'],
    },
    proposal: {
      title: 'Ukusebenza Okusekelwe Eziphakamisweni',
      desc: 'Yonke imisebenzi idlula enqubweni yesiphakamiso esisobala. Akukho izimangaliso, ukuziphendulela okugcwele.',
      steps: [
        { title: 'Phakamisa', sub: 'Noma yimuphi umsayini' },
        { title: 'Vuma', sub: 'Finyelela umkhawulo' },
        { title: 'Yenza', sub: 'Noma ubani' },
      ],
    },
    txTypes: {
      title: 'Izinhlobo Zemisebenzi',
      items: [
        { icon: '💸', title: 'Ukudlulisa', desc: 'Thumela amathokheni ngokushesha ngemva kokuvunywa. Izinkokhelo ezilula, eziqondile.' },
        { icon: '🔒', title: 'Ukukhiya Kwesikhathi', desc: 'Khiya amathokheni kuze kufike usuku oluthile. Kufanele i-escrow noma ukukhululwa okuhleliwe.' },
        { icon: '📈', title: 'Ukugcina', desc: 'Ukukhululwa kancane kancane ngokuhamba kwesikhathi nge-cliff engakhethwa. Kuhle kumathokheni abasebenzi.' },
      ],
    },
    dashboard: {
      title: 'Ukuzulazula Kwedeshibhodi',
      views: [
        { name: 'Ideshibhodi', desc: 'Ukubuka konke nezibalo' },
        { name: 'Amafa', desc: 'Amabhalansi amathokheni' },
        { name: 'Imisebenzi', desc: 'Iziphakamiso nomlando' },
        { name: 'Amalungu', desc: 'Abasayini nezindima' },
        { name: 'Ukukhiya Kwesikhathi', desc: 'Ukukhululwa okuhleliwe' },
        { name: 'Ukugcina', desc: 'Ukugcina amathokheni' },
        { name: 'Oxhumana Nabo', desc: 'Incwadi yamakheli' },
        { name: 'Izilungiselelo', desc: 'Ukucushwa' },
      ],
    },
    publicAccess: {
      title: 'Ukufinyelela Komphakathi Nokwabelana',
      cards: [
        { title: '🔗 Ilinki Lokubuka Komphakathi', desc: 'Yabelana ngombono wokufunda kuphela nabatshalimali, abahloli, noma umphakathi. Bangabona amabhalansi nomsebenzi kodwa abakwazi ukuthatha noma yiziphi izenzo.' },
        { title: '🎁 Ilinki Lokufuna', desc: 'Abazuzayo bangafuna amathokheni abo akhiyiwe noma agciniwe ngokuqondile besebenzisa isikhwama sabo — akudingeki ukufinyelela kwesikhwama.' },
      ],
    },
  },

  roles: {
    heading: 'Izindima Nezimvume',
    intro: 'I-Orion Safe isebenzisa uhlelo olusekelwe ezindimeni ukulawula ukuthi ubani ongenzani. Lokhu kunikeza ukuguquguquka kanti kuphinde kugcine ezokuphepha.',
    cards: [
      { name: 'SuperAdmin', badge: 'Ukulawula Okugcwele', desc: 'Ukulawula okuphelele kwesikhwama. Ama-SuperAdmin angenza yonke into, kuhlanganise nezenzo ezithinta isakhiwo sesikhwama nezokuphepha.', canLabel: 'Angakwazi:', can: 'Ukungeza/ukususa abasayini, ukushintsha umkhawulo wezimvume, ukukhansela noma yikuphi ukukhiya okungahoxiswa, ukubuyekeza izilungiselelo zesikhwama, kanye nakho konke ama-Admin nama-Executor angakwenza.' },
      { name: 'Admin', badge: 'Imisebenzi', desc: 'Umphathi wemisebenzi yansuku zonke. Ama-Admin aphatha imisebenzi eminingi yesikhwama kodwa awakwazi ukushintsha izilungiselelo zokuphepha zesikhwama.', canLabel: 'Angakwazi:', can: 'Ukudala iziphakamiso, ukuvuma imisebenzi, ukwenza imisebenzi evunyiwe, ukudala ukukhiya kwesikhathi nezinhlelo zokugcina, ukuphatha oxhumana nabo.' },
      { name: 'Executor', badge: 'Vuma Futhi Yenza', desc: 'Igunya lokuvuma. Ama-Executor angavotela iziphakamiso futhi enze imisebenzi evunyiwe, kodwa awakwazi ukuqala emisha.', canLabel: 'Angakwazi:', can: 'Ukuvuma noma ukwala iziphakamiso, ukwenza imisebenzi efinyelele umkhawulo.' },
      { name: 'Viewer', badge: 'Funda Kuphela', desc: 'Ukufinyelela komqaphi. Ama-Viewer angabona yonke into kodwa awakwazi ukuthatha noma yiziphi izenzo. Kufanele abahloli noma ababambiqhaza.', canLabel: 'Angakwazi:', can: 'Ukubuka amabhalansi esikhwama, umlando wemisebenzi, iziphakamiso, ukukhiya, nawo wonke umsebenzi.' },
    ],
    matrixTitle: 'Isifinyezo Sezimvume',
    matrixHeaders: { action: 'Isenzo', super: 'SuperAdmin', admin: 'Admin', exec: 'Executor', view: 'Viewer' },
    matrixRows: [
      { action: 'Buka isikhwama namabhalansi', super: true, admin: true, exec: true, view: true },
      { action: 'Dala iziphakamiso', super: true, admin: true, exec: false, view: false },
      { action: 'Vuma iziphakamiso', super: true, admin: true, exec: true, view: false },
      { action: 'Yenza imisebenzi', super: true, admin: true, exec: true, view: false },
      { action: 'Dala ukukhiya kwesikhathi / ukugcina', super: true, admin: true, exec: false, view: false },
      { action: 'Khansela ukukhiya okungahoxiswa', super: true, admin: false, exec: false, view: false },
      { action: 'Ngeza/susa abasayini', super: true, admin: false, exec: false, view: false },
      { action: 'Shintsha umkhawulo', super: true, admin: false, exec: false, view: false },
    ],
    bestPracticeTitle: 'Umkhuba Ongcono: Ukwabiwa Kwezindima',
    bestPractice: [
      'Gcina i-SuperAdmin kubantu aba-1-2 abathenjiwe (abasunguli, abaphathi)',
      'Sebenzisa i-Admin emalungwini eqembu lezezimali aphatha imisebenzi yansuku zonke',
      'Sebenzisa i-Executor emalungwini ebhodi avuma kuphela, angaqali',
      'Sebenzisa i-Viewer kubabambiqhaza, abahloli, noma ukukhanya komphakathi',
    ],
  },

  locks: {
    heading: 'Ukukhiya Kwesikhathi Nokugcina',
    intro: 'Lawula ukuthi amathokheni atholakala nini. Noma udinga i-escrow, izinkokhelo ezihleliwe, noma ukugcina amathokheni abasebenzi — sikuvikele.',
    timeLockTitle: 'Ukukhiya Kwesikhathi',
    timeLockDesc: 'Khiya amathokheni kuze kufike usuku oluthile. Ozuzayo angafuna **inani eliphelele** kuphela ngemva kokudlula kwesikhathi sokuvula. Ngaphambi kwalolo suku, amathokheni awafinyeleleki ngokuphelele.',
    timeLockExampleLabel: 'Isibonelo: Idiphozithi ye-Escrow',
    timeLockExampleAmount: '10,000 USDC',
    timeLockUses: [
      { icon: '💼', title: 'I-Escrow', desc: 'Bamba izimali kuze kufezeke izimo' },
      { icon: '🎯', title: 'Izinkokhelo Zezigaba', desc: 'Khulula lapho okuletheka kuqediwe' },
      { icon: '🏦', title: 'Izinjongo Zokonga', desc: 'Vimbela ukukhipha okungazindlanga' },
    ],
    vestingTitle: 'Izinhlelo Zokugcina',
    vestingDesc: 'Khulula amathokheni **kancane kancane ngokuhamba kwesikhathi** nge-cliff engakhethwa. Lokhu kuyizinga lemboni lenkokhelo yabasebenzi nokwabiwa kwabatshalimali.',
    vestingExampleLabel: 'Isibonelo: Ukugcina Kwabasebenzi Kweminyaka emi-4 ne-Cliff Yonyaka owodwa',
    vestingExampleAmount: 'amathokheni angu-100,000',
    vestingBarCliff: 'I-Cliff (1 nyaka)',
    vestingBarLinear: 'Ukugcina Okuqondile → 100%',
    vestingTimeline: { start: 'Ukuqala', cliff: 'I-Cliff: 25% kuyavuleka', y2: 'Unyaka 2: 50%', y3: 'Unyaka 3: 75%', y4: 'Unyaka 4: 100%' },
    howVestingTitle: 'Indlela Ukugcina Okusebenza Ngayo',
    howVestingSteps: [
      { title: 'Isikhathi se-Cliff:', desc: 'Akukho okugcinwayo kuze kufike usuku lwe-cliff. Uma othile ehamba ngaphambi kwe-cliff, akatholi lutho.' },
      { title: 'Ukuvuleka kwe-Cliff:', desc: 'Ngosuku lwe-cliff, ingxenye iyavuleka ngokushesha (ngokuvamile u-25% wohlelo lweminyaka emi-4).' },
      { title: 'Ukugcina Okuqondile:', desc: 'Ngemva kwe-cliff, amathokheni agcinwa njalo kuze kufike usuku lokugcina.' },
      { title: 'Funa Nganoma Yisiphi Isikhathi:', desc: 'Abazuzayo bangafuna amathokheni abo agciniwe noma nini lapho bethanda — akukho imingcele.' },
    ],
    revTitle: 'Okungahoxiswa vs. Okungenakuhoxiswa',
    revocable: { title: '✓ Okungahoxiswa', desc: 'I-SuperAdmin ingakhansela ukukhiya futhi ibuyisele amathokheni angagciniwe esikhwameni.', bestFor: 'Kuhle ku: Ukugcina kwabasebenzi (nesigaba sokuxoshwa), izibonelelo ezinemibandela, ukwabiwa kwangaphakathi' },
    nonRevocable: { title: '✗ Okungenakuhoxiswa', desc: 'Akukhanseleki uma sekudaliwe. Amathokheni aqinisekisiwe kozuzayo noma kungenzekani.', bestFor: 'Kuhle ku: Ukwabiwa kwabatshalimali, izibonelelo ezingenakuhoxiswa, i-escrow engenakwethenjwa, amathokheni omeluleki' },
    bulkTitle: 'Ukudala Ngobuningi',
    bulkDesc: 'Udinga ukudala ukukhiya okuningi ngesikhathi esisodwa? Sebenzisa isici sokulayisha ngobuningi ngefayela le-CSV. Kufanele ukusatshalaliswa kwamathokheni eqembu, imiholo, noma izinhlelo zezibonelelo.',
    bulkPrepLabel: 'Vele ulungiselele ispredishithi ngalokhu:',
    bulkFields: [
      'Ikheli lesikhwama lozuzayo',
      'Inani lethokheni',
      'Usuku lokuvula (lokukhiya kwesikhathi) noma amapharamitha okugcina',
      'Ukuthi ngabe kungahoxiswa yini',
      'Incazelo engakhethwa',
    ],
    bulkNote: 'Layisha i-CSV, buyekeza amangeniso, bese udala ukukhiya okufika ku-10 ngeqoqo ngalinye.',
  },

  tokens: {
    heading: 'Amathokheni Asekelwayo',
    usdcTitle: 'I-USDC Yomdabu ku-Stellar',
    usdcSubtitle: 'Imali ezinzile esemthethweni ye-Circle — ayisongiwe, ayixhunyiwe',
    usdcDesc: 'I-Orion Safe inokusekelwa kwezinga lokuqala kwe-USDC. Dala izikhwama ezikalwe ngamadola, misa ukugcina komholo ngemali ezinzile, noma ukhiye izimali ze-escrow ngaphandle kwengozi yokuguquguquka.',
    allTitle: 'Wonke Amafa Asekelwayo',
    allIntro: 'I-Orion Safe isekela **noma yiliphi ithokheni kunethiwekhi ye-Stellar**:',
    assets: [
      { emoji: '⭐', name: 'XLM', desc: 'Ithokheni yomdabu ye-Stellar' },
      { emoji: '💵', name: 'USDC', desc: 'Imali ezinzile yeDola laseMelika' },
      { emoji: '💶', name: 'EURC', desc: 'Imali ezinzile yeYuro' },
      { emoji: '🪙', name: 'Noma Yiliphi Ithokheni', desc: 'Amafa angokwezifiso e-Stellar' },
    ],
    whatTitle: 'Ongakwenza Ngamathokheni',
    whatItems: [
      { icon: '💸', title: 'Ukudlulisa Kwezimpawu Eziningi', desc: 'Thumela noma yiliphi ithokheni ngemvume yezimpawu eziningi' },
      { icon: '🔒', title: 'Khiya Noma Yiliphi Ifa Ngesikhathi', desc: 'Khiya i-USDC, i-XLM, noma amathokheni angokwezifiso kuze kufike usuku oluthile' },
      { icon: '📈', title: 'Ukugcina Amathokheni', desc: 'Dala izinhlelo zokugcina zanoma yiliphi ifa le-Stellar' },
      { icon: '📊', title: 'Ukusatshalaliswa Ngobuningi', desc: 'Sabalalisa amathokheni kubamukeli abaningi nge-CSV' },
    ],
    testTitle: 'Ukuthola Amathokheni e-Testnet',
    xlmTitle: '⭐ XLM (Testnet)',
    xlmSteps: [
      'Iya ku-{{laboratory}}',
      'Faka ikheli lesikhwama sakho se-testnet',
      'Chofoza "Fund account with Friendbot"',
      'Thola i-XLM yokuhlola engu-10,000 ngokushesha!',
    ],
    usdcTestTitle: '💵 USDC (Testnet)',
    usdcTestSteps: [
      'Faka i-trustline ye-USDC esikhwameni sakho (Freighter → Manage Assets → Add USDC)',
      'Sebenzisa umthombo we-USDC we-testnet noma ushintshe i-XLM ku-DEX ye-testnet',
    ],
  },

  architecture: {
    heading: 'Indlela Esebenza Ngayo',
    intro: 'Incazelo elula yokwenzeka ngemuva kwesigubhu lapho usebenzisa i-Orion Safe.',
    basicsTitle: 'Izisekelo',
    basicsParas: [
      'Lapho udala isikhwama, i-Orion Safe ithumela **inkontileka ehlakaniphile** ku-blockchain ye-Stellar. Le nkontileka ehlakaniphile injengebhokisi lokugcina elingahlelwa eligcina amafa akho.',
      'Inkontileka ehlakaniphile iphoqelela yonke imithetho: ubani ongaphakamisa imisebenzi, zingaki izimvume ezidingekayo, nini amathokheni akhiyiwe angakhululwa, nokunye. **Akekho ongawedlula le mithetho** — ngisho neqembu le-Orion Safe.',
    ],
    flowTitle: 'Okwenzekayo Lapho Uthumela Amathokheni',
    flowSteps: [
      { title: 'Udala Isiphakamiso', desc: 'Cacisa umamukeli, inani, nesixwayiso esingakhethwa. Isiphakamiso siqoshwa ku-blockchain.' },
      { title: 'Abanye Abasayini Bayavuma', desc: 'Imvume ngayinye iqoshwa ku-cheni. Wonke umuntu angabona ukuthi ubani ovumile.' },
      { title: 'Umkhawulo Ufinyelelwe', desc: 'Lapho abasayini abanele sebevumile (isb. 2 kwabantu 3), umsebenzi usulungele ukwenziwa.' },
      { title: 'Yenza Futhi Qinisekisa', desc: 'Noma ubani angaqalisa ukwenziwa. Amathokheni anyakaza ngokushesha (~5 amasekhondi). Kwenziwe!' },
    ],
    whyTitle: 'Kungani Sakhe ku-Stellar',
    whyItems: [
      { icon: '⚡', title: 'Sheshayo', desc: 'Imisebenzi iqinisekiswa ngamasekhondi angu-~5' },
      { icon: '💰', title: 'Eshibhile', desc: 'Ngaphansi kuka-$0.0001 ngomsebenzi ngamunye' },
      { icon: '🏦', title: 'Ethenjiwe', desc: 'Isetshenziswa yi-Circle, i-MoneyGram, i-Franklin Templeton' },
      { icon: '🔐', title: 'Ephephile', desc: 'Inethiwekhi ehlolwe kakhulu kusukela ngo-2015' },
      { icon: '💵', title: 'I-USDC Yomdabu', desc: 'Izimali ezinzile zangempela, hhayi amathokheni asongiwe' },
      { icon: '🌍', title: 'Yomhlaba Wonke', desc: 'Isebenza noma kuphi lapho kunokufinyelela kwe-inthanethi' },
    ],
    truthTitle: 'Okubalulekile: I-Blockchain Iwumthombo Weqiniso',
    truthDesc: 'Isikhwama sakho sikhona ku-blockchain ye-Stellar, hhayi kumaseva ethu. Ngisho noma iwebhusayithi yethu ingaphumi ku-inthanethi, isikhwama sakho nezimali zakho zizohlala ziphephile futhi zifinyeleleka ngamanye amathuluzi e-Stellar. Sinikeza nje isixhumi esibonakalayo esinobungane nomsebenzisi ukuze uxhumane nesikhwama sakho esiku-cheni.',
  },

  security: {
    heading: 'Ezokuphepha',
    intro: 'Indlela i-Orion Safe egcina ngayo amafa akho ephephile.',
    principlesTitle: 'Imigomo Eyinhloko Yezokuphepha',
    principles: [
      { title: 'Ukuphoqelelwa Ku-Cheni', desc: 'Yonke imithetho iphoqelelwa yinkontileka ehlakaniphile ku-blockchain. Iwebhusayithi iyisixhumi somsebenzisi nje — i-blockchain iyigunya.' },
      { title: 'Akukho Iminyango Yangemuva', desc: 'Akekho — ngisho neqembu le-Orion Safe — ongafinyelela isikhwama sakho noma anyakazise izimali zakho ngaphandle kwezimpawu ezifanele.' },
      { title: 'Izimpawu Eziningi Ngokuzenzakalelayo', desc: 'Ngisho noma ukhiye owodwa ungenelelwe, abahlaseli abakwazi ukunyakazisa izimali ngaphandle kokufinyelela umkhawulo wakho wezimvume.' },
    ],
    threatsTitle: 'Indlela Esivikela Ngayo Ezinsongweni',
    threats: [
      { threat: 'Ukhiye womsayini ongenelelwe', mitigation: 'Umkhawulo wezimpawu eziningi uvimbela ukuhlasela kokhiye oyedwa. Abanye abasayini bangasusa ukhiye ongenelelwe.' },
      { threat: 'Isiphakamiso esinobungozi', mitigation: 'Sidinga izimvume eziningi. Abanye abasayini bangala iziphakamiso ezimbi.' },
      { threat: 'Okhiye abalahlekile', mitigation: 'Inqobo nje uma abasayini abasele befinyelela umkhawulo, isikhwama sihlala sifinyeleleka.' },
      { threat: 'Iwebhusayithi iyaphuma', mitigation: 'Isikhwama sakho sikhona ku-blockchain. Sifinyelele ngamanye amathuluzi e-Stellar.' },
      { threat: 'Ukuphulwa kwedathabhesi', mitigation: 'Idathabhesi yethu iyinqolobane kuphela yokulayisha okusheshayo. I-Blockchain iwumthombo weqiniso.' },
    ],
    bestTitle: 'Imikhuba Engcono Yezokuphepha',
    doTitle: '✓ Yenza',
    dos: [
      'Sebenzisa izikhwama zehadiwe (njenge-Ledger) zokhiye babasayini',
      'Gcina umkhawulo u-2 noma ngaphezulu (ungalokothi umsayini oyedwa)',
      'Buyekeza njalo uhlu lwakho lwabasayini',
      'Sebenzisa izikhwama ezihlukene ngezinjongo ezihlukene',
      'Hlola ngezinani ezincane kuqala',
      'Gcina amabhakaphu wamabinzana akho okutholisisa ngokuphepha',
    ],
    dontTitle: '✗ Ungenzi',
    donts: [
      'Ukwabelana ngokhiye abayimfihlo nge-imeyili noma ngengxoxo',
      'Ukusebenzisa ukhiye ofanayo ezikhwameni eziningi ezibalulekile',
      'Ukushaya indiva iziphakamiso ezilindile isikhathi eside kakhulu',
      'Ukusetha umkhawulo ulingane nesamba sabasayini (akukho ukweqisa)',
      'Ukugcina amabinzana okutholisisa ngedijithali engabhalwe ngekhodi',
      'Ukunika ukufinyelela kwe-SuperAdmin kubantu ongabethembi ngokugcwele',
    ],
    statusTitle: 'Isimo Sezokuphepha',
    statuses: [
      { color: 'green', text: 'Yakhelwe kunethiwekhi ye-Stellar ehlolwe kakhulu (kusukela ngo-2015)' },
      { color: 'green', text: 'Ukuhlanganiswa kohlaka lwe-OpenZeppelin Smart Account' },
      { color: 'yellow', text: 'Ukuhlolwa kwezokuphepha kochwepheshe kuhleliwe ngaphambi kwe-mainnet (ikota yesi-4 ka-2026)' },
      { color: 'gray', text: 'Uhlelo lomklomelo wezinambuzane luzayo ngemva kokwethulwa kwe-mainnet' },
    ],
  },

  roadmap: {
    heading: 'Imephu Yendlela',
    liveTitle: 'Okwamanje Iqhutshwa ku-Testnet',
    liveFeatures: ['Izikhwama zezimpawu eziningi', 'Ukufinyelela okusekelwe ezindimeni', 'Ukukhiya kwesikhathi', 'Izinhlelo zokugcina', 'Ukungenisa kwe-CSV ngobuningi', 'Amalinki okubuka komphakathi', 'Iphothali yokufuna', 'Ukusekelwa kwezikhwama eziningi'],
    phases: [
      { color: 'purple', title: 'Isigaba 1: Ukulungela Ukukhiqiza', target: 'Inhloso: Julayi 2026', items: ['Ukulungiselela ukuthunyelwa kwe-mainnet', 'Ukuqinisa nokuhlola kwezokuphepha', 'Ukuthuthukiswa kokusebenza', 'Ukuphathwa kwamaphutha okuthuthukisiwe'] },
      { color: 'blue', title: 'Isigaba 2: Izici Ezithuthukile', target: 'Inhloso: Septhemba 2026', items: ['Imikhawulo yokusebenzisa (imikhawulo yansuku zonke/yeviki/yenyanga)', 'Izifanekiso zokugcina ezithuthukisiwe', 'Izinketho zeziphakamiso ezithuthukile', 'Isipiliyoni seselula esithuthukisiwe'] },
      { color: 'cyan', title: 'Isigaba 3: Ukwethulwa kwe-Mainnet', target: 'Inhloso: Novemba 2026', items: ['Ukuhlolwa kwezokuphepha kochwepheshe', 'Ukuhlanganiswa kwe-Stellar DEX (ukuhweba ngaphakathi kwesikhwama)', 'I-SDK yonjiniyela', 'Imihlahlandlela yabasebenzisi nezifundo eziphelele', '🚀 **Ukuthunyelwa kwe-Mainnet**'] },
    ],
    futureTitle: 'Umbono Wesikhathi Esizayo (2027+)',
    future: [
      { title: 'Ukuhlanganiswa kwe-DeFi', desc: 'Amasu enzuzo, amaphrothokholi okuboleka, ukunikezwa kukancweba' },
      { title: 'Isethi Yebhizinisi', desc: 'Izinketho zelebula emhlophe, i-SSO, ukubika kokuthobela' },
      { title: 'Ukuzenzakalela', desc: 'Izinkokhelo eziphindaphindayo ezihleliwe, izimo ezihlakaniphile' },
      { title: 'Ukuhlanganiswa', desc: 'I-API, ama-webhook, ukuxhumana kwesofthiwe yokubala' },
    ],
    followTitle: 'Landela Inqubekela Phambili Yethu',
    followDesc: 'Sakha obala. Buka indawo yethu yokugcina ye-GitHub ukuze uthole izibuyekezo, noma ubuyele lapha ukuze uthole izindaba zakamuva.',
  },

  faq: {
    heading: 'Imibuzo Evame Ukubuzwa',
    items: [
      { q: 'Ingabe i-Orion Safe imahhala ukuyisebenzisa?', a: 'Yebo! Inkundla imahhala. Ukhokha kuphela izimali ezivamile zenethiwekhi ye-Stellar (ngaphansi kuka-$0.0001 ngomsebenzi ngamunye) kanye nedephozithi encane yesikhathi esisodwa lapho udala isikhwama.' },
      { q: 'Kwenzekani uma ngilahlekelwa ukhiye wami oyimfihlo?', a: 'Inqobo nje uma abasayini abasele befinyelela umkhawulo wezimvume, isikhwama sihlala sifinyeleleka ngokugcwele. Isibonelo, esikhwameni se-2-kwezi-3, uma ukhiye owodwa ulahleka, abanye abasayini aba-2 basengakwazi ukuphatha isikhwama futhi bangeze umsayini omusha.' },
      { q: 'Ingabe iqembu le-Orion Safe lingafinyelela izimali zami?', a: 'Cha. Isikhwama sakho siyinkontileka ehlakaniphile ku-blockchain ye-Stellar. Abasayini obangezayo kuphela abangagunyaza imisebenzi. Asinakho ukufinyelela okukhethekile, iminyango yangemuva, noma okhiye baphathi kwisikhwama sakho.' },
      { q: 'Yimaphi amathokheni engingawagcina?', a: 'Noma yiliphi ifa le-Stellar: i-XLM (yomdabu), i-USDC, i-EURC, namathokheni ayizinkulungwane akhishwe kunethiwekhi ye-Stellar.' },
      { q: 'Isheshe kangakanani imisebenzi?', a: 'Cishe amasekhondi angu-5 ngemva kokwenziwa. Inqubo yokuvuma incike ekuthini abasayini bakho baphendula ngokushesha kangakanani.' },
      { q: 'Ngingakwazi ukukhansela ukukhiya kwesikhathi noma uhlelo lokugcina?', a: 'Kuphela uma kwakhiwe njenge-"okungahoxiswa". Ukukhiya okungenakuhoxiswa akukhanseleki uma sekudaliwe — amathokheni aqinisekisiwe kozuzayo.' },
      { q: 'Ingabe ikhona i-app yeselula?', a: 'Ideshibhodi iphendula ngokugcwele futhi isebenza kahle kuziphequluli zeselula. Yisebenzise nezikhwama zeselula ezifana ne-Lobstr noma uxhume nge-WalletConnect.' },
      { q: 'Kuthiwani uma iwebhusayithi iphuma?', a: 'Isikhwama sakho sikhona ku-blockchain ye-Stellar, hhayi kumaseva ethu. Ungaxhumana naso usebenzisa i-Stellar Laboratory noma noma yiliphi ithuluzi elihambisanayo ngisho noma iwebhusayithi yethu ingatholakali.' },
      { q: 'Abazuzayo bawafuna kanjani amathokheni abo?', a: 'Yabelana ngelinki lokufuna nabo (litholakala ku-Izilungiselelo → Yabelana). Baxhuma isikhwama sabo bese befuna ngokuqondile — akudingeki ukufinyelela kwesikhwama.' },
      { q: 'Ingabe ukhona umkhawulo wenani labasayini?', a: 'Okwamanje isekela abasayini abafika ku-10 ngesikhwama ngasinye. Udinga abaningi? Xhumana nathi ukuze uthole izixazululo zebhizinisi.' },
      { q: 'Uyini umehluko phakathi kwe-testnet ne-mainnet?', a: 'I-Testnet isebenzisa amathokheni amanga ukuhlola — awanawo umvalue wangempela. I-Mainnet isebenzisa amathokheni angempela nemali yangempela. Okwamanje sisku-testnet, ukwethulwa kwe-mainnet kuhlelelwe ikota yesi-4 ka-2026.' },
      { q: 'Ngithola kanjani usizo uma kukhona okungahambi kahle?', a: 'Hlola la mabhukwana kuqala. Uma usadinga usizo, vula udaba kundawo yethu yokugcina ye-GitHub noma uxhumane ngezindlela zethu zokuxhumana.' },
    ],
  },

  common: {
    locked: '🔒 Kukhiyiwe',
    claimable: '✓ Kungafunwa',
    today: 'Namuhla',
    unlockDate: '⏰ Usuku Lokuvula',
    claimed: 'Kufuniwe',
    viewOnGithub: 'Buka ku-GitHub',
  },
};
